-- Table DFN_PRICE.ESP_SYMBOLMAP_CUST

  CREATE TABLE DFN_PRICE.ESP_SYMBOLMAP_CUST 
   (	EXCHANGE VARCHAR2(8), 
	SYMBOL VARCHAR2(25), 
	EXCHANGECODE VARCHAR2(2), 
	SYMBOLCODE VARCHAR2(10), 
	INSTRUMENTTYPE NUMBER, 
	CATEGORY VARCHAR2(5), 
	SECTOR VARCHAR2(12), 
	CURRENCY VARCHAR2(4), 
	LASTUPDATED DATE, 
	IS_ACTIVE NUMBER(1,0), 
	MARKET_CODE VARCHAR2(10), 
	DECIMAL_PLACES NUMBER, 
	INCREMENT_ID NUMBER, 
	DEC_CORRECTION_FACTOR NUMBER, 
	LOT_SIZE NUMBER(10,3), 
	UNIT VARCHAR2(20), 
	SYMBOLTYPE NUMBER, 
	RIC_CODE VARCHAR2(10), 
	ISINCODE VARCHAR2(13), 
	FREE_FLOAT LONG, 
	INST_CODE VARCHAR2(10)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SYMBOLMAP_CUST


  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_CUST ADD CONSTRAINT PK_ESP_SYMBOLMAP_CUST PRIMARY KEY (EXCHANGE, SYMBOL, INSTRUMENTTYPE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_CUST MODIFY (INSTRUMENTTYPE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_CUST MODIFY (DEC_CORRECTION_FACTOR NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_SYMBOLMAP_CUST
