-- Table DFN_PRICE.ESP_SECTORS_DESCRIPTIONS

  CREATE TABLE DFN_PRICE.ESP_SECTORS_DESCRIPTIONS 
   (	EXCHANGECODE VARCHAR2(8), 
	SECTOR_ID VARCHAR2(20), 
	LANGUAGE CHAR(2), 
	DESCRIPTION NVARCHAR2(100)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SECTORS_DESCRIPTIONS


  ALTER TABLE DFN_PRICE.ESP_SECTORS_DESCRIPTIONS ADD CONSTRAINT PK_ESP_SECTORS_DESCRIPTIONS PRIMARY KEY (EXCHANGECODE, SECTOR_ID, LANGUAGE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SECTORS_DESCRIPTIONS MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SECTORS_DESCRIPTIONS MODIFY (SECTOR_ID NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SECTORS_DESCRIPTIONS MODIFY (LANGUAGE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_SECTORS_DESCRIPTIONS
