-- Table DFN_PRICE.ESP_MARKETS

  CREATE TABLE DFN_PRICE.ESP_MARKETS 
   (	EXCHANGE VARCHAR2(8), 
	MARKET_CODE VARCHAR2(10), 
	DESCRIPTION_1 VARCHAR2(50), 
	DESCRIPTION_2 NVARCHAR2(100), 
	MARKETSTATUS NUMBER(18,0), 
	NOOFUPS NUMBER(18,0), 
	NOOFDOWNS NUMBER(18,0), 
	NOOFNOCHANGE NUMBER(18,0), 
	VOLUME NUMBER(18,0), 
	TURNOVER NUMBER(18,3), 
	SYMBOLS_TRADED NUMBER(18,0), 
	NOOFTRADES NUMBER(18,0), 
	LAST_UPDATED DATE, 
	SYMBOLEXT VARCHAR2(10), 
	IS_DEFAULT NUMBER(18,0), 
	IS_TICKER_DISPLAY NUMBER(18,0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_MARKETS


  ALTER TABLE DFN_PRICE.ESP_MARKETS ADD CONSTRAINT PK_ESP_MARKETS PRIMARY KEY (EXCHANGE, MARKET_CODE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_MARKETS MODIFY (EXCHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETS MODIFY (MARKET_CODE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_MARKETS
