-- Table DFN_PRICE.ESP_NEWS

  CREATE TABLE DFN_PRICE.ESP_NEWS 
   (	NEWS_ID NUMBER(18,0), 
	EXTERNAL_ID NUMBER(18,0), 
	NEWSPROVIDER VARCHAR2(20), 
	COUNTRYCODE VARCHAR2(20), 
	EXCHANGECODE VARCHAR2(20), 
	SYMBOL VARCHAR2(100), 
	NEWSDATE DATE, 
	LANGUAGE VARCHAR2(10), 
	HEADLINE NVARCHAR2(2000), 
	BODY NCLOB, 
	KEYWORDS NVARCHAR2(100), 
	SOURCE NVARCHAR2(100)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_NEWS


  ALTER TABLE DFN_PRICE.ESP_NEWS ADD CONSTRAINT PK_ESP_NEWS PRIMARY KEY (NEWS_ID)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_NEWS MODIFY (NEWS_ID NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_NEWS MODIFY (NEWSPROVIDER NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_NEWS MODIFY (LANGUAGE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_NEWS
