-- Table DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES

  CREATE TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES 
   (	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	TRADETIME DATE, 
	SESSION_ID NUMBER(3,0), 
	LASTTRADEPRICE NUMBER(18,3), 
	LASTTRADEQUANTITY NUMBER(20,0), 
	CHANGE NUMBER(18,3), 
	PERCENTCHANGED NUMBER(18,3), 
	PREVIOUSCLOSED NUMBER(18,3), 
	BUY_BROKER VARCHAR2(12), 
	SELL_BROKER VARCHAR2(12), 
	SEQUENCE_NO NUMBER(10,0), 
	TYPE CHAR(1), 
	ODDLOT NUMBER(10,0), 
	SPLITS NUMBER(10,0), 
	INSTRUMENT_TYPE NUMBER(10,0) DEFAULT (0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES


  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES ADD CONSTRAINT PK_ESP_INTRADAY_COMBINE_TRADE PRIMARY KEY (EXCHANGECODE, SEQUENCE_NO)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (TRADETIME NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (LASTTRADEPRICE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (LASTTRADEQUANTITY NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (CHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES MODIFY (SEQUENCE_NO NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_INTRADAY_COMBINE_TRADES
