-- Table DFN_PRICE.ESP_EXCHANGEMASTER

  CREATE TABLE DFN_PRICE.ESP_EXCHANGEMASTER 
   (	EXCHANGE VARCHAR2(8), 
	EXCHANGECODE CHAR(2), 
	DESCRIPTION_1 VARCHAR2(40), 
	DESCRIPTION_2 NVARCHAR2(80), 
	PRIMARY_CURRENCY VARCHAR2(4), 
	MARKETSTATUS NUMBER(10,0), 
	LAST_EOD_DATE DATE, 
	LAST_ACTIVE_DATE DATE, 
	LAST_INIT_DATE DATE, 
	ISDEFAULTS NUMBER(1,0) DEFAULT 1, 
	IS_ACTIVE NUMBER(5,0), 
	TIMEZONECODE NUMBER(10,0), 
	PATH NUMBER(10,0), 
	COUNTRY_CODE CHAR(10), 
	PARAMETERS VARCHAR2(100), 
	NOOFUPS NUMBER(10,0), 
	NOOFDOWNS NUMBER(10,0), 
	NOOFNOCHANGE NUMBER(10,0), 
	VOLUME NUMBER(10,0), 
	TURNOVER NUMBER(18,3), 
	SYMBOLS_TRADED NUMBER(10,0), 
	NOOFTRADES NUMBER(10,0), 
	INTRADAY_OHLC_DAYS NUMBER(10,0), 
	SATELLITE_DATA_PORT NUMBER(10,0), 
	SATELLITE_ENABLED NUMBER(10,0), 
	SATELLITE_FILE_PORT NUMBER(10,0), 
	IS_EXPAND_SUBMKTS NUMBER(1,0), 
	DEFAULT_DECIMAL_PTS NUMBER(10,0), 
	PRICE_MODIFICATION_FACTOR NUMBER(10,0), 
	SHORT_DESCRIPTION_1 VARCHAR2(50), 
	SHORT_DESCRIPTION_2 NVARCHAR2(100), 
	ARCHIVE_GEN_STATUS NUMBER(1,0), 
	ARCHIVE_GEN_TIME DATE, 
	DEC_CORRECTION_FACTOR NUMBER(10,0), 
	DESCRIPTION_3 NVARCHAR2(80), 
	SHORT_DESCRIPTION_3 NVARCHAR2(100), 
	IS_EOD_COMPLETED NUMBER(1,0), 
	CONTENT_SERVER_IP VARCHAR2(20), 
	IS_ALLOW_DISPLAY NUMBER DEFAULT 0, 
	DISPLAY_EXCHANGE VARCHAR2(25)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_EXCHANGEMASTER


  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER ADD CONSTRAINT PK_EXCHANGEMASTER PRIMARY KEY (EXCHANGE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (EXCHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (LAST_EOD_DATE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (LAST_ACTIVE_DATE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (LAST_INIT_DATE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (ISDEFAULTS NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGEMASTER MODIFY (IS_ALLOW_DISPLAY NOT NULL ENABLE)
/



-- Comments for  DFN_PRICE.ESP_EXCHANGEMASTER

   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.EXCHANGE IS 'Mubasher Driven Exchange long code ()'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.EXCHANGECODE IS 'Mubasher Driven Exchnage short code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.DESCRIPTION_1 IS 'English Description (Eg:Abu Dhabi Securities Market)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.DESCRIPTION_2 IS 'Arabic Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.PRIMARY_CURRENCY IS 'Primary Currency Code(Eg:AED)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.MARKETSTATUS IS 'Current Status of the Exchange (Eg:3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.LAST_EOD_DATE IS 'Last End of date(Eg:2006-06-08 18:00:00.000)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.LAST_ACTIVE_DATE IS 'Last Exchange Active Date(Eg:2008-07-21 07:21:23.000)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.LAST_INIT_DATE IS 'Last Exchange Initialized Date(Eg:2008-06-30 11:00:06.373)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.ISDEFAULTS IS 'Full Exchange driven or Symbol driven exchange (Eg:0 or 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.IS_ACTIVE IS 'Exchange is enabled or disabled in the system(Eg:1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.TIMEZONECODE IS 'Exchange Time zone code(Eg:3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.PATH IS '1 : Primary path 
/ 2: Secondry path'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.COUNTRY_CODE IS 'Standard country code(Eg:AE for dubai)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.PARAMETERS IS 'Exchange code,county code , path (Eg:A,AE,1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.NOOFUPS IS 'No of symbols increased in price compared to previoued closed price (Eg:25)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.NOOFDOWNS IS 'No of symbols decreased in price compared to previoued closed price(Eg:18)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.NOOFNOCHANGE IS 'No of symbols have no change in price compared to previoued closed price(Eg:20)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.VOLUME IS 'Total quantity traded  for the exchange(Eg:125782563)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.TURNOVER IS 'Total traded value for the exchange(Eg:990463435.110)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SYMBOLS_TRADED IS 'Total number of symbols traded for the exchange(Eg:45)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.NOOFTRADES IS 'Total number of trades for the exchange(Eg:3410)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.INTRADAY_OHLC_DAYS IS 'Number of past days which OHLC should be generated(Eg:5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SATELLITE_DATA_PORT IS 'Data port for the satellite connection(Eg:8013)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SATELLITE_ENABLED IS 'satellite data enabled/ disabled for the exchange(Eg:1 or 0)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SATELLITE_FILE_PORT IS 'File port for the satellite connection(Eg:8014)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.IS_EXPAND_SUBMKTS IS 'Exchange contains sub markets or not (Eg: 1 or 0)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.DEFAULT_DECIMAL_PTS IS 'Default number of decimal places for the exchange in price values (Eg:2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.PRICE_MODIFICATION_FACTOR IS 'Modification factor for price data (Eg:100)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SHORT_DESCRIPTION_1 IS 'English Short Description(Eg:Morocco(CSE))'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.SHORT_DESCRIPTION_2 IS 'Arabic Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.ARCHIVE_GEN_STATUS IS 'Archive files generated or not at the end of the day(Eg:1 or 0)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.ARCHIVE_GEN_TIME IS 'Last Archive generation time (Eg:2008-02-14 16:56:31.670)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.DEC_CORRECTION_FACTOR IS 'correction factor for price data (Eg:100)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_EXCHANGEMASTER.IS_EOD_COMPLETED IS 'end of day DB process is completed or not(Eg:1 or 0)'
/
-- End of DDL Script for Table DFN_PRICE.ESP_EXCHANGEMASTER

ALTER TABLE dfn_price.esp_exchangemaster
 MODIFY (
  exchangecode CHAR (5 BYTE),
  primary_currency NOT NULL,
  marketstatus NOT NULL,
  turnover NUMBER (20, 3)
 )
/