-- Table DFN_PRICE.ESP_LANGUAGE_MASTER

  CREATE TABLE DFN_PRICE.ESP_LANGUAGE_MASTER 
   (	LANGUAGE_CODE CHAR(2), 
	LANGUAGE_NAME VARCHAR2(50)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_LANGUAGE_MASTER


  ALTER TABLE DFN_PRICE.ESP_LANGUAGE_MASTER ADD CONSTRAINT PK_ESP_LANGUAGE_MASTER PRIMARY KEY (LANGUAGE_CODE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_LANGUAGE_MASTER MODIFY (LANGUAGE_CODE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_LANGUAGE_MASTER
