-- Table DFN_PRICE.SYS_VERSION

  CREATE TABLE DFN_PRICE.SYS_VERSION 
   (	SYS_DB_VERSION VARCHAR2(100), 
	SYS_RDBM_VERSION VARCHAR2(100), 
	SYS_SRDBM_VERSION VARCHAR2(100), 
	SYS_DATE DATE DEFAULT SYSDATE, 
	SYS_NARRATION VARCHAR2(100)
   ) 
/






-- End of DDL Script for Table DFN_PRICE.SYS_VERSION
