-- Table DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST

  CREATE TABLE DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST 
   (	EXCHANGE VARCHAR2(8), 
	SYMBOL VARCHAR2(25), 
	INSTRUMENTTYPE NUMBER DEFAULT 0, 
	LANGUAGE VARCHAR2(2), 
	SYMBOLDESCRIPTION NVARCHAR2(255), 
	SYMBOLSHORTDESCRIPTION NVARCHAR2(60)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST


  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST ADD CONSTRAINT PK_ESP_SYMBOLMAP_DESC_CUST PRIMARY KEY (EXCHANGE, SYMBOL, INSTRUMENTTYPE, LANGUAGE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST MODIFY (INSTRUMENTTYPE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST MODIFY (LANGUAGE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_SYMBOLMAP_DESC_CUST
