-- Table DFN_PRICE.ESP_SECTORS

  CREATE TABLE DFN_PRICE.ESP_SECTORS 
   (	EXCHANGECODE VARCHAR2(8), 
	SECTOR_ID VARCHAR2(20), 
	DESCRIPTION_1 VARCHAR2(50), 
	DESCRIPTION_2 NVARCHAR2(100), 
	SHORTDESCRIPTION_1 VARCHAR2(50), 
	SHORTDESCRIPTION_2 NVARCHAR2(100), 
	SORT_ORDER NUMBER(3,0), 
	INCREMENT_ID NUMBER(10,0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SECTORS


  ALTER TABLE DFN_PRICE.ESP_SECTORS ADD CONSTRAINT PK_ESP_SECTORS PRIMARY KEY (EXCHANGECODE, SECTOR_ID)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SECTORS MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SECTORS MODIFY (SECTOR_ID NOT NULL ENABLE)
/



-- Comments for  DFN_PRICE.ESP_SECTORS

   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.EXCHANGECODE IS 'Mubasher Driven Exchnage short code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.SECTOR_ID IS 'Sector ID'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.DESCRIPTION_1 IS 'English Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.DESCRIPTION_2 IS 'Arabic Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.SHORTDESCRIPTION_1 IS 'English Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SECTORS.SHORTDESCRIPTION_2 IS 'Arabic Short Description'
/
-- End of DDL Script for Table DFN_PRICE.ESP_SECTORS
