-- Table DFN_PRICE.ESP_INTRADAY_TRADES

  CREATE TABLE DFN_PRICE.ESP_INTRADAY_TRADES 
   (	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	TRADETIME DATE, 
	SESSION_ID NUMBER(3,0), 
	LASTTRADEPRICE NUMBER(18,3), 
	LASTTRADEQUANTITY NUMBER(20,0), 
	CHANGE NUMBER(18,3), 
	PERCENTCHANGED NUMBER(18,3), 
	PREVIOUSCLOSED NUMBER(18,3), 
	BUY_BROKER VARCHAR2(12), 
	SELL_BROKER VARCHAR2(12), 
	SEQUENCE_NO NUMBER(10,0), 
	TYPE CHAR(1), 
	ODDLOT NUMBER(10,0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_INTRADAY_TRADES


  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES ADD CONSTRAINT PK_ESP_INTRADAY_TRADES PRIMARY KEY (EXCHANGECODE, SEQUENCE_NO)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (TRADETIME NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (LASTTRADEPRICE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (LASTTRADEQUANTITY NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (CHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_TRADES MODIFY (SEQUENCE_NO NOT NULL ENABLE)
/



-- Comments for  DFN_PRICE.ESP_INTRADAY_TRADES

   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.EXCHANGECODE IS 'Mubasher Driven Exchnage short code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.SYMBOL IS 'Symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.TRADETIME IS 'Trade time in GMT'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.SESSION_ID IS 'Market session ID'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.LASTTRADEPRICE IS 'Trade price'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.LASTTRADEQUANTITY IS 'Trade quantity'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.CHANGE IS 'Net change (lasttradeprice - previousclosed)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.PERCENTCHANGED IS '( change / previousclosed ) x 100'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.PREVIOUSCLOSED IS 'Previous days close price '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.BUY_BROKER IS 'The Broker ID of the buyer '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.SELL_BROKER IS 'The Broker ID of the seller'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.SEQUENCE_NO IS 'Trade sequence number'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.TYPE IS 'Trade Type'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_INTRADAY_TRADES.ODDLOT IS 'Is oddlot trade or not (1 - Yes / 0 - No)'
/
-- End of DDL Script for Table DFN_PRICE.ESP_INTRADAY_TRADES
