-- Table DFN_PRICE.ESP_SYMBOLMAP

  CREATE TABLE DFN_PRICE.ESP_SYMBOLMAP 
   (	EXCHANGE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	EXCHANGECODE VARCHAR2(2), 
	SYMBOLCODE VARCHAR2(25), 
	INSTRUMENTTYPE NUMBER(10,0), 
	CATEGORY CHAR(5), 
	SYMBOLDESCRIPTION_1 VARCHAR2(255), 
	SYMBOLDESCRIPTION_2 NVARCHAR2(510), 
	SYMBOLSHORTDESCRIPTION_1 VARCHAR2(100), 
	SYMBOLSHORTDESCRIPTION_2 NVARCHAR2(120), 
	SECTOR VARCHAR2(12), 
	CURRENCY VARCHAR2(4), 
	STATUS NUMBER(10,0), 
	LASTUPDATED DATE, 
	ACCESSLEVEL NUMBER(2,0) DEFAULT NULL, 
	MARGINABILITY NUMBER(10,2) DEFAULT 0, 
	TRADING_SYMBOL VARCHAR2(10), 
	EXG_SYM_CODE VARCHAR2(25), 
	MATURITY_DAY VARCHAR2(2), 
	MATURITY_MYEAR VARCHAR2(6), 
	BASE_SYMBOL VARCHAR2(10), 
	IS_ACTIVE NUMBER(1,0), 
	MARKET_CODE VARCHAR2(10), 
	EXPIRY_DATE DATE, 
	SECURITY_TYPE VARCHAR2(10), 
	PRICE_MODIFICATION_FACTOR NUMBER(10,0) DEFAULT 1, 
	DECIMAL_PLACES NUMBER(10,0) DEFAULT 2, 
	INCREMENT_ID NUMBER(10,0), 
	DEC_CORRECTION_FACTOR NUMBER(4,0) DEFAULT 1, 
	LOT_SIZE NUMBER(18,3), 
	UNIT VARCHAR2(20), 
	EXPIRYDATE DATE, 
	UNDERLINESYMBOL VARCHAR2(25), 
	STRIKEPRICE NUMBER(18,6), 
	ISINCODE CHAR(13), 
	NATIONALITY VARCHAR2(10), 
	SYMBOL_GROUP VARCHAR2(5), 
	UNDERLINE_EXCHANGE VARCHAR2(25), 
	OPTION_TYPE NUMBER(10,0), 
	FIRST_SUBS_STARTDATE DATE, 
	FIRST_SUBS_EXPDATE DATE, 
	SEC_SUBS_STARTDATE DATE, 
	SEC_SUBS_EXPDATE DATE, 
	FIRST_SUBS_START_HIJRI VARCHAR2(10), 
	FIRST_SUBS_EXP_HIJRI VARCHAR2(10), 
	SEC_SUBS_START_HIJRI VARCHAR2(10), 
	SEC_SUBS_EXP_HIJRI VARCHAR2(10), 
	MARKET_ID VARCHAR2(50)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SYMBOLMAP


  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP ADD CONSTRAINT PK_ESP_SYMBOLMAP PRIMARY KEY (EXCHANGE, SYMBOL, INSTRUMENTTYPE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (EXCHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (INSTRUMENTTYPE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (PRICE_MODIFICATION_FACTOR NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (DECIMAL_PLACES NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP MODIFY (DEC_CORRECTION_FACTOR NOT NULL ENABLE)
/



-- Comments for  DFN_PRICE.ESP_SYMBOLMAP

   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.EXCHANGE IS 'Mubasher Driven Exchange long code ()'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOL IS 'Symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.EXCHANGECODE IS 'Mubasher Driven Exchnage short code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOLCODE IS 'Symbol code '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.INSTRUMENTTYPE IS 'Indicated the type of the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOLDESCRIPTION_1 IS 'English Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOLDESCRIPTION_2 IS 'Arabic Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOLSHORTDESCRIPTION_1 IS 'English Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SYMBOLSHORTDESCRIPTION_2 IS 'Arabic Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.SECTOR IS 'sector code '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.CURRENCY IS 'Currency code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.LASTUPDATED IS 'Last updated time of the  symbol entry'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.IS_ACTIVE IS 'symbol is enabled or disabled in the system'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.MARKET_CODE IS 'Indicates to which market given symbol belongs'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.PRICE_MODIFICATION_FACTOR IS 'Modification factor for price data (Eg:100)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.DECIMAL_PLACES IS 'Number of decimal places to be shown in clinet'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_SYMBOLMAP.DEC_CORRECTION_FACTOR IS 'Correction factor for price data (Eg:100)'
/
-- End of DDL Script for Table DFN_PRICE.ESP_SYMBOLMAP
