-- Table DFN_PRICE.ESP_TODAYS_SNAPSHOTS

  CREATE TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS 
   (	COMPANYCODE VARCHAR2(15) DEFAULT 'N/A', 
	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	SECTOR VARCHAR2(12) DEFAULT 'UNCLASSIFIED', 
	SYMBOLDESCRIPTION_1 VARCHAR2(255), 
	SYMBOLDESCRIPTION_2 NVARCHAR2(510), 
	SYMBOLSHORTDESCRIPTION_1 VARCHAR2(30), 
	SYMBOLSHORTDESCRIPTION_2 NVARCHAR2(120), 
	SYMBOLSTATUS VARCHAR2(6), 
	ASSETCLASS VARCHAR2(6), 
	CURRENCY VARCHAR2(4), 
	LASTUPDATEDTIME DATE, 
	LASTTRADETIME DATE, 
	TRADETICK VARCHAR2(1), 
	ASKTICK VARCHAR2(1), 
	BIDTICK VARCHAR2(1), 
	BESTASKPRICE NUMBER(21,6), 
	BESTASKQUANTITY NUMBER(26,0), 
	BESTBIDPRICE NUMBER(21,6), 
	BESTBIDQUANTITY NUMBER(26,0), 
	LASTTRADEPRICE NUMBER(21,6), 
	LASTTRADEQUANTITY NUMBER(20,0), 
	HIGH NUMBER(21,6), 
	LOW NUMBER(21,6), 
	CHANGE NUMBER(21,6), 
	VOLUME NUMBER(26,0), 
	TURNOVER NUMBER(21,6), 
	PERCENTCHANGED NUMBER(21,6), 
	PREVIOUSCLOSED NUMBER(21,6), 
	TODAYSOPEN NUMBER(21,6), 
	UPDATED CHAR(1), 
	NOOFTRADES NUMBER(18,0), 
	NOOFBIDS NUMBER(18,0), 
	NOOFASKS NUMBER(18,0), 
	VWAP NUMBER(21,6), 
	MINPRICE NUMBER(21,6), 
	MAXPRICE NUMBER(21,6), 
	HIGHPRICEOF52WEEKS NUMBER(21,6), 
	HIGHPRICEOF52WEEKSDATE DATE, 
	LOWPRICEOF52WEEKS NUMBER(21,6), 
	LOWPRICEOF52WEEKSDATE DATE, 
	IS52WEEKSCONSISTSOFLASTTRADE NUMBER(1,0), 
	BEGININGOFYEAR NUMBER(21,6), 
	LASTSEQUENCENO NUMBER(18,0), 
	PER NUMBER(21,6), 
	PBR NUMBER(21,6), 
	MARKETCAP NUMBER(26,6), 
	YIELD NUMBER(21,6), 
	TOTALBIDQTY NUMBER(18,0), 
	TOTALASKQTY NUMBER(18,0), 
	HIGHASK NUMBER(21,6), 
	LOWBID NUMBER(21,6), 
	LASTASKPRICE NUMBER(21,6), 
	LASTBIDPRICE NUMBER(21,6), 
	BIDASKRATIO NUMBER(21,6), 
	SIMPLEAVGASK NUMBER(21,6), 
	WEIGHTEDAVGASK NUMBER(21,6), 
	SIMPLEAVGBID NUMBER(21,6), 
	WEIGHTEDAVGBID NUMBER(21,6), 
	AVGVOLUME NUMBER(20,0), 
	ACRONYM_1 VARCHAR2(20), 
	ACRONYM_2 NVARCHAR2(80), 
	LISTED_SHARES NUMBER(18,3), 
	PAID_SHARES NUMBER(18,3), 
	FACE_VALUE NUMBER(18,3), 
	COUPON_VALUE VARCHAR2(25), 
	COUPON_DATE DATE, 
	NET_PROFIT NUMBER(18,3), 
	NET_PROFIT_DATE DATE, 
	EPS NUMBER(18,3), 
	LASTTRADEDDATE DATE, 
	IS_ACTIVE NUMBER(1,0), 
	TODAYSCLOSED NUMBER(21,6), 
	LASTTRADEDPRICE NUMBER(18,3), 
	CREATED_DATE DATE, 
	REF_PRICE NUMBER(21,6), 
	STRIKEPRICE NUMBER(21,6), 
	OPENINTEREST NUMBER(21,6), 
	EXPIRYDATE VARCHAR2(10), 
	OPTIONTYPE NUMBER(18,0), 
	INSTRUMENTTYPE NUMBER(18,0), 
	EQUITYSYMBOL VARCHAR2(15), 
	BENCHMARK VARCHAR2(100), 
	PERFORMANCE_YTD NUMBER(18,0), 
	PERFORMANCE_12M NUMBER(18,0), 
	PERFORMANCE_3Y NUMBER(18,0), 
	PERFORMANCE_5Y NUMBER(18,0), 
	MANAGEMENT_FEE NUMBER(18,0), 
	DEALING_DEADLINE VARCHAR2(50), 
	NO_OF_SHARES_FOR_FOREIGNERS NUMBER(26,0), 
	CASHINNOOFORDERS NUMBER(18,0), 
	CASHINTURNOVER NUMBER(21,6), 
	CASHINVOLUME NUMBER(26,0), 
	CASHOUTNOOFORDERS NUMBER(18,0), 
	CASHOUTTURNOVER NUMBER(21,6), 
	CASHOUTVOLUME NUMBER(26,0), 
	CHANGE_IN_OPENINTEREST NUMBER(9,0), 
	SETTLMENT_PRICE NUMBER(9,2), 
	ISSUE_CAPITAL NUMBER(12,0), 
	TICK_SIZE NUMBER(6,0), 
	INTRINSIC_VALUE NUMBER(21,6), 
	FLOAT_SHARES NUMBER(20,0), 
	SETTLE_TYPE VARCHAR2(50), 
	TWAP NUMBER(21,6) DEFAULT 0, 
	CLOSING_VWAP NUMBER(21,6) DEFAULT 0, 
	LOOSING_CATEGORY NUMBER(10,0), 
	NOMINAL_VALUE NUMBER(18,6), 
	SHARIAH_STATUS NUMBER(10,0), 
	TOPRICE NUMBER(21,6), 
	TOVOLUME NUMBER(21,0), 
	TCPRICE NUMBER(21,6), 
	TCVOLUME NUMBER(21,0), 
	TWAP_PRM NUMBER(26,6) DEFAULT 0, 
	AVG_TRD_PRC_PRM NUMBER(26,6) DEFAULT 0, 
	MARKET_CAPITAL NUMBER(26,6) DEFAULT 0, 
	SHARE_CAPITAL NUMBER(26,6) DEFAULT 0, 
	DAY_COUNT_METHOD NUMBER(10,0) DEFAULT 0, 
	CALCULATED_VWAP NUMBER(26,6), 
	MONTHLY_HIGH NUMBER(21,6) DEFAULT 0, 
	MONTHLY_LOW NUMBER(21,6) DEFAULT 0, 
	YEARLY_HIGH NUMBER(21,6) DEFAULT 0, 
	YEARLY_LOW NUMBER(21,6) DEFAULT 0
   ) 
/

-- Constraints for  DFN_PRICE.ESP_TODAYS_SNAPSHOTS


  ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS ADD CONSTRAINT PK_ESP_TODAYS_SNAPSHOTS PRIMARY KEY (EXCHANGECODE, SYMBOL)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS MODIFY (LASTTRADEDDATE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS MODIFY (LASTTRADEDPRICE NOT NULL ENABLE)
/



-- Comments for  DFN_PRICE.ESP_TODAYS_SNAPSHOTS

   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.COMPANYCODE IS 'Company code for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.EXCHANGECODE IS 'Mubasher Driven Exchange long code ()'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOL IS 'Symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SECTOR IS 'sector code '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOLDESCRIPTION_1 IS 'English Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOLDESCRIPTION_2 IS 'Arabic Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOLSHORTDESCRIPTION_1 IS 'English Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOLSHORTDESCRIPTION_2 IS 'Arabic Short Description'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.SYMBOLSTATUS IS 'Symbolstaus ( Active, Suspended etcâ€¦)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CURRENCY IS 'Currency'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTUPDATEDTIME IS 'Last updated time'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTTRADETIME IS 'Last trade time of the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TRADETICK IS 'Trade tick ( Eg: N,U,D)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.ASKTICK IS 'Ask price tick'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BIDTICK IS 'Bid Price tick'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BESTASKPRICE IS 'Best ask price'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BESTASKQUANTITY IS 'Best ask quantity'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BESTBIDPRICE IS 'Best bid price'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BESTBIDQUANTITY IS 'best bid quantiy'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTTRADEPRICE IS 'Last trade price'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTTRADEQUANTITY IS 'Last trade quantiy'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.HIGH IS 'highest value of the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LOW IS 'lowest  values of the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CHANGE IS 'Change value of the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.VOLUME IS 'Total quantity '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TURNOVER IS 'Total traded value for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.PERCENTCHANGED IS 'precentage change for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.PREVIOUSCLOSED IS 'Previous closed value of the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TODAYSOPEN IS 'Open value of the symbol for the current day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.NOOFTRADES IS 'Total number of trades for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.NOOFBIDS IS 'Total number of bids for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.NOOFASKS IS 'Total number of asks for the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.VWAP IS 'Volume Weighted Avarge price for the symbol ( Trunover / Volume )'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.MINPRICE IS 'Minimum price for the stock for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.MAXPRICE IS 'Maximum price for the stock for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.HIGHPRICEOF52WEEKS IS 'Highest price value of past 52 weeks'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.HIGHPRICEOF52WEEKSDATE IS 'Date of Highest price value for past 52 weeks'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LOWPRICEOF52WEEKS IS 'Lowest price value of past 52 weeks'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LOWPRICEOF52WEEKSDATE IS 'Date of Lowest price value for past 52 weeks'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.PER IS 'price-to-earnings ratio'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.PBR IS 'price-to-book ratio'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TOTALBIDQTY IS 'Total bids quantity for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TOTALASKQTY IS 'Total ask quantity for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.HIGHASK IS 'Highest Ask price for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LOWBID IS 'Lowest Ask price for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTASKPRICE IS 'Last ask price for day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTBIDPRICE IS 'last bid price for day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.BIDASKRATIO IS 'Bid to ask ratio '
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.AVGVOLUME IS 'Total traded volumn / Total trades'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.EPS IS 'Earnings per share'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTTRADEDDATE IS 'Date where last trade happened before the current date'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.IS_ACTIVE IS 'symbol is enabled or disabled in the system'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.TODAYSCLOSED IS 'Close price for the day'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LASTTRADEDPRICE IS 'Price where last trade happened before the current date'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.INSTRUMENTTYPE IS 'Indicated the type of the symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHINNOOFORDERS IS 'Number of Cash in orders'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHINTURNOVER IS 'Total trunover for the cash In order'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHINVOLUME IS 'Total volumn of the cash in order'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHOUTNOOFORDERS IS 'Number of Cash out orders'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHOUTTURNOVER IS 'Total trunover for the cash out order'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.CASHOUTVOLUME IS 'Total volumn of the cash out order'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_TODAYS_SNAPSHOTS.LOOSING_CATEGORY IS '0-Normal, 1 - 50%-75%,  2 - 75%-100%, 3 - above 100%'
/
-- End of DDL Script for Table DFN_PRICE.ESP_TODAYS_SNAPSHOTS

ALTER TABLE dfn_price.esp_todays_snapshots
 ADD (
  static_min NUMBER (21, 5),
  static_max NUMBER (21, 5)
 )
/

ALTER TABLE DFN_PRICE.ESP_TODAYS_SNAPSHOTS 
 ADD (
  SETTLEMENT_PRICE NUMBER (26, 6)
 )
/
