-- Table DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS

  CREATE TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS 
   (	EXCHANGE VARCHAR2(8), 
	LANGUAGE CHAR(2), 
	DESCRIPTION NVARCHAR2(100), 
	SHORT_DESCRIPTION NVARCHAR2(100)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS


  ALTER TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS ADD CONSTRAINT PK_ESP_EXCHANGE_DESCRIPTIONS PRIMARY KEY (EXCHANGE, LANGUAGE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS MODIFY (EXCHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS MODIFY (LANGUAGE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS
