-- Table DFN_PRICE.ESP_MARKETDEPTH

  CREATE TABLE DFN_PRICE.ESP_MARKETDEPTH 
   (	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	MBO_BID1 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBO_BID2 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBO_BID3 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY3 NUMBER(18,0) DEFAULT 0, 
	MBO_BID4 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBO_BID5 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBO_BID6 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBO_BID7 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBO_BID8 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBO_BID9 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBO_BID10 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY10 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK1 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK2 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK3 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY3 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK4 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK5 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK6 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK7 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK8 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK9 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK10 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY10 NUMBER(18,0) DEFAULT 0, 
	MBP_BID1 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS1 NUMBER(5,0) DEFAULT 0, 
	MBP_BID2 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS2 NUMBER(5,0) DEFAULT 0, 
	MBP_BID3 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY3 NUMBER(10,0) DEFAULT 0, 
	MBP_BID_SPLITS3 NUMBER(5,0) DEFAULT 0, 
	MBP_BID4 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS4 NUMBER(5,0) DEFAULT 0, 
	MBP_BID5 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS5 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK1 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS1 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK2 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS2 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK3 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY3 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS3 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK4 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS4 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK5 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS5 NUMBER(5,0) DEFAULT 0, 
	MBPS_BID1 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID2 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID3 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY3 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID4 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID5 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID6 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID7 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID8 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID9 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBPS_BID10 NUMBER(18,3) DEFAULT 0, 
	MBPS_BID_QTY10 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK1 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY1 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK2 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY2 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK3 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY3 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK4 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY4 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK5 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY5 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK6 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK7 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK8 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK9 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBPS_ASK10 NUMBER(18,3) DEFAULT 0, 
	MBPS_ASK_QTY10 NUMBER(18,0) DEFAULT 0, 
	LAST_UPDATED DATE DEFAULT SYSDATE, 
	MBP_BID6 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS6 NUMBER(5,0) DEFAULT 0, 
	MBP_BID7 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS7 NUMBER(5,0) DEFAULT 0, 
	MBP_BID8 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS8 NUMBER(5,0) DEFAULT 0, 
	MBP_BID9 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS9 NUMBER(5,0) DEFAULT 0, 
	MBP_BID10 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY10 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS10 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK6 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY6 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS6 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK7 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY7 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS7 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK8 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY8 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS8 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK9 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY9 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS9 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK10 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY10 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS10 NUMBER(5,0) DEFAULT 0, 
	INSTRUMENT_TYPE NUMBER(10,0) DEFAULT (0), 
	MBO_BID11 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY11 NUMBER(18,0) DEFAULT 0, 
	MBO_BID12 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY12 NUMBER(18,0) DEFAULT 0, 
	MBO_BID13 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY13 NUMBER(18,0) DEFAULT 0, 
	MBO_BID14 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY14 NUMBER(18,0) DEFAULT 0, 
	MBO_BID15 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY15 NUMBER(18,0) DEFAULT 0, 
	MBO_BID16 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY16 NUMBER(18,0) DEFAULT 0, 
	MBO_BID17 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY17 NUMBER(18,0) DEFAULT 0, 
	MBO_BID18 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY18 NUMBER(18,0) DEFAULT 0, 
	MBO_BID19 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY19 NUMBER(18,0) DEFAULT 0, 
	MBO_BID20 NUMBER(18,3) DEFAULT 0, 
	MBO_BID_QTY20 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK11 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY11 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK12 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY12 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK13 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY13 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK14 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY14 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK15 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY15 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK16 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY16 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK17 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY17 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK18 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY18 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK19 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY19 NUMBER(18,0) DEFAULT 0, 
	MBO_ASK20 NUMBER(18,3) DEFAULT 0, 
	MBO_ASK_QTY20 NUMBER(18,0) DEFAULT 0, 
	MBP_BID11 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY11 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS11 NUMBER(5,0) DEFAULT 0, 
	MBP_BID12 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY12 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS12 NUMBER(5,0) DEFAULT 0, 
	MBP_BID13 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY13 NUMBER(10,0) DEFAULT 0, 
	MBP_BID_SPLITS13 NUMBER(5,0) DEFAULT 0, 
	MBP_BID14 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY14 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS14 NUMBER(5,0) DEFAULT 0, 
	MBP_BID15 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY15 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS15 NUMBER(5,0) DEFAULT 0, 
	MBP_BID16 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY16 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS16 NUMBER(5,0) DEFAULT 0, 
	MBP_BID17 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY17 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS17 NUMBER(5,0) DEFAULT 0, 
	MBP_BID18 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY18 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS18 NUMBER(5,0) DEFAULT 0, 
	MBP_BID19 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY19 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS19 NUMBER(5,0) DEFAULT 0, 
	MBP_BID20 NUMBER(18,3) DEFAULT 0, 
	MBP_BID_QTY20 NUMBER(18,0) DEFAULT 0, 
	MBP_BID_SPLITS20 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK11 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY11 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS11 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK12 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY12 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS12 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK13 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY13 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS13 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK14 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY14 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS14 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK15 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY15 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS15 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK16 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY16 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS16 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK17 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY17 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS17 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK18 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY18 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS18 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK19 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY19 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS19 NUMBER(5,0) DEFAULT 0, 
	MBP_ASK20 NUMBER(18,3) DEFAULT 0, 
	MBP_ASK_QTY20 NUMBER(18,0) DEFAULT 0, 
	MBP_ASK_SPLITS20 NUMBER(5,0) DEFAULT 0
   ) 
/

-- Constraints for  DFN_PRICE.ESP_MARKETDEPTH


  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH ADD CONSTRAINT PK_ESP_MARKETDEPTH PRIMARY KEY (EXCHANGECODE, SYMBOL)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_BID_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY1 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY2 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY3 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY4 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY5 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBPS_ASK_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (LAST_UPDATED NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS6 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS7 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS8 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS9 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS10 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_BID_QTY20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBO_ASK_QTY20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_QTY20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_BID_SPLITS20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS11 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS12 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS13 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS14 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS15 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS16 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS17 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS18 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS19 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_QTY20 NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_MARKETDEPTH MODIFY (MBP_ASK_SPLITS20 NOT NULL ENABLE)
/
-- End of DDL Script for Table DFN_PRICE.ESP_MARKETDEPTH


-- Comments for  DFN_PRICE.ESP_MARKETDEPTH

   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.EXCHANGECODE IS 'Mubasher Driven Exchnage short code'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.SYMBOL IS 'Symbol'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID1 IS 'Market Depth by Order Value ( Order Book Bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY1 IS 'Market Depth by Order Qnty ( Order Book Bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID2 IS 'Market Depth by Order Value ( Order Book Bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY2 IS 'Market Depth by Order Qnty ( Order Book Bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID3 IS 'Market Depth by Order Value ( Order Book Bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY3 IS 'Market Depth by Order Qnty ( Order Book Bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID4 IS 'Market Depth by Order Value ( Order Book Bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY4 IS 'Market Depth by Order Qnty ( Order Book Bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID5 IS 'Market Depth by Order Value ( Order Book Bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY5 IS 'Market Depth by Order Qnty ( Order Book Bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID6 IS 'Market Depth by Order Value ( Order Book Bid Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY6 IS 'Market Depth by Order Qnty ( Order Book Bid Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID7 IS 'Market Depth by Order Value ( Order Book Bid Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY7 IS 'Market Depth by Order Qnty ( Order Book Bid Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID8 IS 'Market Depth by Order Value ( Order Book Bid Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY8 IS 'Market Depth by Order Qnty ( Order Book Bid Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID9 IS 'Market Depth by Order Value ( Order Book Bid Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY9 IS 'Market Depth by Order Qnty ( Order Book Bid Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID10 IS 'Market Depth by Order Value ( Order Book Bid Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_BID_QTY10 IS 'Market Depth by Order Qnty ( Order Book Bid Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK1 IS 'Market Depth by Order Value ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY1 IS 'Market Depth by Order Qnty ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK2 IS 'Market Depth by Order Value ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY2 IS 'Market Depth by Order Qnty ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK3 IS 'Market Depth by Order Value ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY3 IS 'Market Depth by Order Qnty ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK4 IS 'Market Depth by Order Value ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY4 IS 'Market Depth by Order Qnty ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK5 IS 'Market Depth by Order Value ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY5 IS 'Market Depth by Order Qnty ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK6 IS 'Market Depth by Order Value ( Order Book ask Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY6 IS 'Market Depth by Order Qnty ( Order Book ask Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK7 IS 'Market Depth by Order Value ( Order Book ask Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY7 IS 'Market Depth by Order Qnty ( Order Book ask Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK8 IS 'Market Depth by Order Value ( Order Book ask Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY8 IS 'Market Depth by Order Qnty ( Order Book ask Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK9 IS 'Market Depth by Order Value ( Order Book ask Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY9 IS 'Market Depth by Order Qnty ( Order Book ask Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK10 IS 'Market Depth by Order Value ( Order Book ask Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBO_ASK_QTY10 IS 'Market Depth by Order Qnty ( Order Book ask Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID1 IS 'Market Depth by Price Value ( Order Book bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_QTY1 IS 'Market Depth by Price Qnty ( Order Book bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_SPLITS1 IS 'Market Depth by Price Splits ( Order Book bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID2 IS 'Market Depth by Price Value ( Order Book bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_QTY2 IS 'Market Depth by Price Qnty ( Order Book bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_SPLITS2 IS 'Market Depth by Price Splits ( Order Book bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID3 IS 'Market Depth by Price Value ( Order Book bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_QTY3 IS 'Market Depth by Price Qnty ( Order Book bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_SPLITS3 IS 'Market Depth by Price Splits ( Order Book bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID4 IS 'Market Depth by Price Value ( Order Book bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_QTY4 IS 'Market Depth by Price Qnty ( Order Book bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_SPLITS4 IS 'Market Depth by Price Splits ( Order Book bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID5 IS 'Market Depth by Price Value ( Order Book bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_QTY5 IS 'Market Depth by Price Qnty ( Order Book bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_BID_SPLITS5 IS 'Market Depth by Price Splits ( Order Book bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK1 IS 'Market Depth by Price Value ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_QTY1 IS 'Market Depth by Price Qnty ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_SPLITS1 IS 'Market Depth by Price Splits ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK2 IS 'Market Depth by Price Value ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_QTY2 IS 'Market Depth by Price Qnty ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_SPLITS2 IS 'Market Depth by Price Splits ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK3 IS 'Market Depth by Price Value ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_QTY3 IS 'Market Depth by Price Qnty ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_SPLITS3 IS 'Market Depth by Price Splits ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK4 IS 'Market Depth by Price Value ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_QTY4 IS 'Market Depth by Price Qnty ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_SPLITS4 IS 'Market Depth by Price Splits ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK5 IS 'Market Depth by Price Value ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_QTY5 IS 'Market Depth by Price Qnty ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBP_ASK_SPLITS5 IS 'Market Depth by Price Splits ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID1 IS 'Market Depth Special Value ( Order Book bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY1 IS 'Market Depth Special Qnty ( Order Book bid Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID2 IS 'Market Depth Special Value ( Order Book bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY2 IS 'Market Depth Special Qnty ( Order Book bid Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID3 IS 'Market Depth Special Value ( Order Book bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY3 IS 'Market Depth Special Qnty ( Order Book bid Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID4 IS 'Market Depth Special Value ( Order Book bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY4 IS 'Market Depth Special Qnty ( Order Book bid Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID5 IS 'Market Depth Special Value ( Order Book bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY5 IS 'Market Depth Special Qnty ( Order Book bid Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID6 IS 'Market Depth Special Value ( Order Book bid Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY6 IS 'Market Depth Special Qnty ( Order Book bid Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID7 IS 'Market Depth Special Value ( Order Book bid Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY7 IS 'Market Depth Special Qnty ( Order Book bid Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID8 IS 'Market Depth Special Value ( Order Book bid Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY8 IS 'Market Depth Special Qnty ( Order Book bid Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID9 IS 'Market Depth Special Value ( Order Book bid Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY9 IS 'Market Depth Special Qnty ( Order Book bid Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID10 IS 'Market Depth Special Value ( Order Book bid Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_BID_QTY10 IS 'Market Depth Special Qnty ( Order Book bid Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK1 IS 'Market Depth Special Value ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY1 IS 'Market Depth Special Qnty ( Order Book ask Value 1)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK2 IS 'Market Depth Special Value ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY2 IS 'Market Depth Special Qnty ( Order Book ask Value 2)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK3 IS 'Market Depth Special Value ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY3 IS 'Market Depth Special Qnty ( Order Book ask Value 3)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK4 IS 'Market Depth Special Value ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY4 IS 'Market Depth Special Qnty ( Order Book ask Value 4)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK5 IS 'Market Depth Special Value ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY5 IS 'Market Depth Special Qnty ( Order Book ask Value 5)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK6 IS 'Market Depth Special Value ( Order Book ask Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY6 IS 'Market Depth Special Qnty ( Order Book ask Value 6)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK7 IS 'Market Depth Special Value ( Order Book ask Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY7 IS 'Market Depth Special Qnty ( Order Book ask Value 7)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK8 IS 'Market Depth Special Value ( Order Book ask Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY8 IS 'Market Depth Special Qnty ( Order Book ask Value 8)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK9 IS 'Market Depth Special Value ( Order Book ask Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY9 IS 'Market Depth Special Qnty ( Order Book ask Value 9)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK10 IS 'Market Depth Special Value ( Order Book ask Value 10)'
/
   COMMENT ON COLUMN DFN_PRICE.ESP_MARKETDEPTH.MBPS_ASK_QTY10 IS 'Market Depth Special Qnty ( Order Book ask Value 10)'
/
-- End of DDL Script for Table DFN_PRICE.ESP_MARKETDEPTH
