-- Table DFN_PRICE.EOD_SNAPSHOT

  CREATE TABLE DFN_PRICE.EOD_SNAPSHOT 
   (	EXID VARCHAR2(4), 
	SYMBOL VARCHAR2(60), 
	EX_NAME VARCHAR2(256), 
	PRE_IND VARCHAR2(1), 
	COMPANY_NAME VARCHAR2(160), 
	LAST_PRICE NUMBER, 
	OPEN_PRICE NUMBER, 
	HIGH_PRICE NUMBER, 
	LOW_PRICE NUMBER, 
	CUMM_VOLUME NUMBER, 
	YESTERDAY_CLOSE NUMBER, 
	SETTLE NUMBER, 
	YESTERDAY_VOLUME NUMBER, 
	OPEN_INT NUMBER, 
	STRIKE_PRICE NUMBER, 
	STRIKE_PRICE_DIV VARCHAR2(25), 
	ACTIVITY_DATE DATE, 
	CURRENCY_CODE VARCHAR2(30), 
	BID_PRICE NUMBER, 
	BID_HIGH_PRICE NUMBER, 
	BID_LOW_PRICE NUMBER, 
	ASK_PRICE NUMBER, 
	TRADE_DATE DATE, 
	EXP_DATE DATE, 
	PREV_TRADE_DATE DATE, 
	LOCAL_CODE VARCHAR2(100), 
	TRADING_CODE VARCHAR2(50), 
	SEDOL VARCHAR2(30), 
	ISIN VARCHAR2(12), 
	DESCRIPTION VARCHAR2(160), 
	UNDERLYING_EXCHID VARCHAR2(100), 
	UNDERLYING_SYMBOL VARCHAR2(200), 
	LOWSPEEDSYMBOL VARCHAR2(150), 
	INDEX_MEMBERSHIP VARCHAR2(60), 
	STATUS VARCHAR2(10), 
	PRIMARY_EXCH VARCHAR2(35), 
	SUBMARKET VARCHAR2(30), 
	LOCALINSTTYPE VARCHAR2(100), 
	LOCALINDSECTOR VARCHAR2(100), 
	CONTRACT_UNITS NUMBER, 
	CONTRACT_SIZE NUMBER, 
	SUBMARKETCODE VARCHAR2(20), 
	SUBMARKETDESC VARCHAR2(100), 
	CONTRACTDESC VARCHAR2(30), 
	INSTRUMENTDESC VARCHAR2(100), 
	MICCODE VARCHAR2(40), 
	TRADE_EX_NAME VARCHAR2(256)
   ) 
/

-- Constraints for  DFN_PRICE.EOD_SNAPSHOT


  ALTER TABLE DFN_PRICE.EOD_SNAPSHOT MODIFY (EXID NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.EOD_SNAPSHOT MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.EOD_SNAPSHOT ADD PRIMARY KEY (EXID, SYMBOL)
  USING INDEX  ENABLE
/

-- Indexes for  DFN_PRICE.EOD_SNAPSHOT


  CREATE INDEX DFN_PRICE.EOD_SNAPSHOT_ISIN_IND ON DFN_PRICE.EOD_SNAPSHOT (ISIN) 
  
/


-- End of DDL Script for Table DFN_PRICE.EOD_SNAPSHOT
