-- Table DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS

  CREATE TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS 
   (	EXCHANGE VARCHAR2(8), 
	SYMBOL VARCHAR2(25), 
	INSTRUMENTTYPE NUMBER(10,0), 
	LANGUAGE CHAR(2), 
	SYMBOLDESCRIPTION NVARCHAR2(510), 
	SYMBOLSHORTDESCRIPTION NVARCHAR2(120), 
	DISPLAYSYMBOL VARCHAR2(25), 
	SYMBOLDESCRIPTION_ASCII CLOB, 
	DISPLAYSYMBOLDESCRIPTION NVARCHAR2(510), 
	ISDISPLAYSYMBOL NUMBER(1,0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS


  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS ADD CONSTRAINT PK_ESP_SYMBOLMAP_DESCRIPTIONS PRIMARY KEY (EXCHANGE, SYMBOL, INSTRUMENTTYPE, LANGUAGE)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS MODIFY (EXCHANGE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS MODIFY (INSTRUMENTTYPE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS MODIFY (LANGUAGE NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_SYMBOLMAP_DESCRIPTIONS
