-- Table DFN_PRICE.ESP_INTRADAY_OHLC

  CREATE TABLE DFN_PRICE.ESP_INTRADAY_OHLC 
   (	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(30), 
	TRADE_MIN DATE, 
	OPEN NUMBER(18,3), 
	HIGH NUMBER(18,3), 
	LOW NUMBER(18,3), 
	CLOSE NUMBER(18,3), 
	MIN_TIME DATE, 
	MAX_TIME DATE, 
	VOLUME NUMBER(18,3), 
	TURNOVER NUMBER(21,3), 
	VWAP NUMBER(21,3), 
	NOOFTRADES NUMBER(10,0), 
	CASHINTURNOVER NUMBER(21,3), 
	CASHINVOLUME NUMBER(10,0), 
	CASHOUTTURNOVER NUMBER(21,3), 
	CASHOUTVOLUME NUMBER(10,0), 
	CASHINNOOFTRADES NUMBER(21,0), 
	CASHOUTNOOFTRADES NUMBER(21,0), 
	INSTRUMENT_TYPE NUMBER(10,0) DEFAULT (0)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_INTRADAY_OHLC


  ALTER TABLE DFN_PRICE.ESP_INTRADAY_OHLC ADD CONSTRAINT PK_ESP_INTRADAY_OHLC PRIMARY KEY (EXCHANGECODE, SYMBOL, TRADE_MIN)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_OHLC MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_OHLC MODIFY (SYMBOL NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_INTRADAY_OHLC MODIFY (TRADE_MIN NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_INTRADAY_OHLC
