-- Table DFN_PRICE.ESP_INSTRUMENT_TYPES

  CREATE TABLE DFN_PRICE.ESP_INSTRUMENT_TYPES 
   (	ID NUMBER(10,0), 
	DESCRIPTION_1 VARCHAR2(50), 
	DESCRIPTION_2 NVARCHAR2(50)
   ) 
/






-- End of DDL Script for Table DFN_PRICE.ESP_INSTRUMENT_TYPES
