-- Table DFN_PRICE.ESP_PERIODIC_INDICATORS

  CREATE TABLE DFN_PRICE.ESP_PERIODIC_INDICATORS 
   (	EXCHANGECODE VARCHAR2(8), 
	SYMBOL VARCHAR2(50), 
	LASTUPDATEDTIME DATE DEFAULT SYSDATE, 
	ISENDOFDAY NUMBER(1,0) DEFAULT 0, 
	PERIODSTART DATE, 
	PERIODSTOP DATE, 
	TWASPREAD NUMBER(13,6) DEFAULT 0, 
	RTWASPREAD NUMBER(13,6) DEFAULT 0, 
	TWABESTBID NUMBER(13,6) DEFAULT 0, 
	TWABESTASK NUMBER(13,6) DEFAULT 0, 
	TVWAQUOTATION NUMBER(13,6) DEFAULT 0, 
	TWBESTASKVOLUME NUMBER(13,6) DEFAULT 0, 
	TWBESTASKVALUE NUMBER(13,6) DEFAULT 0, 
	TWNOBESTASK NUMBER(13,6) DEFAULT 0, 
	TWVOLUMEASKSIDE NUMBER(13,6) DEFAULT 0, 
	TWVALUEASKSIDE NUMBER(13,6) DEFAULT 0, 
	TWNOASKSIDE NUMBER(13,6) DEFAULT 0, 
	TWBESTBIDVOLUME NUMBER(13,6) DEFAULT 0, 
	TWBESTBIDVALUE NUMBER(13,6) DEFAULT 0, 
	TWNOBESTBID NUMBER(13,6) DEFAULT 0, 
	TWVOLUMEBIDSIDE NUMBER(13,6) DEFAULT 0, 
	TWVALUEBIDSIDE NUMBER(13,6) DEFAULT 0, 
	TWNOBIDSIDE NUMBER(13,6) DEFAULT 0, 
	TWMIDPOINTVOLUME NUMBER(13,6) DEFAULT 0, 
	TWMIDPOINTVALUE NUMBER(13,6) DEFAULT 0, 
	TWNOMIDPOINT NUMBER(13,6) DEFAULT 0, 
	TWTVOLUMEMIDPOINT NUMBER(13,6) DEFAULT 0, 
	TWTVALUEMIDPOINT NUMBER(13,6) DEFAULT 0, 
	TWTOMIDPOINT NUMBER(13,6) DEFAULT 0, 
	TOTALORDERCOVERAGE NUMBER(13,6) DEFAULT 0, 
	BIDORDERCOVERAGE NUMBER(13,6) DEFAULT 0, 
	ASKORDERCOVERAGE NUMBER(13,6) DEFAULT 0, 
	BEVWAPBIDSIDE NUMBER(13,6) DEFAULT 0, 
	BEVWAPASKSIDE NUMBER(13,6) DEFAULT 0, 
	TWTVOLUMEBIDSIDE NUMBER(13,6) DEFAULT 0, 
	TWTVOLUMEASKSIDE NUMBER(13,6) DEFAULT 0, 
	TWBAINDICATORBEST NUMBER(13,6) DEFAULT 0, 
	TWBAINDICATORALL NUMBER(13,6) DEFAULT 0, 
	TWCINDICATORBIDSIDE NUMBER(13,6) DEFAULT 0, 
	TWCINDICATORASKSIDE NUMBER(13,6) DEFAULT 0, 
	LOCALRTCLASSES VARCHAR2(200), 
	LOCALRTCOSTS VARCHAR2(200), 
	LOCALRTCOVERAGES VARCHAR2(200), 
	REFERANCERTCLASSES VARCHAR2(200), 
	REFERANCERTCOSTS VARCHAR2(200), 
	REFERANCERTCOVERAGES VARCHAR2(200)
   ) 
/

-- Constraints for  DFN_PRICE.ESP_PERIODIC_INDICATORS


  ALTER TABLE DFN_PRICE.ESP_PERIODIC_INDICATORS ADD CONSTRAINT PK_ESP_PERIODIC_INDICATOR PRIMARY KEY (EXCHANGECODE, SYMBOL)
  USING INDEX  ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_PERIODIC_INDICATORS MODIFY (EXCHANGECODE NOT NULL ENABLE)
/

  ALTER TABLE DFN_PRICE.ESP_PERIODIC_INDICATORS MODIFY (SYMBOL NOT NULL ENABLE)
/




-- End of DDL Script for Table DFN_PRICE.ESP_PERIODIC_INDICATORS
