SPOOL log.run.dfn_mig.migration_scripts REPLACE

WHENEVER SQLERROR EXIT
SET ECHO ON
SET DEFINE OFF
SET SQLBLANKLINES ON

@@00_x_dfn_ntp.h00_dates.data.sql
COMMIT
/
@@01_i_dfn_ntp.m12_employee_department.data.sql
COMMIT
/
@@02_i_dfn_ntp.u17_employee.data.sql
COMMIT
/
@@03_i_dfn_ntp.m04_currency_rate.data.sql
COMMIT
/
@@04_i_dfn_ntp.m07_location.data.sql
COMMIT
/
@@05_p_dfn_ntp.m01_exchanges.data.sql
COMMIT
/
@@06_i_dfn_ntp.m08_trading_group.data.sql
COMMIT
/
@@07_il_dfn_ntp.m09_companies.data.sql
COMMIT
/
@@08_i_dfn_ntp.m10_relationship_manager.data.sql
COMMIT
/
@@10_il_dfn_ntp.m14_issue_location.data.sql
COMMIT
/
@@15_p_dfn_ntp.m39_price_qty_factors.data.sql
COMMIT
/
@@21_i_dfn_ntp.m16_bank.data.sql
COMMIT
/
@@22_i_dfn_ntp.m17_bank_branches.data.sql
COMMIT
/
@@23_p_dfn_ntp.m29_markets.data.sql
COMMIT
/
@@24_p_dfn_ntp.m63_sectors.data.sql
COMMIT
/
@@25_p_dfn_ntp.m20_symbol.data.sql
COMMIT
/
@@26_p_dfn_ntp.m20_symbol_extended.data.sql
COMMIT
/
@@27_il_dfn_ntp.m21_introducing_broker.data.sql
COMMIT
/
@@28_i_dfn_ntp.m22_commission_group.data.sql
COMMIT
/
@@29_i_dfn_ntp.m23_commission_slabs.data.sql
COMMIT
/
@@30_i_dfn_ntp.m24_commission_discount_group.data.sql
COMMIT
/
@@41_i_dfn_ntp.m25_commission_discount_slabs.data.sql
COMMIT
/
@@42_p_dfn_ntp.m26_executing_broker.data.sql
COMMIT
/
@@43_p_dfn_ntp.m34_exec_broker_commission.data.sql
COMMIT
/
@@44_il_dfn_ntp.m28_customer_grade_data.data.sql
COMMIT
/
@@45_p_dfn_ntp.m57_exchange_order_types.data.sql
COMMIT
/
@@46_p_dfn_ntp.m58_exchange_tif.data.sql
COMMIT
/
@@47_p_dfn_ntp.m59_exchange_market_status.data.sql
COMMIT
/
@@48_p_dfn_ntp.m30_ex_market_permissions.data.sql
COMMIT
/
@@49_p_dfn_ntp.m32_ex_market_status_tif.data.sql
COMMIT
/
@@50_il_dfn_ntp.m44_institution_entitlements.data.sql
COMMIT
/
--@@61_i_dfn_ntp.m45_permission_groups.data.sql -- SFC Will Configure
--COMMIT
--/
--@@62_i_dfn_ntp.m46_permission_grp_entlements.data.sql -- SFC Will Configure
--COMMIT
--/
--@@63_i_dfn_ntp.m47_permission_grp_users.data.sql -- SFC Will Configure
--COMMIT
--/
@@64_i_dfn_ntp.m50_employee_trd_limits.data.sql
COMMIT
/
@@65_i_dfn_ntp.m51_employee_trading_groups.data.sql
COMMIT
/
@@66_i_dfn_ntp.m60_institute_banks.data.sql
COMMIT
/
@@67_i_dfn_ntp.m62_institute_documents.data.sql
COMMIT
/
@@68_i_dfn_ntp.m52_notification_group.data.sql
COMMIT
/
@@69_i_dfn_ntp.m65_saibor_basis_rates.data.sql
COMMIT
/
@@70_i_dfn_ntp.m67_fix_logins.data.sql
COMMIT
/
@@75_i_dfn_ntp.m75_stock_concentration_group.data.sql
COMMIT
/
@@81_il_dfn_ntp.m68_institute_order_channels.data.sql
COMMIT
/
@@82_i_dfn_ntp.m69_institute_trading_limits.data.sql
COMMIT
/
@@83_p_dfn_ntp.m70_custody_exchanges.data.sql
COMMIT
/
@@84_p_dfn_ntp.m72_exec_broker_cash_account.data.sql
COMMIT
/
@@85_i_dfn_ntp.m74_margin_interest_group.data.sql
COMMIT
/
@@86_i_dfn_ntp.m77_symbol_marginability_grps.data.sql
COMMIT
/
@@87_i_dfn_ntp.m78_symbol_marginability.data.sql
COMMIT
/
@@88_i_dfn_ntp.m79_pending_symbl_mrg_request.data.sql
COMMIT
/
@@89_i_dfn_ntp.m73_margin_products.data.sql
COMMIT
/
@@90_p_dfn_ntp.m87_exec_broker_exchange.data.sql
COMMIT
/
@@95_il_dfn_ntp.m89_customer_category.data.sql
COMMIT
/
@@101_il_dfn_ntp.m105_other_brokerages.data.sql
COMMIT
/
@@102_il_dfn_ntp.m114_company_positions.data.sql
COMMIT
/
@@103_il_dfn_ntp.m110_reasons.data.sql
COMMIT
/
@@104_il_dfn_ntp.m116_hijri_adjustments.data.sql
COMMIT
/
@@105_il_dfn_ntp.m117_charge_groups.data.sql
COMMIT
/
@@106_i_dfn_ntp.m118_charge_fee_structure.data.sql
COMMIT
/
@@107_i_dfn_ntp.m120_sharia_compliant_group.data.sql
COMMIT
/
@@108_i_dfn_ntp.m119_sharia_symbol.data.sql
COMMIT
/
@@109_p_dfn_ntp.m122_exchange_tick_sizes.data.sql
COMMIT
/
@@110_p_dfn_ntp.m125_exchange_instrument_type.data.sql
COMMIT
/
@@115_il_dfn_ntp.m151_trade_confirm_config.data.sql
COMMIT
/
--@@121_p_dfn_ntp.m133_gl_account_types.data.sql -- Not Required. Configuration Data
--COMMIT
--/
--@@122_p_dfn_ntp.m134_gl_account_categories.data.sql -- Not Required. Configuration Data
--COMMIT
--/
--@@123_il_dfn_ntp.m135_gl_accounts.data.sql -- Not Required. Configuration Data
--COMMIT
--/
@@124_i_dfn_ntp.m93_bank_accounts.data.sql
COMMIT
/
@@125_i_dfn_ntp.u01_customer.data.sql
COMMIT
/
@@126_i_dfn_ntp.m109_customer_family_members.data.sql
COMMIT
/
@@127_i_dfn_ntp.u02_customer_contact_info.data.sql
COMMIT
/
@@128_i_dfn_ntp.u48_corp_customer_contact.data.sql
COMMIT
/
@@129_i_dfn_ntp.u05_customer_identification.data.sql
COMMIT
/
@@130_i_dfn_ntp.u03_customer_kyc.data.sql
COMMIT
/
@@141_i_dfn_ntp.u06_cash_account.data.sql
COMMIT
/
@@142_il_dfn_ntp.m131_market_maker_grps.data.sql
COMMIT
/
@@143_i_dfn_ntp.u07_trading_account.data.sql
COMMIT
/
@@144_i_dfn_ntp.u08_customer_beneficiary_acc.data.sql
COMMIT
/
@@145_i_dfn_ntp.u09_customer_login.data.sql
COMMIT
/
@@146_i_dfn_ntp.u46_user_sessions.data.sql
COMMIT
/
@@147_i_dfn_ntp.u30_login_cash_acc.data.sql
COMMIT
/
@@148_i_dfn_ntp.u10_login_trading_acc.data.sql
COMMIT
/
@@149_i_dfn_ntp.m104_cust_notification_schedul.data.sql
COMMIT
/
@@150_i_dfn_ntp.u11_cash_restriction.data.sql
COMMIT
/
@@161_i_dfn_ntp.u12_trading_restriction.data.sql
COMMIT
/
@@162_i_dfn_ntp.u14_trading_symbol_restriction.data.sql
COMMIT
/
@@163_i_dfn_ntp.u16_trading_instrument_restric.data.sql
COMMIT
/
@@164_i_dfn_ntp.u18_trading_channel_restrict.data.sql
COMMIT
/
@@165_i_dfn_ntp.u23_customer_margin_product.data.sql
COMMIT
/
--@@166_i_dfn_ntp.u22_customer_margin_call_log.data.sql -- Not Required. SFC -> u20_cust_margin_calls but All Required Data Not Available
--COMMIT
--/
@@167_i_dfn_ntp.m43_institute_exchanges.data.sql
COMMIT
/
@@168_i_dfn_ntp.u24_holdings.data.sql
COMMIT
/
@@169_i_dfn_ntp.u28_employee_exchanges.data.sql
COMMIT
/
@@170_i_dfn_ntp.u29_emp_notification_groups.data.sql
COMMIT
/
@@181_i_dfn_ntp.u41_notification_configuration.data.sql
COMMIT
/
@@182_i_dfn_ntp.u44_uploaded_documents.data.sql
COMMIT
/
@@183_i_dfn_ntp.u45_uploaded_doc_pages.data.sql
COMMIT
/
@@184_i_dfn_ntp.u47_power_of_attorney.data.sql
COMMIT
/
@@185_i_dfn_ntp.u49_poa_trading_privileges.data.sql
COMMIT
/
@@186_i_dfn_ntp.u55_poa_symbol_restrictions.data.sql
COMMIT
/
--@@187_i_dfn_ntp.u13_ext_custody_portfolios.data.sql -- Not Available
--COMMIT
--/
@@188_i_dfn_ntp.t01_order.data.sql
COMMIT
/
@@189_i_dfn_ntp.t02_transaction_log.data.sql
COMMIT
/
--@@190_i_dfn_ntp.t04_disable_exchange_acc_req.data.sql -- Account Closure Requests Migrated from Same T87 Source Table and Hence Ignored
--COMMIT
--/
@@201_i_dfn_ntp.t05_institute_cash_acc_log.data.sql
COMMIT
/
@@202_i_dfn_ntp.t06_cash_transaction.data.sql
COMMIT
/
@@203_i_dfn_ntp.t08_od_withdraw_limit.data.sql
COMMIT
/
@@204_i_dfn_ntp.t10_cash_block_request.data.sql
COMMIT
/
--@@205_i_dfn_ntp.t11_block_amount_details.data.sql  -- Not Available. All Required Data Not Available
--COMMIT
--/
@@206_i_dfn_ntp.t12_share_transaction.data.sql
COMMIT
/
@@207_i_dfn_ntp.t20_pending_pledg.data.sql
COMMIT
/
@@208_i_dfn_ntp.t21_daily_interest_for_charges.data.sql
COMMIT
/
--@@209_i_dfn_ntp.t22_order_audit.data.sql -- Not Available
--COMMIT
--/
--@@210_i_dfn_ntp.t24_customer_margin_request.data.sql -- Not Available
--COMMIT
--/
@@221_p_dfn_ntp.h26_daily_status.data.sql
COMMIT
/
@@222_i_dfn_ntp.t52_desk_orders.data.sql
COMMIT
/
--@@223_i_dfn_ntp.t53_order_canceled_requests.data.sql -- Not Available
--COMMIT
--/
@@224_i_dfn_ntp.h01_holding_summary.data.sql
COMMIT
/
@@225_i_dfn_ntp.h02_cash_account_summary.data.sql
COMMIT
/
@@226_il_dfn_ntp.h03_currency_rate.data.sql
COMMIT
/
@@227_i_dfn_ntp.h05_institute_trading_limits.data.sql
COMMIT
/
@@228_i_dfn_ntp.h07_user_sessions.data.sql
COMMIT
/
--@@229_i_dfn_ntp.h09_cash_account_update.data.sql -- Not Available
--COMMIT
--/
@@230_i_dfn_ntp.h10_bank_accounts_summary.data.sql
COMMIT
/
@@241_i_dfn_ntp.a06_audit.data.sql
COMMIT
/
@@242_i_dfn_ntp.h24_gl_cash_account_summary.data.sql
COMMIT
/
@@243_i_dfn_ntp.m1001_sukuk_coupon_payment.data.sql
COMMIT
/
--@@245_i_dfn_ntp.a18_user_login_audit.data.sql -- Not Available
--COMMIT
--/
@@246_i_dfn_ntp.m162_incentive_group.data.sql
COMMIT
/
@@247_i_dfn_ntp.m163_incentive_slabs.data.sql
COMMIT
/
@@248_i_dfn_ntp.t13_notifications.data.sql
COMMIT
/
@@249_i_dfn_ntp.t14_notification_data.data.sql
COMMIT
/
@@250_i_dfn_ntp.t18_c_umessage.data.sql
COMMIT
/
@@261_i_dfn_ntp.t19_c_umessage_share_details.data.sql
COMMIT
/
@@262_i_dfn_ntp.m161_price_user_pool.data.sql
COMMIT
/
@@263_i_dfn_ntp.m158_priceuser_agreement.data.sql
COMMIT
/
@@264_il_dfn_ntp.m178_asset_management_company.data.sql
COMMIT
/
@@265_i_dfn_ntp.m132_market_maker_grp_details.data.sql
COMMIT
/
@@266_i_dfn_ntp.t54_slice_orders.data.sql
COMMIT
/
/* Janaka : Will be Handled from ETI Migration
@@267_i_dfn_ntp.m152_products.data.sql
COMMIT
/
@@268_i_dfn_ntp.m153_exchange_subscription_prd.data.sql
COMMIT
/
@@269_i_dfn_ntp.m154_subscription_waiveoff_grp.data.sql
COMMIT
/
@@270_i_dfn_ntp.m155_product_waiveoff_details.data.sql
COMMIT
/
@@281_i_dfn_ntp.m156_exchange_waiveoff_details.data.sql
COMMIT
/
@@282_i_dfn_ntp.t56_product_subscription_data.data.sql
COMMIT
/
@@283_i_dfn_ntp.t57_exchange_subscription_data.data.sql
COMMIT
/
*/
@@284_i_dfn_ntp.m160_offline_symbol_update_log.data.sql
COMMIT
/
@@286_il_dfn_ntp.m176_order_limit_group.data.sql
COMMIT
/
@@287_il_dfn_ntp.m177_cash_transfer_limit_group.data.sql
COMMIT
/
@@288_i_dfn_ntp.m141_cust_corporate_action.data.sql
COMMIT
/
@@289_il_dfn_ntp.m166_custody_charges_group.data.sql
COMMIT
/
@@290_il_dfn_ntp.m167_custody_charges_slab.data.sql
COMMIT
/
@@301_i_dfn_ntp.m170_institute_cash_acc_config.data.sql
COMMIT
/
@@302_i_dfn_ntp.t500_payment_sessions_c.data.sql
COMMIT
/
@@303_i_dfn_ntp.t501_payment_detail_c.data.sql
COMMIT
/
@@304_i_dfn_ntp.t61_bulk_share_transactions.data.sql
COMMIT
/
@@305_i_dfn_ntp.m76_stock_conc_symbol_details.data.sql
COMMIT
/
@@306_i_dfn_ntp.t38_conditional_order.data.sql
COMMIT
/
@@307_i_dfn_ntp.t27_gl_batches.data.sql
COMMIT
/
@@308_i_dfn_ntp.t28_gl_record_wise_entries.data.sql
COMMIT
/
@@309_i_dfn_ntp.t29_gl_column_wise_entries.data.sql
COMMIT
/
@@310_i_dfn_ntp.t41_cust_corp_act_distribution.data.sql
COMMIT
/
@@321_i_dfn_ntp.t42_cust_corp_act_hold_adjust.data.sql
COMMIT
/
@@322_i_dfn_ntp.t43_cust_corp_act_cash_adjust.data.sql
COMMIT
/
@@323_i_dfn_ntp.m18_derivative_spread_matrix.data.sql
COMMIT
/
@@324_i_dfn_ntp.t15_authorization_request.data.sql
COMMIT
/
@@325_i_dfn_ntp.t502_change_account_requests_c.data.sql
COMMIT
/
@@326_i_dfn_ntp.t48_tax_invoices.data.sql
COMMIT
/
@@327_i_dfn_ntp.t49_tax_invoice_details.data.sql
COMMIT
/
@@328_il_dfn_ntp.m181_murabaha_baskets.data.sql
COMMIT
/
@@329_il_dfn_ntp.m182_murabaha_bskt_composition.data.sql
COMMIT
/
@@330_i_dfn_ntp.t70_mark_to_market.data.sql
COMMIT
/
@@341_i_dfn_ntp.t75_murabaha_contracts.data.sql
COMMIT
/
@@342_i_dfn_ntp.h13_interest_indices_history.data.sql
COMMIT
/
@@343_i_dfn_ntp.t67_stock_block_request.data.sql
COMMIT
/
@@344_i_dfn_ntp.t90_murabaha_amortize.data.sql
COMMIT
/
@@345_i_dfn_ntp.u59_trading_acc_fix_logins.data.sql
COMMIT
/
@@995_i_dfn_ntp.a10_entity_status_history.data.sql
COMMIT
/
@@996_il_dfn_ntp.a10_entity_status_history.data.sql
COMMIT
/
@@997_o_dfn_ntp.a10_entity_status_history.data.sql 
COMMIT
/
@@998_x_set_discount_charge_group_mappings.data.sql
COMMIT
/
@@999_x_dfn_ntp.update_unmapped_ids.data.sql
COMMIT
/

SPOOL OFF

EXIT