CREATE USER dfn_mig IDENTIFIED BY password DEFAULT TABLESPACE dfn_mig_ts QUOTA UNLIMITED ON dfn_mig_ts TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE JOB,
      RESOURCE,
	  CREATE DATABASE LINK,
      UNLIMITED TABLESPACE
    TO dfn_mig;