CREATE TABLE DFN_NTP.V14_CONTROLLABLE_FEATURES
  (
  ID NUMBER (3,0),
  FEATURE_NAME VARCHAR2 (50),
  ENABLED NUMBER (1)
 )
/
COMMENT ON COLUMN DFN_NTP.V14_CONTROLLABLE_FEATURES.ID IS 'Feature Id'
/
COMMENT ON COLUMN DFN_NTP.V14_CONTROLLABLE_FEATURES.FEATURE_NAME IS 'Feature Name'
/
COMMENT ON COLUMN DFN_NTP.V14_CONTROLLABLE_FEATURES.ENABLED IS 'Feature Availability; 1 = enable, 0 = disable'
/