CREATE TABLE DFN_NTP.T77_SYSTEM_NOTIFY_EVENTDATA
  (
  t77_event_id_m148 NUMBER (10),
  t77_notify_type NUMBER (10),
  t77_event_data CLOB,
  t77_created_date DATE,
  t77_id NUMBER (10) NOT NULL,
  t77_status NUMBER (5)
 )
/
COMMENT ON COLUMN DFN_NTP.T77_SYSTEM_NOTIFY_EVENTDATA.t77_notify_type IS 'Falcon-1'
/
COMMENT ON COLUMN DFN_NTP.T77_SYSTEM_NOTIFY_EVENTDATA.T77_STATUS IS '1-Read,0-Unread'
/

ALTER TABLE DFN_NTP.T77_SYSTEM_NOTIFY_EVENTDATA
 ADD (
  t77_component VARCHAR2 (50)
 )
/

ALTER TABLE DFN_NTP.T77_SYSTEM_NOTIFY_EVENTDATA
 ADD (
  t77_component_id NUMBER
 )
/