CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_bond_contract_list
(
    t68_id,
    t68_issued_bond_id_m171,
    t68_transaction_date,
    t68_settlement_date,
    t68_sub_asset_type,
    t68_bond_type,
    t68_bond_issue_date,
    t68_nominal_value,
    t68_premium_discount_amount,
    t68_interest_rate,
    t68_accrued_days,
    t68_accrued_interest,
    t68_maturity_date,
    t68_period,
    t68_contract_value,
    t68_last_payment_date,
    t68_next_payment_date,
    t68_quantity,
    t68_buyer_customer_id_u01,
    t68_buyer_cash_acc_id_u06,
    t68_buyer_currency_code_m03,
    t68_buyer_trading_acc_id_u07,
    t68_buyer_gross_settl_amount,
    t68_buyer_commission_id_m169,
    t68_buyer_commission_amount,
    t68_buyer_vat_amount,
    t68_buyer_net_settl_amount,
    t68_seller_customer_id_u01,
    t68_seller_cash_acc_id_u06,
    t68_seller_currency_code_m03,
    t68_seller_trading_acc_id_u07,
    t68_seller_gross_settl_amount,
    t68_seller_commission_id_m169,
    t68_seller_commission_amount,
    t68_seller_vat_amount,
    t68_seller_net_settl_amount,
    t68_status_id_v01,
    status,
    t68_created_by_id_u17,
    created_by,
    t68_created_date,
    t68_modified_by_id_u17,
    modified_by,
    t68_modified_date,
    t68_status_changed_by_id_u17,
    status_changed_by,
    t68_status_changed_date,
    t68_institute_id_m02,
    t68_bond_currency_code_m03,
    issued_bond,
    sub_asset_type,
    bondtype,
    buyer_trading_acc,
    buyer_customer_no,
    buyer_name,
    buyer_cash_acc,
    seller_trading_acc,
    seller_customer_no,
    seller_name,
    seller_cash_acc
)
AS
    SELECT t68.t68_id,
           t68.t68_issued_bond_id_m171,
           t68.t68_transaction_date,
           t68.t68_settlement_date,
           t68.t68_sub_asset_type,
           t68.t68_bond_type,
           t68.t68_bond_issue_date,
           t68.t68_nominal_value,
           t68.t68_premium_discount_amount,
           t68.t68_interest_rate,
           t68.t68_accrued_days,
           t68.t68_accrued_interest,
           t68.t68_maturity_date,
           t68.t68_period,
           t68.t68_contract_value,
           t68.t68_last_payment_date,
           t68.t68_next_payment_date,
           t68.t68_quantity,
           t68.t68_buyer_customer_id_u01,
           t68.t68_buyer_cash_acc_id_u06,
           t68.t68_buyer_currency_code_m03,
           t68.t68_buyer_trading_acc_id_u07,
           t68.t68_buyer_gross_settl_amount,
           t68.t68_buyer_commission_id_m169,
           t68.t68_buyer_commission_amount,
           t68.t68_buyer_vat_amount,
           t68.t68_buyer_net_settl_amount,
           t68.t68_seller_customer_id_u01,
           t68.t68_seller_cash_acc_id_u06,
           t68.t68_seller_currency_code_m03,
           t68.t68_seller_trading_acc_id_u07,
           t68.t68_seller_gross_settl_amount,
           t68.t68_seller_commission_id_m169,
           t68.t68_seller_commission_amount,
           t68.t68_seller_vat_amount,
           t68.t68_seller_net_settl_amount,
           t68.t68_status_id_v01,
           status_list.v01_description AS status,
           t68.t68_created_by_id_u17,
           u17_created_by.u17_full_name AS created_by,
           t68.t68_created_date,
           t68.t68_modified_by_id_u17,
           u17_modified_by.u17_full_name AS modified_by,
           t68.t68_modified_date,
           t68.t68_status_changed_by_id_u17,
           u17_status_changed_by.u17_full_name AS status_changed_by,
           t68.t68_status_changed_date,
           t68.t68_institute_id_m02,
           t68.t68_bond_currency_code_m03,
           m171.m171_name AS issued_bond,
           m171.sub_asset_type,
           m171.bondtype,
           buyer.u07_display_name AS buyer_trading_acc,
           buyer.u07_customer_no_u01 AS buyer_customer_no,
           buyer.u07_display_name_u01 AS buyer_name,
           buyer.u07_display_name_u06 AS buyer_cash_acc,
           seller.u07_display_name AS seller_trading_acc,
           seller.u07_customer_no_u01 AS seller_customer_no,
           seller.u07_display_name_u01 AS seller_name,
           seller.u07_display_name_u06 AS seller_cash_acc
      FROM t68_bond_contract t68
           JOIN vw_m171_bond_issue_list m171
               ON t68.t68_issued_bond_id_m171 = m171.m171_id
           JOIN trading_account_list buyer
               ON t68.t68_buyer_trading_acc_id_u07 = buyer.u07_id
           JOIN trading_account_list seller
               ON t68.t68_seller_trading_acc_id_u07 = seller.u07_id
           JOIN u17_employee u17_created_by
               ON t68.t68_created_by_id_u17 = u17_created_by.u17_id
           LEFT JOIN u17_employee u17_modified_by
               ON t68.t68_modified_by_id_u17 = u17_modified_by.u17_id
           JOIN u17_employee u17_status_changed_by
               ON t68.t68_status_changed_by_id_u17 =
                      u17_status_changed_by.u17_id
           LEFT JOIN vw_status_list status_list
               ON t68.t68_status_id_v01 = status_list.v01_id
/