CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_u24_holdings_for_symbol
(
    customer_id,
    customer_no,
    external_ref_no,
    institution_id,
    customer_name,
    u24_exchange_code_m01,
    u24_symbol_code_m20,
    trading_account_no,
    tot_holdings_with_unsettles,
    u24_avg_cost,
    u24_sell_pending,
    pledge_qty,
    u24_buy_pending,
    vwap,
    market_value_with_unsettles,
    vwap_val_hold_with_unsettle,
    short_description,
    long_description,
    short_description_lang,
    long_description_lang,
    expiry_date,
    avg_price,
    availableqty,
    currency,
    total_cost,
    last_trade_price,
    previous_closed,
    market_value,
    profit,
    market_price,
    profitpercentage,
    u07_exchange_account_no,
    u01_account_category_id_v01,
    instrument_type,
    u24_manual_block,
    strike_price,
    option_type,
    m20_cusip_no,
    isin_code,
    m20_reuters_code,
    u24_payable_holding,
    u24_receivable_holding,
    option_expiry_date,
    net_holdings,
    avg_cost,
    u24_trading_acnt_id_u07
)
AS
    SELECT a.customer_id,
           a.customer_no,
           d.u01_external_ref_no AS external_ref_no,
           a.institution_id,
           a.customer_name,
           a.u24_exchange_code_m01,
           a.u24_symbol_code_m20,
           a.u07_display_name AS trading_account_no,
           a.tot_holdings_with_unsettles,
           a.avg_cost u24_avg_cost,
           a.u24_sell_pending,
           a.pledge_qty,
           a.u24_buy_pending,
           a.vwap,
           a.market_value_with_unsettles,
           a.tot_holdings_with_unsettles * a.vwap * a.m20_lot_size
               AS vwap_val_hold_with_unsettle,
           a.short_description,
           a.long_description,
           a.short_description_lang,
           a.long_description_lang,
           a.expiry_date,
           a.avg_price,
           a.availableqty,
           a.currency,
           a.total_cost,
           a.last_trade_price,
           a.previous_closed,
           a.market_value,
           a.profit,
           a.market_price,
           a.profitpercentage,
           a.u07_exchange_account_no,
           d.u01_account_category_id_v01,
           a.m20_instrument_type_code_v09 AS instrument_type,
           a.u24_manual_block,
           a.strike_price,
           a.option_type,
           a.m20_cusip_no,
           a.m20_isincode AS isin_code,
           a.m20_reuters_code,
           a.u24_payable_holding,
           a.u24_receivable_holding,
           a.option_expiry_date,
           a.u24_net_holding AS net_holdings,
           ROUND (a.avg_cost, 8) avg_cost,
           u24_trading_acnt_id_u07
      FROM vw_u24_holdings_all a, u01_customer d
     WHERE     (   u24_net_holding <> 0
                OR u24_payable_holding <> 0
                OR u24_receivable_holding <> 0
                OR u24_pledge_qty <> 0
                OR u24_sell_pending <> 0
                OR u24_manual_block <> 0)
           AND a.customer_id = d.u01_id;
/
