CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_pending_pledge
(
    t20_id,
    t20_trading_acc_id_u07,
    t20_exchange,
    t20_symbol,
    t20_qty,
    total_pledge_qty,
    t20_instrument_type,
    t20_last_changed_by_id_u17,
    last_changed_by,
    t20_last_changed_date,
    t20_status_id_v01,
    status,
    t20_send_to_exchange,
    sentto_exchange,
    t20_send_to_exchange_result,
    t20_pledge_type,
    pledge_type,
    t20_transaction_number,
    t20_pledgee,
    t20_pledgor,
    t20_pledgor_ac_no,
    t20_nin,
    t20_pledge_call_member,
    t20_pledge_call_ac_no,
    t20_pledge_value,
    t20_narration,
    t20_exchange_fee,
    t20_broker_fee,
    t20_reject_reason,
    t20_remaining_qty,
    t20_custodian_id,
    t20_include_gl,
    t20_current_approval_level,
    t20_no_of_approval,
    t20_entered_date,
    t20_entered_by_id_u17,
    entered_by,
    u07_display_name,
    u07_id,
    u07_exchange_id_m01,
    u07_exchange_account_no,
    u07_institute_id_m02,
    u01_id,
    u01_customer_no,
    u01_full_name,
    u01_default_id_no,
    u01_external_ref_no,
    m20_short_description,
    u06_currency_code_m03,
    u06_charges_group_m117,
    u06_vat_waive_off,
    u07_cash_account_id_u06,
    t20_ref_no,
    t20_exchange_vat,
    t20_broker_vat
)
AS
    SELECT t20.t20_id,
           t20_trading_acc_id_u07,
           t20_exchange,
           t20_symbol,
           t20_qty,
           fn_get_remaining_pledge_qty (
               trading_acc_id   => t20.t20_trading_acc_id_u07,
               symbol           => t20.t20_symbol,
               send_to_ex       => t20.t20_send_to_exchange,
               exchnge          => t20.t20_exchange,
               trans_no         => t20.t20_transaction_number,
               symbol_id_m20    => t20.t20_symbol_id_m20)
               AS total_pledge_qty,
           t20_instrument_type,
           t20_last_changed_by_id_u17,
           u17l.u17_full_name AS last_changed_by,
           t20_last_changed_date,
           t20_status_id_v01,
           status_list.v01_description AS status,
           t20_send_to_exchange,
           CASE
               WHEN t20.t20_send_to_exchange = 0 THEN 'Internal'
               WHEN t20.t20_send_to_exchange = 1 THEN 'Exchange'
           END
               AS sentto_exchange,
           t20_send_to_exchange_result,
           t20_pledge_type,
           CASE
               WHEN t20.t20_pledge_type = '8' THEN 'IN'
               WHEN t20.t20_pledge_type = '9' THEN 'OUT'
           END
               AS pledge_type,
           t20_transaction_number,
           t20_pledgee,
           t20_pledgor,
           t20_pledgor_ac_no,
           t20_nin,
           t20_pledge_call_member,
           t20_pledge_call_ac_no,
           t20_pledge_value,
           t20_narration,
           t20_exchange_fee,
           t20_broker_fee,
           t20_reject_reason,
           t20_remaining_qty,
           t20_custodian_id,
           t20_include_gl,
           t20_current_approval_level,
           t20_no_of_approval,
           t20_entered_date,
           t20_entered_by_id_u17,
           u17e.u17_full_name AS entered_by,
           u07.u07_display_name,
           u07.u07_id,
           u07.u07_exchange_id_m01,
           u07.u07_exchange_account_no,
           u07.u07_institute_id_m02,
           u01.u01_id,
           u01.u01_customer_no,
           u01.u01_full_name,
           u01.u01_default_id_no,
           u01.u01_external_ref_no,
           m20.m20_short_description,
           u06.u06_currency_code_m03,
           u06.u06_charges_group_m117,
           u06.u06_vat_waive_off,
           u07.u07_cash_account_id_u06,
           t20_ref_no,
           t20_exg_vat AS t20_exchange_vat,
           t20_brk_vat AS t20_broker_vat
      FROM t20_pending_pledge t20,
           u07_trading_account u07,
           u01_customer u01,
           u06_cash_account u06,
           m20_symbol m20,
           vw_status_list status_list,
           u17_employee u17l,
           u17_employee u17e
     WHERE     t20.t20_trading_acc_id_u07 = u07.u07_id
           AND u07.u07_customer_id_u01 = u01.u01_id
           AND u07.u07_cash_account_id_u06 = u06.u06_id
           AND t20.t20_symbol_id_m20 = m20.m20_id(+)
           AND t20.t20_status_id_v01 = status_list.v01_id
           AND t20.t20_last_changed_by_id_u17 = u17l.u17_id(+)
           AND t20.t20_entered_by_id_u17 = u17e.u17_id(+)
           AND t20.t20_institution_id = m20_institute_id_m02
/