CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_a03_approval_audit
(
    a03_id,
    a03_table,
    a03_table_row_id,
    a03_status_id_v01,
    a03_where_clause,
    a03_created_date,
    a03_last_updated_date,
    a03_class,
    a03_current_approval_level,
    a03_no_of_approval,
    a03_new_value,
    a03_current_value,
    a03_ready_to_save_value,
    a03_description,
    a03_is_approval_completed,
    a03_table_id_m53,
    a03_table_description,
    a03_display_code,
    a03_next_status_id_v01,
    a03_approval_type,
    a03_created_by_id_u17,
    a03_last_updated_by_id_u17,
    a03_comment,
    a03_institute_id_m02,
    status,
    created_by_name,
    modified_by_name,
    next_status
)
AS
    SELECT a03_id,
           a03_table,
           a03_table_row_id,
           a03_status_id_v01,
           a03_where_clause,
           a03_created_date,
           a03_last_updated_date,
           a03_class,
           a03_current_approval_level,
           a03_no_of_approval,
           a03_new_value,
           a03_current_value,
           a03_ready_to_save_value,
           a03_description,
           a03_is_approval_completed,
           a03_table_id_m53,
           a03_table_description,
           a03_display_code,
           a03_next_status_id_v01,
           a03_approval_type,
           a03_created_by_id_u17,
           a03_last_updated_by_id_u17,
           a03_comment,
           a03_institute_id_m02,
           status_list.v01_description AS status,
           createdby.u17_full_name AS created_by_name,
           modifiedby.u17_full_name AS modified_by_name,
           next_status_list.v01_description AS next_status
      FROM a03_approval_audit_all a03,
           vw_status_list status_list,
           u17_employee createdby,
           u17_employee modifiedby,
           vw_status_list next_status_list
     WHERE     a03.a03_status_id_v01 = status_list.v01_id(+)
           AND a03.a03_created_by_id_u17 = createdby.u17_id(+)
           AND a03.a03_last_updated_by_id_u17 = modifiedby.u17_id(+)
           AND a03.a03_next_status_id_v01 = next_status_list.v01_id(+)
/
