CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_master_customer_list
(
    u01_id,
    u01_customer_no,
    u01_institute_id_m02,
    m02_name,
    u01_account_category_id_v01,
    acctype,
    u01_first_name,
    u01_first_name_lang,
    u01_second_name,
    u01_second_name_lang,
    u01_third_name,
    u01_third_name_lang,
    u01_last_name,
    u01_last_name_lang,
    u01_display_name,
    u01_display_name_lang,
    u01_gender,
    u01_title_id_v01,
    u01_marital_status_id_v01,
    u01_date_of_birth,
    u01_birth_country_id_m05,
    u01_birth_city_id_m06,
    u01_default_id_no,
    u01_default_id_type_m15,
    u01_default_id_type_txt,
    u01_default_id_type_txt_lang,
    u01_preferred_lang_id_v01,
    u01_is_ipo_customer,
    u01_is_black_listed,
    u01_created_by_id_u17,
    u01_created_date,
    u01_status_id_v01,
    status_description,
    v01_description_lang,
    u02_mobile,
    u02_email,
    u01_signup_location_id_m07,
    u01_service_location_id_m07,
    u01_relationship_mngr_id_m10,
    u01_grade,
    u01_black_listed_reason,
    u01_identification_code,
    u01_modified_by_id_u17,
    u01_modified_date,
    u01_status_changed_by_id_u17,
    u01_status_changed_date,
    u01_trading_enabled,
    u01_nationality_id_m05,
    nationalitycountry,
    u01_online_trading_enabled,
    trading,
    online_trading,
    u01_preferred_name,
    u01_preferred_name_lang,
    u01_full_name,
    u01_full_name_lang,
    u01_external_ref_no,
    u01_account_type_id_v01,
    u01_master_account_id_u01,
    u01_corp_client_type_id_v01,
    u01_corp_license_renewal_date,
    u01_corp_license,
    u01_corp_name_address_of_group,
    u01_corp_type_of_business,
    u01_corp_date_incorporation,
    u01_corp_country_id_m05,
    u01_corp_annual_turnover,
    u01_corp_region_id_m90,
    u01_corp_no_of_employees,
    u01_corp_regulatory_body,
    u01_corp_paid_up_capital,
    u01_corp_legal_form,
    u01_corp_general_partner,
    u01_corp_investors,
    acccategory
)
AS
    SELECT u01_id,
           u01_customer_no,
           u01_institute_id_m02,
           m02.m02_name,
           u01_account_category_id_v01,
           CASE
               WHEN u01.u01_account_type_id_v01 = 2 THEN 'Sub A/C'
               WHEN u01.u01_account_type_id_v01 = 1 THEN 'Master A/C'
           END
               AS acctype,
           u01_first_name,
           u01_first_name_lang,
           u01_second_name,
           u01_second_name_lang,
           u01_third_name,
           u01_third_name_lang,
           u01_last_name,
           u01_last_name_lang,
           u01_display_name,
           u01_display_name_lang,
           u01_gender,
           u01_title_id_v01,
           u01_marital_status_id_v01,
           u01_date_of_birth,
           u01_birth_country_id_m05,
           u01_birth_city_id_m06,
           u01_default_id_no,
           u01_default_id_type_m15,
           m15.m15_name AS u01_default_id_type_txt,
           m15.m15_name_lang || '_l' AS u01_default_id_type_txt_lang,
           u01_preferred_lang_id_v01,
           u01_is_ipo_customer,
           u01_is_black_listed,
           u01_created_by_id_u17,
           u01_created_date,
           u01_status_id_v01,
           status.v01_description AS status_description,
           status.v01_description_lang,
           u01.u01_def_mobile AS u02_mobile,
           u01.u01_def_email AS u02_email,
           u01_signup_location_id_m07,
           u01_service_location_id_m07,
           u01_relationship_mngr_id_m10,
           u01_grade,
           u01_black_listed_reason,
           u01_identification_code,
           u01_modified_by_id_u17,
           u01_modified_date,
           u01_status_changed_by_id_u17,
           u01_status_changed_date,
           u01.u01_trading_enabled,
           u01.u01_nationality_id_m05,
           nationality.m05_name AS nationalitycountry,
           u01.u01_online_trading_enabled,
           CASE WHEN u01.u01_trading_enabled = 1 THEN 'Yes' ELSE 'No' END
               AS trading,
           CASE
               WHEN u01.u01_online_trading_enabled = 1 THEN 'Yes'
               ELSE 'No'
           END
               AS online_trading,
           u01.u01_preferred_name,
           u01.u01_preferred_name_lang,
           u01.u01_full_name,
           u01.u01_full_name_lang,
           u01.u01_external_ref_no,
           u01.u01_account_type_id_v01,
           u01.u01_master_account_id_u01,
           u01.u01_corp_client_type_id_v01,
           u01.u01_corp_license_renewal_date,
           u01.u01_corp_license,
           u01.u01_corp_name_address_of_group,
           u01.u01_corp_type_of_business,
           u01.u01_corp_date_incorporation,
           u01.u01_corp_country_id_m05,
           u01.u01_corp_annual_turnover,
           u01.u01_corp_region_id_m90,
           u01.u01_corp_no_of_employees,
           u01.u01_corp_regulatory_body,
           u01.u01_corp_paid_up_capital,
           u01.u01_corp_legal_form,
           u01.u01_corp_general_partner,
           u01.u01_corp_investors,
           CASE
               WHEN u01_account_category_id_v01 = 1 THEN 'Individual'
               WHEN u01_account_category_id_v01 = 2 THEN 'Corporate'
           END
               AS acccategory
      FROM u01_customer u01,
           m15_identity_type m15,
           v01_system_master_data status,
           m05_country nationality,
           m02_institute m02
     WHERE     u01.u01_default_id_type_m15 = m15.m15_id(+)
           AND u01.u01_status_id_v01 = status.v01_id
           AND status.v01_type = 4
           AND u01.u01_nationality_id_m05 = nationality.m05_id(+)
           AND u01.u01_institute_id_m02 = m02.m02_id(+)
           AND u01.u01_account_type_id_v01 = 1;
/
