CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_cash_account_list
(
    u06_id,
    u06_institute_id_m02,
    u06_customer_id_u01,
    u06_customer_no_u01,
    u06_display_name_u01,
    u06_default_id_no_u01,
    default_email,
    default_mobile,
    u01_nationality_id_m05,
    u01_tax_ref,
    u06_currency_code_m03,
    u06_currency_id_m03,
    u06_balance,
    cash_for_withdraw,
    od_limit_today,
    od_margin_utilized,
    u06_blocked,
    u06_open_buy_blocked,
    u06_payable_blocked,
    u06_manual_trade_blocked,
    u06_manual_full_blocked,
    u06_manual_transfer_blocked,
    u06_receivable_amount,
    u06_is_default,
    is_default,
    u06_created_by_id_u17,
    created_by_name,
    u06_created_date,
    u06_status_id_v01,
    status,
    u06_margin_product_id_u23,
    margin_product,
    u06_modified_by_id_u17,
    modified_by_name,
    u06_modified_date,
    u06_status_changed_by_id_u17,
    status_changed_by_name,
    u06_status_changed_date,
    u06_last_activity_date,
    u06_display_name,
    margin_enabled,
    institute_name,
    u01_external_ref_no,
    u06_external_ref_no,
    u06_primary_od_limit,
    u06_primary_start,
    u06_primary_expiry,
    u06_secondary_od_limit,
    u06_secondary_start,
    u06_secondary_expiry,
    u06_investment_account_no,
    m177_cash_transfer_limit,
    u06_pending_restriction,
    symbol_marginability_group,
    u06_pending_withdraw,
    u06_pending_deposit,
    balance,
    interest,
    u06_charges_group_m117,
    charges_group,
    u06_vat_waive_off,
    vat_waive_off,
    u06_iban_no,
    u06_account_type_v01,
    account_type,
    u06_inactive_drmnt_status_v01,
    dormant_status,
    u06_net_receivable,
    u06_status_changed_reason,
    u02_mobile,
    u02_fax,
    u02_email,
    u02_zip_code,
    u02_po_box,
    u02_address_line1,
    u02_address_line2,
    u02_address_line2_lang,
    u02_building_no,
    u02_unit_no,
    u02_additional_code,
    u02_district,
    u02_district_lang,
    contract_country,
    contract_country_lang,
    contract_city,
    contract_city_lang,
    u06_margin_block,
    u06_margin_due,
    u06_discunt_charges_group_m165,
    discount_charges_group,
    u06_mutual_fund_account,
    mutual_fund_account,
    u06_order_limit_grp_id_m176,
    order_limit_group,
    u06_transfer_limit_grp_id_m177,
    cash_transfer_limit_group,
    u06_group_bp_enable,
    u06_other_commsion_grp_id_m22,
    u06_sub_waive_grp_id_m154_c
)
AS
    SELECT u06.u06_id,
           u06.u06_institute_id_m02,
           u06.u06_customer_id_u01,
           u06.u06_customer_no_u01,
           u06.u06_display_name_u01,
           u06.u06_default_id_no_u01,
           u02.u02_email AS default_email,
           u02.u02_mobile AS default_mobile,
           u01.u01_nationality_id_m05,
           u01.u01_tax_ref,
           u06.u06_currency_code_m03,
           u06.u06_currency_id_m03,
           u06.u06_balance,
           u06.cash_for_withdraw,
           u06.od_limit_today,
           CASE
               WHEN u06.u06_balance < 0 THEN ABS (u06.u06_balance)
               ELSE 0
           END
               AS od_margin_utilized,
           u06.u06_blocked,
           u06.u06_open_buy_blocked,
           u06.u06_payable_blocked,
           u06.u06_manual_trade_blocked,
           u06.u06_manual_full_blocked,
           u06.u06_manual_transfer_blocked,
           u06.u06_receivable_amount,
           u06.u06_is_default,
           CASE WHEN u06_is_default = 1 THEN 'Yes' ELSE 'No' END
               AS is_default,
           u06.u06_created_by_id_u17,
           createdby.u17_full_name AS created_by_name,
           u06.u06_created_date,
           u06.u06_status_id_v01,
           status.v01_description AS status,
           u06.u06_margin_product_id_u23,
           m73.m73_name AS margin_product,
           u06.u06_modified_by_id_u17,
           modifiedby.u17_full_name AS modified_by_name,
           u06.u06_modified_date,
           u06.u06_status_changed_by_id_u17,
           statuschangedby.u17_full_name AS status_changed_by_name,
           u06.u06_status_changed_date,
           u06.u06_last_activity_date,
           u06.u06_display_name,
           CASE u06.u06_margin_enabled WHEN 1 THEN 'Yes' ELSE 'No' END
               AS margin_enabled,
           m02.m02_name AS institute_name,
           u01.u01_external_ref_no,
           u06.u06_external_ref_no,
           u06.u06_primary_od_limit,
           u06.u06_primary_start,
           u06.u06_primary_expiry,
           u06.u06_secondary_od_limit,
           u06.u06_secondary_start,
           u06.u06_secondary_expiry,
           u06.u06_investment_account_no,
           m177.m177_cash_transfer_limit,
           u06.u06_pending_restriction,
           m77.m77_name AS symbol_marginability_group,
           u06.u06_pending_withdraw,
           u06.u06_pending_deposit,
             u06.u06_balance
           + u06.u06_payable_blocked
           - u06.u06_receivable_amount
               AS balance,
           fn_get_interest_for_cash_acc (u06.u06_id) AS interest,
           u06.u06_charges_group_m117,
           m117.m117_name AS charges_group,
           u06.u06_vat_waive_off,
           CASE u06.u06_vat_waive_off WHEN 1 THEN 'Yes' ELSE 'No' END
               AS vat_waive_off,
           u06.u06_iban_no,
           u06.u06_account_type_v01,
           CASE u06.u06_account_type_v01
               WHEN 1 THEN 'Investment'
               WHEN 2 THEN 'Share Finance'
               WHEN 3 THEN 'Mutual Fund'
           END
               AS account_type,
           u06.u06_inactive_drmnt_status_v01,
           CASE u06.u06_inactive_drmnt_status_v01
               WHEN 11 THEN dormnt_status.v01_description
               WHEN 12 THEN dormnt_status.v01_description
               ELSE ''
           END
               AS dormant_status,
           u06.u06_net_receivable,
           u06.u06_status_changed_reason,
           u02.u02_mobile,
           u02.u02_fax,
           u02.u02_email,
           u02.u02_zip_code,
           u02.u02_po_box,
           u02.u02_address_line1,
           u02.u02_address_line2,
           u02.u02_address_line2_lang,
           u02.u02_building_no,
           u02.u02_unit_no,
           u02.u02_additional_code,
           u02.u02_district,
           u02.u02_district_lang,
           u02.country AS contract_country,
           u02.country_lang AS contract_country_lang,
           u02.city AS contract_city,
           u02.city_lang AS contract_city_lang,
           u06.u06_margin_block,
           u06.u06_margin_due,
           u06.u06_discunt_charges_group_m165,
           m165.m165_name AS discount_charges_group,
           u06.u06_mutual_fund_account,
           CASE u06.u06_mutual_fund_account WHEN 1 THEN 'Yes' ELSE 'No' END
               AS mutual_fund_account,
           u06.u06_order_limit_grp_id_m176,
           m176.m176_group_name AS order_limit_group,
           u06.u06_transfer_limit_grp_id_m177,
           m177.m177_group_name AS cash_transfer_limit_group,
           u06_group_bp_enable,
           u06_other_commsion_grp_id_m22,
           u06_sub_waive_grp_id_m154_c
      FROM vw_u06_cash_account_base u06,
           vw_status_list status,
           u17_employee createdby,
           u17_employee modifiedby,
           u17_employee statuschangedby,
           u23_customer_margin_product u23,
           m02_institute m02,
           u01_customer u01,
           m77_symbol_marginability_grps m77,
           m117_charge_groups m117,
           vw_status_list dormnt_status,
           m73_margin_products m73,
           m165_discount_charge_groups m165,
           (SELECT *
              FROM vw_customer_contact_info
             WHERE u02_is_default = 1) u02,
           m176_order_limit_group m176,
           m177_cash_transfer_limit_group m177
     WHERE     u06.u06_status_id_v01 = status.v01_id
           AND u06.u06_created_by_id_u17 = createdby.u17_id
           AND u06.u06_modified_by_id_u17 = modifiedby.u17_id(+)
           AND u06.u06_status_changed_by_id_u17 = statuschangedby.u17_id
           AND u06.u06_margin_product_id_u23 = u23.u23_id(+)
           AND u06.u06_institute_id_m02 = m02.m02_id
           AND u06.u06_customer_id_u01 = u01.u01_id
           AND u23.u23_sym_margin_group_m77 = m77.m77_id(+)
           AND u06.u06_charges_group_m117 = m117.m117_id(+)
           AND u06.u06_inactive_drmnt_status_v01 = dormnt_status.v01_id(+)
           AND u23.u23_margin_product_m73 = m73.m73_id(+)
           AND u06.u06_customer_id_u01 = u02.u02_customer_id_u01(+)
           AND u06.u06_discunt_charges_group_m165 = m165.m165_id(+)
           AND u06.u06_order_limit_grp_id_m176 = m176.m176_id(+)
           AND u06.u06_transfer_limit_grp_id_m177 = m177.m177_id(+)
/