CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_symbol_data
(
   m20_id,
   m20_exchange_id_m01,
   m20_symbol_code,
   m20_short_description,
   m20_short_description_lang,
   m20_long_description,
   m20_long_description_lang,
   m20_market_code_m29,
   m20_instrument_type_code_v09,
   m20_instrument_type_id_v09,
   m20_currency_code_m03,
   m20_currency_id_m03,
   m20_trading_status_id_v22,
   trading_status,
   m20_status_id_v01,
   status,
   m20_access_level_id_v01,
   m20_cusip_no,
   m20_reuters_code,
   access_level,
   m20_price_ratio,
   m20_exchange_code_m01,
   m20_price_exchange_code_m01,
   m20_price_symbol_code_m20,
   m20_small_orders,
   small_orders,
   m20_small_order_value,
   m20_status_changed_by_id_u17,
   status_changed_by,
   m20_is_white_symbol,
   is_white_symbol,
   m20_market_segment,
   market_segment,
   m20_trading_allowed,
   m20_settle_category_v11,
   m20_lot_size,
   m20_lasttradeprice,
   m20_date_of_last_price,
   m20_maxprice,
   m20_minprice,
   m20_restricted_direction,
   m20_online_trading_allowed,
   m20_isincode,
   m20_exchange_symbol_code_m20,
   m20_vwap,
   m20_trade_type_v01,
   m20_short_selling,
   m20_option_type,
   m20_strike_price,
   m20_previous_closed,
   m20_bestbidprice,
   m20_bestaskprice,
   v26_description,
   m20_interest_rate,
   m20_int_payment_date,
   v25_duration,
   m20_base_symbol_m20,
   m20_base_exchange_code_m01,
   v34_price_inst_type_id,
   m20_maturity_date,
   m20_today_closed,
   m20_static_min,
   m20_static_max,
   m20_institute_id_m02,
   m20_market_id_m29,
   m20_expire_date,
   m20_initial_margin_value,
   m20_base_symbol_id_m20,
   m20_client_fee_per_buy_b,
   m20_staff_fee_per_buy_b,
   m20_ytd_nav_b,
   m20_date_of_ytd_nav_b,
   m20_risk_profile_b,
   m20_share_class_b,
   m20_share_class_desc_b,
   m20_share_cls_desc_lang_b,
   m20_fund_family_b,
   m20_asset_type_b,
   m20_asset_type_desc_b,
   m20_asset_type_desc_lang_b,
   m20_market_b,
   m20_market_desc_b,
   m20_market_desc_lang_b,
   m20_region_b,
   m20_region_desc_b,
   m20_region_desc_lang_b,
   m20_fund_inv_profile_b,
   m20_fund_size_b,
   m20_nav_inception_b,
   m20_comparative_index_b,
   m20_date_of_incepttion_b,
   m20_sub_fee_b,
   m20_management_fee_b,
   m20_minimum_sub_b,
   m20_dealing_days_b,
   m20_announce_days_b,
   m20_sub_redem_cut_off_b,
   m20_redem_payment_b,
   m20_fund_type_b,
   m20_fund_family_desc_b,
   m20_fund_family_desc_lang_b
)
AS
( (SELECT m20.m20_id,
              m20.m20_exchange_id_m01,
              m20.m20_symbol_code,
              m20.m20_short_description,
              m20.m20_short_description_lang,
              m20.m20_long_description,
              m20.m20_long_description_lang,
              m20.m20_market_code_m29,
              m20.m20_instrument_type_code_v09,
              m20.m20_instrument_type_id_v09,
              m20.m20_currency_code_m03,
              m20.m20_currency_id_m03,
              m20.m20_trading_status_id_v22,
              v22.v22_description AS trading_status,
              m20.m20_status_id_v01,
              vw_status_list.v01_description AS status,
              m20.m20_access_level_id_v01,
              m20.m20_cusip_no,
              m20.m20_reuters_code,
              vw_access_level.v01_description AS access_level,
              m20.m20_price_ratio,
              m20.m20_exchange_code_m01,
              m20.m20_price_exchange_code_m01,
              m20.m20_price_symbol_code_m20,
              m20.m20_small_orders,
              CASE m20.m20_small_orders
                  WHEN 0 THEN 'No'
                  WHEN 1 THEN 'Yes'
              END
                  AS small_orders,
              m20.m20_small_order_value,
              m20.m20_status_changed_by_id_u17,
              u17.u17_full_name AS status_changed_by,
              m20.m20_is_white_symbol,
              CASE m20.m20_is_white_symbol
                  WHEN 0 THEN 'No'
                  WHEN 1 THEN 'Yes'
              END
                  AS is_white_symbol,
              m20.m20_market_segment,
              CASE m20.m20_market_segment
                  WHEN 1 THEN 'Main Market'
                  WHEN 2 THEN 'Second Market'
                  WHEN 3 THEN 'Main Market & Second Market'
              END
                  AS market_segment,
              m20.m20_trading_allowed,
              m20.m20_settle_category_v11,
              m20.m20_lot_size,
              m20.m20_lasttradeprice,
              m20.m20_date_of_last_price,
              m20.m20_maxprice,
              m20.m20_minprice,
              m20.m20_restricted_direction,
              m20.m20_online_trading_allowed,
              m20.m20_isincode,
              m20.m20_exchange_symbol_code_m20,
              m20.m20_vwap,
              m20.m20_trade_type_v01,
              m20.m20_short_selling,
              m20.m20_option_type,
              m20.m20_strike_price,
              m20.m20_previous_closed,
              m20.m20_bestbidprice,
              m20.m20_bestaskprice,
              v26.v26_description,
              m20_extnd.m20_interest_rate,
              m20_extnd.m20_int_payment_date,
              v25.v25_duration,
              m20.m20_base_symbol_m20,
              m20.m20_base_exchange_code_m01,
              v34.v34_price_inst_type_id,
              CASE
                  WHEN (    m20_extnd.m20_maturity_myear IS NOT NULL
                        AND m20_extnd.m20_maturity_day IS NOT NULL)
                  THEN
                      TO_DATE (
                             m20_extnd.m20_maturity_myear
                          || m20_extnd.m20_maturity_day,
                          'yyyymmdd')
                  WHEN m20.m20_expire_date IS NOT NULL
                  THEN
                      TRUNC (m20.m20_expire_date)
              END
                  AS m20_maturity_date,
              m20.m20_today_closed,
              m20_static_min,
              m20_static_max,
              m20_institute_id_m02,
              m20_market_id_m29,
              m20.m20_expire_date,
              m20.m20_initial_margin_value,
              m20.m20_base_symbol_id_m20,
              m20.m20_client_fee_per_buy_b,
              m20.m20_staff_fee_per_buy_b,
              m20.m20_ytd_nav_b,
              m20.m20_date_of_ytd_nav_b,
              m20.m20_risk_profile_b,
              m20.m20_share_class_b,
              m20.m20_share_class_desc_b,
              m20.m20_share_cls_desc_lang_b,
              m20.m20_fund_family_b,
              m20.m20_asset_type_b,
              m20.m20_asset_type_desc_b,
              m20.m20_asset_type_desc_lang_b,
              m20.m20_market_b,
              m20.m20_market_desc_b,
              m20.m20_market_desc_lang_b,
              m20.m20_region_b,
              m20.m20_region_desc_b,
              m20.m20_region_desc_lang_b,
              m20.m20_fund_inv_profile_b,
              m20.m20_fund_size_b,
              m20.m20_nav_inception_b,
              m20.m20_comparative_index_b,
              m20.m20_date_of_incepttion_b,
              m20.m20_sub_fee_b,
              m20.m20_management_fee_b,
              m20.m20_minimum_sub_b,
              m20.m20_dealing_days_b,
              m20.m20_announce_days_b,
              m20.m20_sub_redem_cut_off_b,
              m20.m20_redem_payment_b,
              m20.m20_fund_type_b,
              m20.m20_fund_family_desc_b,
              m20.m20_fund_family_desc_lang_b
         FROM m20_symbol m20
              LEFT JOIN vw_access_level
                  ON vw_access_level.v01_id = m20.m20_access_level_id_v01
              LEFT JOIN v22_symbol_status v22
                  ON v22.v22_id = m20.m20_trading_status_id_v22
              LEFT JOIN u17_employee u17
                  ON u17.u17_id = m20.m20_status_changed_by_id_u17
              LEFT JOIN vw_status_list
                  ON m20.m20_status_id_v01 = vw_status_list.v01_id
              LEFT JOIN m20_symbol_extended m20_extnd
                  ON m20.m20_id = m20_extnd.m20_id
              LEFT JOIN v26_interest_day_basis v26
                  ON m20_extnd.m20_interest_day_basis_id_v26 = v26.v26_id
              LEFT JOIN v25_payment_types v25
                  ON m20_extnd.m20_no_of_payment_v25 = v25.v25_id
              LEFT JOIN v34_price_instrument_type v34
                  ON m20.m20_price_instrument_id_v34 = v34.v34_id))
/