CREATE OR REPLACE FORCE VIEW dfn_ntp.m36_settlement_calendar_all
(
    m36_buy_cash_settle_date,
    m36_buy_holdings_settle_date,
    m36_sell_cash_settle_date,
    m36_sell_holdings_settle_date,
    m36_month_end,
    m36_week_end,
    m36_date,
    m36_exchange_code_m01,
    m36_instrument_type_code_v09,
    m36_symbol_settle_category_v11,
    m36_cust_settle_group_id_m35,
    m36_description,
    m36_holiday,
    m36_working_day,
    m36_institution_id_m02,
    m36_instrument_type_id_v09,
    m36_year,
    is_temp_record,
    m36_settle_cal_conf_id_m95
)
AS
    SELECT m36_buy_cash_settle_date,
           m36_buy_holdings_settle_date,
           m36_sell_cash_settle_date,
           m36_sell_holdings_settle_date,
           m36_month_end,
           m36_week_end,
           m36_date,
           m36_exchange_code_m01,
           m36_instrument_type_code_v09,
           m36_symbol_settle_category_v11,
           m36_cust_settle_group_id_m35,
           m36_description,
           m36_holiday,
           m36_working_day,
           m36_institution_id_m02,
           m36_instrument_type_id_v09,
           m36_year,
           is_temp_record,
           m36_settle_cal_conf_id_m95
      FROM dfn_ntp.m36_settlement_calendar
    UNION ALL
    SELECT m36_buy_cash_settle_date,
           m36_buy_holdings_settle_date,
           m36_sell_cash_settle_date,
           m36_sell_holdings_settle_date,
           m36_month_end,
           m36_week_end,
           m36_date,
           m36_exchange_code_m01,
           m36_instrument_type_code_v09,
           m36_symbol_settle_category_v11,
           m36_cust_settle_group_id_m35,
           m36_description,
           m36_holiday,
           m36_working_day,
           m36_institution_id_m02,
           m36_instrument_type_id_v09,
           m36_year,
           is_temp_record,
           m36_settle_cal_conf_id_m95
      FROM dfn_arc.m36_settlement_calendar
/
