CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_t01_right_subscription_list
(
    t01_cl_ord_id,
    t01_ord_no,
    t01_side,
    order_side,
    t01_quantity,
    t01_leaves_qty,
    t01_price,
    t01_cum_quantity,
    t01_avg_price,
    t01_cum_ord_value,
    t01_cum_net_value,
    t01_ord_type_id_v06,
    t01_ord_value,
    t01_commission,
    t01_min_quantity,
    t01_date,
    t01_date_time,
    t01_expiry_date,
    t01_cash_settle_date,
    t01_holding_settle_date,
    t01_exchange_code_m01,
    t01_tif_id_v10,
    t01_status_id_v30,
    t01_order_mode,
    t01_disclose_qty,
    t01_broker_tax,
    t01_exchange_tax,
    t01_cum_commission,
    t01_instrument_type_code,
    t01_cum_exec_brk_commission,
    t01_exec_brk_commission,
    cum_broker_commission,
    t01_ord_net_value,
    t01_settle_currency,
    t01_cum_exchange_tax,
    t01_cum_broker_tax,
    t01_settle_currency_rate,
    t01_ord_net_settle,
    t01_exec_broker_id_m26,
    v30_description,
    v30_description_lang,
    v10_description,
    u01_preferred_lang_id_v01,
    u01_id,
    u01_customer_no,
    u01_display_name,
    u02_mobile,
    u02_email,
    u01_nationality_id_m05,
    u01_external_ref_no,
    t01_symbol_id_m20,
    m20_symbol_code,
    v06_description,
    v06_description_lang,
    m20_isincode,
    m20_short_description,
    m20_currency_id_m03,
    m20_currency_code_m03,
    t01_trading_acntno_u07,
    t01_last_shares,
    t01_last_price,
    t01_ord_channel_id_v29,
    v29_description,
    t01_custodian_id_m26,
    m26_sid,
    m26_name,
    t01_reject_reason,
    t01_accrued_interest,
    m20_expire_date,
    m20_option_type,
    option_type_desc,
    m20_strike_price,
    t01_position_effect,
    position_effect_desc,
    position_covered,
    t01_orig_cl_ord_id,
    t01_trading_acc_id_u07,
    t01_cash_acc_id_u06,
    t01_block_amount,
    t01_cum_netstl,
    t01_market_code_m29,
    t01_tenant_code,
    t01_exchange_ord_id,
    t01_price_inst_type,
    t01_dealer_id_u17,
    t01_last_updated_date_time,
    format_last_update_date_time,
    t01_fail_mngmnt_status,
    t01_fail_mngmnt_status_desc,
    t01_institution_id_m02,
    u17_full_name,
    t01_customer_id_u01,
    exec_broker,
    u07_display_name,
    custodian_type,
    t01_desk_order_ref_t52,
    t01_desk_order_no_t52,
    t01_trade_process_stat_id_v01,
    v01_description,
    v01_description_lang,
    approved_by_name,
    u09_login_name,
    total_tax
)
AS
    SELECT t01_cl_ord_id,
           t01_ord_no,
           t01_side,
           order_side,
           t01_quantity,
           t01_leaves_qty,
           t01_price,
           t01_cum_quantity,
           t01_avg_price,
           t01_cum_ord_value,
           t01_cum_net_value,
           t01_ord_type_id_v06,
           t01_ord_value,
           t01_commission,
           t01_min_quantity,
           t01_date,
           t01_date_time,
           t01_expiry_date,
           t01_cash_settle_date,
           t01_holding_settle_date,
           t01_exchange_code_m01,
           t01_tif_id_v10,
           t01_status_id_v30,
           t01_order_mode,
           t01_disclose_qty,
           t01_broker_tax,
           t01_exchange_tax,
           t01_cum_commission,
           t01_instrument_type_code,
           t01_cum_exec_brk_commission,
           t01_exec_brk_commission,
           cum_broker_commission,
           t01_ord_net_value,
           t01_settle_currency,
           t01_cum_exchange_tax,
           t01_cum_broker_tax,
           t01_settle_currency_rate,
           t01_ord_net_settle,
           t01_exec_broker_id_m26,
           v30_description,
           v30_description_lang,
           v10_description,
           u01_preferred_lang_id_v01,
           u01_id,
           u01_customer_no,
           u01_display_name,
           u01_def_mobile AS u02_mobile,
           u01_def_email AS u02_email,
           u01_nationality_id_m05,
           u01_external_ref_no,
           t01_symbol_id_m20,
           m20_symbol_code,
           v06_description,
           v06_description_lang,
           m20_isincode,
           m20_short_description,
           m20_currency_id_m03,
           m20_currency_code_m03,
           t01_trading_acntno_u07,
           t01_last_shares,
           t01_last_price,
           t01_ord_channel_id_v29,
           v29_description,
           t01_custodian_id_m26,
           m26_custody.m26_sid,
           m26_custody.m26_name,
           t01_reject_reason,
           t01_accrued_interest,
           m20_expire_date,
           m20_option_type,
           DECODE (m20.m20_option_type,  0, 'Put',  1, 'Call')
               AS option_type_desc,
           m20_strike_price,
           t01_position_effect,
           position_effect_desc,
           position_covered,
           t01_orig_cl_ord_id,
           t01_trading_acc_id_u07,
           t01_cash_acc_id_u06,
           t01_block_amount,
           t01_cum_netstl,
           t01_market_code_m29,
           t01_tenant_code,
           t01_exchange_ord_id,
           t01_price_inst_type,
           t01_dealer_id_u17,
           t01_last_updated_date_time,
           format_last_update_date_time,
           t01_fail_mngmnt_status,
           t01_fail_mngmnt_status_desc,
           t01_institution_id_m02,
           u17_full_name,
           t01_customer_id_u01,
           m26_broker.m26_sid AS exec_broker,
           u07_display_name,
           custodian_type,
           t01_desk_order_ref_t52,
           t01_desk_order_no_t52,
           t01_trade_process_stat_id_v01,
           v01_description,
           v01_description_lang,
           u17_approve.u17_full_name AS approved_by_name,
           u09_login_name,
           total_tax
      FROM vw_t01_order_list_base
           LEFT JOIN u09_customer_login u09
               ON t01_customer_login_id_u09 = u09.u09_id
           LEFT JOIN u17_employee u17_approve
               ON t01_approved_by_id_u17 = u17_approve.u17_id
           LEFT JOIN vw_status_list v01
               ON t01_trade_process_stat_id_v01 = v01.v01_id
           LEFT JOIN u07_trading_account u07
               ON t01_trading_acc_id_u07 = u07.u07_id
           LEFT JOIN m26_executing_broker m26_broker
               ON t01_exec_broker_id_m26 = m26_broker.m26_id
           LEFT JOIN m26_executing_broker m26_custody
               ON t01_custodian_id_m26 = m26_custody.m26_id
           LEFT JOIN m20_symbol m20
               ON m20.m20_id = t01_symbol_id_m20
           LEFT JOIN u01_customer u01
               ON t01_customer_id_u01 = u01.u01_id
           LEFT JOIN v30_order_status v30
               ON t01_status_id_v30 = v30.v30_status_id
     WHERE t01_side IN (3)
/