CREATE OR REPLACE FORCE VIEW dfn_ntp.vw_u24_h01_holdings_all
(
    trading_acnt_id_u07,
    exchange_code_m01,
    symbol_id_m20,
    holding_date,
    custodian_id_m26,
    holding_block,
    sell_pending,
    buy_pending,
    weighted_avg_price,
    avg_price,
    weighted_avg_cost,
    avg_cost,
    receivable_holding,
    payable_holding,
    symbol_code_m20,
    realized_gain_lost,
    currency_code_m03,
    price_inst_type,
    pledge_qty,
    manual_block,
    net_holding,
    custodian_code_m26,
    short_holdings,
    net_receivable,
    subscribed_qty,
    pending_subscribe_qty
)
AS
    SELECT u24_trading_acnt_id_u07 AS trading_acnt_id_u07,
           u24_exchange_code_m01 AS exchange_code_m01,
           u24_symbol_id_m20 AS symbol_id_m20,
           TRUNC (SYSDATE) AS holding_date,
           u24_custodian_id_m26 AS custodian_id_m26,
           u24_holding_block AS holding_block,
           u24_sell_pending AS sell_pending,
           u24_buy_pending AS buy_pending,
           u24_weighted_avg_price AS weighted_avg_price,
           u24_avg_price AS avg_price,
           u24_weighted_avg_cost AS weighted_avg_cost,
           u24_avg_cost AS avg_cost,
           u24_receivable_holding AS receivable_holding,
           u24_payable_holding AS payable_holding,
           u24_symbol_code_m20 AS symbol_code_m20,
           u24_realized_gain_lost AS realized_gain_lost,
           u24_currency_code_m03 AS currency_code_m03,
           u24_price_inst_type AS price_inst_type,
           u24_pledge_qty AS pledge_qty,
           u24_manual_block AS manual_block,
           u24_net_holding AS net_holding,
           u24_custodian_code_m26 AS custodian_code_m26,
           u24_short_holdings AS short_holdings,
           u24_net_receivable AS net_receivable,
           u24_subscribed_qty AS subscribed_qty,
           u24_pending_subscribe_qty AS pending_subscribe_qty
      FROM u24_holdings
    UNION ALL
    SELECT h01_trading_acnt_id_u07 AS trading_acnt_id_u07,
           h01_exchange_code_m01 AS exchange_code_m01,
           h01_symbol_id_m20 AS symbol_id_m20,
           h01_date AS holding_date,
           h01_custodian_id_m26 AS custodian_id_m26,
           h01_holding_block AS holding_block,
           h01_sell_pending AS sell_pending,
           h01_buy_pending AS buy_pending,
           h01_weighted_avg_price AS weighted_avg_price,
           h01_avg_price AS avg_price,
           h01_weighted_avg_cost AS weighted_avg_cost,
           h01_avg_cost AS avg_cost,
           h01_receivable_holding AS receivable_holding,
           h01_payable_holding AS payable_holding,
           h01_symbol_code_m20 AS symbol_code_m20,
           h01_realized_gain_lost AS realized_gain_lost,
           h01_currency_code_m03 AS currency_code_m03,
           h01_price_inst_type AS price_inst_type,
           h01_pledge_qty AS pledge_qty,
           h01_manual_block AS manual_block,
           h01_net_holding AS net_holding,
           h01_custodian_code_m26 AS custodian_code_m26,
           h01_short_holdings AS short_holdings,
           h01_net_receivable AS net_receivable,
           h01_subscribed_qty AS subscribed_qty,
           h01_pending_subscribe_qty AS pending_subscribe_qty
      FROM h01_holding_summary_all
/