
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_INS_UPD_MKT_DEPTH_MBPS (
    v_exchangecode     IN esp_marketdepth.exchangecode%TYPE,
    v_symbol           IN esp_marketdepth.symbol%TYPE,
    v_mbps_bid1        IN esp_marketdepth.mbps_bid1%TYPE,
    v_mbps_bid_qty1    IN esp_marketdepth.mbps_bid_qty1%TYPE,
    v_mbps_bid2        IN esp_marketdepth.mbps_bid2%TYPE,
    v_mbps_bid_qty2    IN esp_marketdepth.mbps_bid_qty2%TYPE,
    v_mbps_bid3        IN esp_marketdepth.mbps_bid3%TYPE,
    v_mbps_bid_qty3    IN esp_marketdepth.mbps_bid_qty3%TYPE,
    v_mbps_bid4        IN esp_marketdepth.mbps_bid4%TYPE,
    v_mbps_bid_qty4    IN esp_marketdepth.mbps_bid_qty4%TYPE,
    v_mbps_bid5        IN esp_marketdepth.mbps_bid5%TYPE,
    v_mbps_bid_qty5    IN esp_marketdepth.mbps_bid_qty5%TYPE,
    v_mbps_bid6        IN esp_marketdepth.mbps_bid6%TYPE,
    v_mbps_bid_qty6    IN esp_marketdepth.mbps_bid_qty6%TYPE,
    v_mbps_bid7        IN esp_marketdepth.mbps_bid7%TYPE,
    v_mbps_bid_qty7    IN esp_marketdepth.mbps_bid_qty7%TYPE,
    v_mbps_bid8        IN esp_marketdepth.mbps_bid8%TYPE,
    v_mbps_bid_qty8    IN esp_marketdepth.mbps_bid_qty8%TYPE,
    v_mbps_bid9        IN esp_marketdepth.mbps_bid9%TYPE,
    v_mbps_bid_qty9    IN esp_marketdepth.mbps_bid_qty9%TYPE,
    v_mbps_bid10       IN esp_marketdepth.mbps_bid10%TYPE,
    v_mbps_bid_qty10   IN esp_marketdepth.mbps_bid_qty10%TYPE,
    v_mbps_ask1        IN esp_marketdepth.mbps_ask1%TYPE,
    v_mbps_ask_qty1    IN esp_marketdepth.mbps_ask_qty1%TYPE,
    v_mbps_ask2        IN esp_marketdepth.mbps_ask2%TYPE,
    v_mbps_ask_qty2    IN esp_marketdepth.mbps_ask_qty2%TYPE,
    v_mbps_ask3        IN esp_marketdepth.mbps_ask3%TYPE,
    v_mbps_ask_qty3    IN esp_marketdepth.mbps_ask_qty3%TYPE,
    v_mbps_ask4        IN esp_marketdepth.mbps_ask4%TYPE,
    v_mbps_ask_qty4    IN esp_marketdepth.mbps_ask_qty4%TYPE,
    v_mbps_ask5        IN esp_marketdepth.mbps_ask5%TYPE,
    v_mbps_ask_qty5    IN esp_marketdepth.mbps_ask_qty5%TYPE,
    v_mbps_ask6        IN esp_marketdepth.mbps_ask6%TYPE,
    v_mbps_ask_qty6    IN esp_marketdepth.mbps_ask_qty6%TYPE,
    v_mbps_ask7        IN esp_marketdepth.mbps_ask7%TYPE,
    v_mbps_ask_qty7    IN esp_marketdepth.mbps_ask_qty7%TYPE,
    v_mbps_ask8        IN esp_marketdepth.mbps_ask8%TYPE,
    v_mbps_ask_qty8    IN esp_marketdepth.mbps_ask_qty8%TYPE,
    v_mbps_ask9        IN esp_marketdepth.mbps_ask9%TYPE,
    v_mbps_ask_qty9    IN esp_marketdepth.mbps_ask_qty9%TYPE,
    v_mbps_ask10       IN esp_marketdepth.mbps_ask10%TYPE,
    v_mbps_ask_qty10   IN esp_marketdepth.mbps_ask_qty10%TYPE)
AS
BEGIN
    UPDATE esp_marketdepth
       SET mbps_bid1 = v_mbps_bid1,
           mbps_bid_qty1 = v_mbps_bid_qty1,
           mbps_bid2 = v_mbps_bid2,
           mbps_bid_qty2 = v_mbps_bid_qty2,
           mbps_bid3 = v_mbps_bid3,
           mbps_bid_qty3 = v_mbps_bid_qty3,
           mbps_bid4 = v_mbps_bid4,
           mbps_bid_qty4 = v_mbps_bid_qty4,
           mbps_bid5 = v_mbps_bid5,
           mbps_bid_qty5 = v_mbps_bid_qty5,
           mbps_bid6 = v_mbps_bid6,
           mbps_bid_qty6 = v_mbps_bid_qty6,
           mbps_bid7 = v_mbps_bid7,
           mbps_bid_qty7 = v_mbps_bid_qty7,
           mbps_bid8 = v_mbps_bid8,
           mbps_bid_qty8 = v_mbps_bid_qty8,
           mbps_bid9 = v_mbps_bid9,
           mbps_bid_qty9 = v_mbps_bid_qty9,
           mbps_bid10 = v_mbps_bid10,
           mbps_bid_qty10 = v_mbps_bid_qty10,
           mbps_ask1 = v_mbps_ask1,
           mbps_ask_qty1 = v_mbps_ask_qty1,
           mbps_ask2 = v_mbps_ask2,
           mbps_ask_qty2 = v_mbps_ask_qty2,
           mbps_ask3 = v_mbps_ask3,
           mbps_ask_qty3 = v_mbps_ask_qty3,
           mbps_ask4 = v_mbps_ask4,
           mbps_ask_qty4 = v_mbps_ask_qty4,
           mbps_ask5 = v_mbps_ask5,
           mbps_ask_qty5 = v_mbps_ask_qty5,
           mbps_ask6 = v_mbps_ask6,
           mbps_ask_qty6 = v_mbps_ask_qty6,
           mbps_ask7 = v_mbps_ask7,
           mbps_ask_qty7 = v_mbps_ask_qty7,
           mbps_ask8 = v_mbps_ask8,
           mbps_ask_qty8 = v_mbps_ask_qty8,
           mbps_ask9 = v_mbps_ask9,
           mbps_ask_qty9 = v_mbps_ask_qty9,
           mbps_ask10 = v_mbps_ask10,
           mbps_ask_qty10 = v_mbps_ask_qty10,
           last_updated =
               CASE
                   WHEN mbps_bid_qty1 = v_mbps_bid_qty1 THEN last_updated
                   ELSE SYSDATE
               END
     WHERE exchangecode = v_exchangecode AND symbol = v_symbol;

    IF (SQL%ROWCOUNT = 0)
    THEN
        INSERT INTO esp_marketdepth (exchangecode,
                                     symbol,
                                     mbps_bid1,
                                     mbps_bid_qty1,
                                     mbps_bid2,
                                     mbps_bid_qty2,
                                     mbps_bid3,
                                     mbps_bid_qty3,
                                     mbps_bid4,
                                     mbps_bid_qty4,
                                     mbps_bid5,
                                     mbps_bid_qty5,
                                     mbps_bid6,
                                     mbps_bid_qty6,
                                     mbps_bid7,
                                     mbps_bid_qty7,
                                     mbps_bid8,
                                     mbps_bid_qty8,
                                     mbps_bid9,
                                     mbps_bid_qty9,
                                     mbps_bid10,
                                     mbps_bid_qty10,
                                     mbps_ask1,
                                     mbps_ask_qty1,
                                     mbps_ask2,
                                     mbps_ask_qty2,
                                     mbps_ask3,
                                     mbps_ask_qty3,
                                     mbps_ask4,
                                     mbps_ask_qty4,
                                     mbps_ask5,
                                     mbps_ask_qty5,
                                     mbps_ask6,
                                     mbps_ask_qty6,
                                     mbps_ask7,
                                     mbps_ask_qty7,
                                     mbps_ask8,
                                     mbps_ask_qty8,
                                     mbps_ask9,
                                     mbps_ask_qty9,
                                     mbps_ask10,
                                     mbps_ask_qty10,
                                     last_updated)
             VALUES (v_exchangecode,
                     v_symbol,
                     v_mbps_bid1,
                     v_mbps_bid_qty1,
                     v_mbps_bid2,
                     v_mbps_bid_qty2,
                     v_mbps_bid3,
                     v_mbps_bid_qty3,
                     v_mbps_bid4,
                     v_mbps_bid_qty4,
                     v_mbps_bid5,
                     v_mbps_bid_qty5,
                     v_mbps_bid6,
                     v_mbps_bid_qty6,
                     v_mbps_bid7,
                     v_mbps_bid_qty7,
                     v_mbps_bid8,
                     v_mbps_bid_qty8,
                     v_mbps_bid9,
                     v_mbps_bid_qty9,
                     v_mbps_bid10,
                     v_mbps_bid_qty10,
                     v_mbps_ask1,
                     v_mbps_ask_qty1,
                     v_mbps_ask2,
                     v_mbps_ask_qty2,
                     v_mbps_ask3,
                     v_mbps_ask_qty3,
                     v_mbps_ask4,
                     v_mbps_ask_qty4,
                     v_mbps_ask5,
                     v_mbps_ask_qty5,
                     v_mbps_ask6,
                     v_mbps_ask_qty6,
                     v_mbps_ask7,
                     v_mbps_ask_qty7,
                     v_mbps_ask8,
                     v_mbps_ask_qty8,
                     v_mbps_ask9,
                     v_mbps_ask_qty9,
                     v_mbps_ask10,
                     v_mbps_ask_qty10,
                     SYSDATE);
    END IF;
END;
/
/
