
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_EOD_MASTER_DATA (
    v_exchangeid              IN VARCHAR2,
    v_symbol                  IN VARCHAR2,
    v_exchangename            IN VARCHAR2,
    v_localcode               IN VARCHAR2 DEFAULT NULL,
    v_tradingcode             IN VARCHAR2 DEFAULT NULL,
    v_sedol                   IN VARCHAR2 DEFAULT NULL,
    v_isin                    IN VARCHAR2 DEFAULT NULL,
    v_description             IN VARCHAR2 DEFAULT NULL,
    v_undexchange             IN VARCHAR2 DEFAULT NULL,
    v_undsymbol               IN VARCHAR2 DEFAULT NULL,
    v_lowspeedsymbol          IN VARCHAR2 DEFAULT NULL,
    v_indexmembership         IN VARCHAR2 DEFAULT NULL,
    v_status                  IN VARCHAR2 DEFAULT NULL,
    v_primaryexchange         IN VARCHAR2 DEFAULT NULL,
    v_submarket               IN VARCHAR2 DEFAULT NULL,
    v_localinsttype           IN VARCHAR2 DEFAULT NULL,
    v_localindsector          IN VARCHAR2 DEFAULT NULL,
    v_contractunit            IN NUMBER DEFAULT NULL,
    v_contractsize            IN NUMBER DEFAULT NULL,
    v_submarketcode           IN VARCHAR2 DEFAULT NULL,
    v_submarketdescription    IN VARCHAR2 DEFAULT NULL,
    v_contractdescription     IN VARCHAR2 DEFAULT NULL,
    v_instrumentdescription   IN VARCHAR2 DEFAULT NULL,
    v_miccode                 IN VARCHAR2 DEFAULT NULL,
    v_tradeexchangename       IN VARCHAR2 DEFAULT NULL)
AS
BEGIN
    UPDATE eod_snapshot
       SET ex_name = v_exchangename,
           local_code = v_localcode,
           trading_code = v_tradingcode,
           sedol = v_sedol,
           isin = v_isin,
           description = v_description,
           underlying_exchid = v_undexchange,
           underlying_symbol = v_undsymbol,
           lowspeedsymbol = v_lowspeedsymbol,
           index_membership = v_indexmembership,
           status = v_status,
           primary_exch = v_primaryexchange,
           submarket = v_submarket,
           localinsttype = v_localinsttype,
           localindsector = v_localindsector,
           contract_units = v_contractunit,
           contract_size = v_contractsize,
           submarketcode = v_submarketcode,
           submarketdesc = v_submarketdescription,
           contractdesc = v_contractdescription,
           instrumentdesc = v_instrumentdescription,
           miccode = v_miccode,
           trade_ex_name = v_tradeexchangename
     WHERE (exid = v_exchangeid AND symbol = v_symbol);

    IF (SQL%ROWCOUNT = 0)
    THEN
        BEGIN
            INSERT INTO eod_snapshot (exid,
                                      symbol,
                                      ex_name,
                                      local_code,
                                      trading_code,
                                      sedol,
                                      isin,
                                      description,
                                      underlying_exchid,
                                      underlying_symbol,
                                      lowspeedsymbol,
                                      index_membership,
                                      status,
                                      primary_exch,
                                      submarket,
                                      localinsttype,
                                      localindsector,
                                      contract_units,
                                      contract_size,
                                      submarketcode,
                                      submarketdesc,
                                      contractdesc,
                                      instrumentdesc,
                                      miccode,
                                      trade_ex_name)
                 VALUES (v_exchangeid,
                         v_symbol,
                         v_exchangename,
                         v_localcode,
                         v_tradingcode,
                         v_sedol,
                         v_isin,
                         v_description,
                         v_undexchange,
                         v_undsymbol,
                         v_lowspeedsymbol,
                         v_indexmembership,
                         v_status,
                         v_primaryexchange,
                         v_submarket,
                         v_localinsttype,
                         v_localindsector,
                         v_contractunit,
                         v_contractsize,
                         v_submarketcode,
                         v_submarketdescription,
                         v_contractdescription,
                         v_instrumentdescription,
                         v_miccode,
                         v_tradeexchangename);
        END;
    END IF;

    COMMIT;
END;
/
/
