
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_INS_UPD_PERIODIC_INDICATORS (
    v_exchangecode           IN VARCHAR2,
    v_symbol                 IN VARCHAR2,
    v_isendofday             IN NUMBER DEFAULT NULL,
    v_periodstart            IN DATE DEFAULT NULL,
    v_periodstop             IN DATE DEFAULT NULL,
    v_twaspread              IN NUMBER DEFAULT NULL,
    v_rtwaspread             IN NUMBER DEFAULT NULL,
    v_twabestbid             IN NUMBER DEFAULT NULL,
    v_twabestask             IN NUMBER DEFAULT NULL,
    v_tvwaquotation          IN NUMBER DEFAULT NULL,
    v_twbestaskvolume        IN NUMBER DEFAULT NULL,
    v_twbestaskvalue         IN NUMBER DEFAULT NULL,
    v_twnobestask            IN NUMBER DEFAULT NULL,
    v_twvolumeaskside        IN NUMBER DEFAULT NULL,
    v_twvalueaskside         IN NUMBER DEFAULT NULL,
    v_twnoaskside            IN NUMBER DEFAULT NULL,
    v_twbestbidvolume        IN NUMBER DEFAULT NULL,
    v_twbestbidvalue         IN NUMBER DEFAULT NULL,
    v_twnobestbid            IN NUMBER DEFAULT NULL,
    v_twvolumebidside        IN NUMBER DEFAULT NULL,
    v_twvaluebidside         IN NUMBER DEFAULT NULL,
    v_twnobidside            IN NUMBER DEFAULT NULL,
    v_twmidpointvolume       IN NUMBER DEFAULT NULL,
    v_twmidpointvalue        IN NUMBER DEFAULT NULL,
    v_twnomidpoint           IN NUMBER DEFAULT NULL,
    v_twtvolumemidpoint      IN NUMBER DEFAULT NULL,
    v_twtvaluemidpoint       IN NUMBER DEFAULT NULL,
    v_twtomidpoint           IN NUMBER DEFAULT NULL,
    v_totalordercoverage     IN NUMBER DEFAULT NULL,
    v_bidordercoverage       IN NUMBER DEFAULT NULL,
    v_askordercoverage       IN NUMBER DEFAULT NULL,
    v_bevwapbidside          IN NUMBER DEFAULT NULL,
    v_bevwapaskside          IN NUMBER DEFAULT NULL,
    v_twtvolumebidside       IN NUMBER DEFAULT NULL,
    v_twtvolumeaskside       IN NUMBER DEFAULT NULL,
    v_twbaindicatorbest      IN NUMBER DEFAULT NULL,
    v_twbaindicatorall       IN NUMBER DEFAULT NULL,
    v_twcindicatorbidside    IN NUMBER DEFAULT NULL,
    v_twcindicatoraskside    IN NUMBER DEFAULT NULL,
    v_localrtclasses         IN VARCHAR2 DEFAULT NULL,
    v_localrtcosts           IN VARCHAR2 DEFAULT NULL,
    v_localrtcoverages       IN VARCHAR2 DEFAULT NULL,
    v_referancertclasses     IN VARCHAR2 DEFAULT NULL,
    v_referancertcosts       IN VARCHAR2 DEFAULT NULL,
    v_referancertcoverages   IN VARCHAR2 DEFAULT NULL)
AS
BEGIN
    UPDATE esp_periodic_indicators
       SET lastupdatedtime = SYSDATE,
           isendofday = v_isendofday,
           periodstart = v_periodstart,
           periodstop = v_periodstop,
           twaspread = v_twaspread,
           rtwaspread = v_rtwaspread,
           twabestbid = v_twabestbid,
           twabestask = v_twabestask,
           tvwaquotation = v_tvwaquotation,
           twbestaskvolume = v_twbestaskvolume,
           twbestaskvalue = v_twbestaskvalue,
           twnobestask = v_twnobestask,
           twvolumeaskside = v_twvolumeaskside,
           twvalueaskside = v_twvalueaskside,
           twnoaskside = v_twnoaskside,
           twbestbidvolume = v_twbestbidvolume,
           twbestbidvalue = v_twbestbidvalue,
           twnobestbid = v_twnobestbid,
           twvolumebidside = v_twvolumebidside,
           twvaluebidside = v_twvaluebidside,
           twnobidside = v_twnobidside,
           twmidpointvolume = v_twmidpointvolume,
           twmidpointvalue = v_twmidpointvalue,
           twnomidpoint = v_twnomidpoint,
           twtvolumemidpoint = v_twtvolumemidpoint,
           twtvaluemidpoint = v_twtvaluemidpoint,
           twtomidpoint = v_twtomidpoint,
           totalordercoverage = v_totalordercoverage,
           bidordercoverage = v_bidordercoverage,
           askordercoverage = v_askordercoverage,
           bevwapbidside = v_bevwapbidside,
           bevwapaskside = v_bevwapaskside,
           twtvolumebidside = v_twtvolumebidside,
           twtvolumeaskside = v_twtvolumeaskside,
           twbaindicatorbest = v_twbaindicatorbest,
           twbaindicatorall = v_twbaindicatorall,
           twcindicatorbidside = v_twcindicatorbidside,
           twcindicatoraskside = v_twcindicatoraskside,
           localrtclasses = v_localrtclasses,
           localrtcosts = v_localrtcosts,
           localrtcoverages = v_localrtcoverages,
           referancertclasses = v_referancertclasses,
           referancertcosts = v_referancertcosts,
           referancertcoverages = v_referancertcoverages
     WHERE exchangecode = v_exchangecode AND symbol = v_symbol;

    IF (SQL%ROWCOUNT = 0)
    THEN
        BEGIN
            INSERT INTO esp_periodic_indicators (exchangecode,
                                                 symbol,
                                                 lastupdatedtime,
                                                 isendofday,
                                                 periodstart,
                                                 periodstop,
                                                 twaspread,
                                                 rtwaspread,
                                                 twabestbid,
                                                 twabestask,
                                                 twvolumeaskside,
                                                 twvalueaskside,
                                                 twnoaskside,
                                                 tvwaquotation,
                                                 twbestaskvolume,
                                                 twbestaskvalue,
                                                 twnobestask,
                                                 twbestbidvolume,
                                                 twbestbidvalue,
                                                 twnobestbid,
                                                 twvolumebidside,
                                                 twvaluebidside,
                                                 twnobidside,
                                                 twmidpointvolume,
                                                 twmidpointvalue,
                                                 twnomidpoint,
                                                 twtvolumemidpoint,
                                                 twtvaluemidpoint,
                                                 twtomidpoint,
                                                 totalordercoverage,
                                                 bidordercoverage,
                                                 askordercoverage,
                                                 bevwapbidside,
                                                 bevwapaskside,
                                                 twtvolumebidside,
                                                 twtvolumeaskside,
                                                 twbaindicatorbest,
                                                 twbaindicatorall,
                                                 twcindicatorbidside,
                                                 twcindicatoraskside,
                                                 localrtclasses,
                                                 localrtcosts,
                                                 localrtcoverages,
                                                 referancertclasses,
                                                 referancertcosts,
                                                 referancertcoverages)
                 VALUES (v_exchangecode,
                         v_symbol,
                         SYSDATE,
                         v_isendofday,
                         v_periodstart,
                         v_periodstop,
                         v_twaspread,
                         v_rtwaspread,
                         v_twabestbid,
                         v_twabestask,
                         v_twvolumeaskside,
                         v_twvalueaskside,
                         v_twnoaskside,
                         v_tvwaquotation,
                         v_twbestaskvolume,
                         v_twbestaskvalue,
                         v_twnobestask,
                         v_twbestbidvolume,
                         v_twbestbidvalue,
                         v_twnobestbid,
                         v_twvolumebidside,
                         v_twvaluebidside,
                         v_twnobidside,
                         v_twmidpointvolume,
                         v_twmidpointvalue,
                         v_twnomidpoint,
                         v_twtvolumemidpoint,
                         v_twtvaluemidpoint,
                         v_twtomidpoint,
                         v_totalordercoverage,
                         v_bidordercoverage,
                         v_askordercoverage,
                         v_bevwapbidside,
                         v_bevwapaskside,
                         v_twtvolumebidside,
                         v_twtvolumeaskside,
                         v_twbaindicatorbest,
                         v_twbaindicatorall,
                         v_twcindicatorbidside,
                         v_twcindicatoraskside,
                         v_localrtclasses,
                         v_localrtcosts,
                         v_localrtcoverages,
                         v_referancertclasses,
                         v_referancertcosts,
                         v_referancertcoverages);
        END;
    END IF;

    COMMIT;
END;
/
/
