
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_EOD_PRICE_DATA (
    vv_exchangeid          IN VARCHAR2,
    vv_symbol              IN VARCHAR2,
    vv_exchangename        IN VARCHAR2,
    vv_precisionin         IN VARCHAR2,
    vv_companyname         IN VARCHAR2 DEFAULT NULL,
    vv_lastprice           IN NUMBER DEFAULT NULL,
    vv_openprice           IN NUMBER DEFAULT NULL,
    vv_highprice           IN NUMBER DEFAULT NULL,
    vv_lowprice            IN NUMBER DEFAULT NULL,
    vv_cummvolume          IN NUMBER DEFAULT NULL,
    vv_yesterclose         IN NUMBER DEFAULT NULL,
    vv_settle              IN NUMBER DEFAULT NULL,
    vv_yestervolume        IN NUMBER DEFAULT NULL,
    vv_openinterest        IN NUMBER DEFAULT NULL,
    vv_strikeprice         IN NUMBER DEFAULT NULL,
    vv_strikepricediv      IN VARCHAR2,
    vv_activitydate        IN DATE DEFAULT NULL,
    vv_currencycode        IN VARCHAR2 DEFAULT NULL,
    vv_bidprice            IN NUMBER DEFAULT NULL,
    vv_bidhighprice        IN NUMBER DEFAULT NULL,
    vv_bidlowprice         IN NUMBER DEFAULT NULL,
    vv_askprice            IN NUMBER DEFAULT NULL,
    vv_tradedate           IN DATE DEFAULT NULL,
    vv_expirdate           IN DATE DEFAULT NULL,
    vv_pretradedate        IN DATE DEFAULT NULL,
    vv_tradeexchangename   IN VARCHAR2 DEFAULT NULL)
AS
BEGIN
    UPDATE eod_snapshot
       SET ex_name = vv_exchangename,
           pre_ind = vv_precisionin,
           company_name = vv_companyname,
           last_price = vv_lastprice,
           open_price = vv_openprice,
           high_price = vv_highprice,
           low_price = vv_lowprice,
           cumm_volume = vv_cummvolume,
           yesterday_close = vv_yesterclose,
           settle = vv_settle,
           yesterday_volume = vv_yestervolume,
           open_int = vv_openinterest,
           strike_price = vv_strikeprice,
           strike_price_div = vv_strikepricediv,
           activity_date = vv_activitydate,
           currency_code = vv_currencycode,
           bid_price = vv_bidprice,
           bid_high_price = vv_bidhighprice,
           bid_low_price = vv_bidlowprice,
           ask_price = vv_askprice,
           trade_date = vv_tradedate,
           exp_date = vv_expirdate,
           prev_trade_date = vv_pretradedate,
           trade_ex_name = vv_tradeexchangename
     WHERE exid = vv_exchangeid AND symbol = vv_symbol;

    IF (SQL%ROWCOUNT = 0)
    THEN
        BEGIN
            INSERT INTO eod_snapshot (exid,
                                      symbol,
                                      ex_name,
                                      pre_ind,
                                      company_name,
                                      last_price,
                                      open_price,
                                      high_price,
                                      low_price,
                                      cumm_volume,
                                      yesterday_close,
                                      settle,
                                      yesterday_volume,
                                      open_int,
                                      strike_price,
                                      strike_price_div,
                                      activity_date,
                                      currency_code,
                                      bid_price,
                                      bid_high_price,
                                      bid_low_price,
                                      ask_price,
                                      trade_date,
                                      exp_date,
                                      prev_trade_date,
                                      trade_ex_name)
                 VALUES (vv_exchangeid,
                         vv_symbol,
                         vv_exchangename,
                         vv_precisionin,
                         vv_companyname,
                         vv_lastprice,
                         vv_openprice,
                         vv_highprice,
                         vv_lowprice,
                         vv_cummvolume,
                         vv_yesterclose,
                         vv_settle,
                         vv_yestervolume,
                         vv_openinterest,
                         vv_strikeprice,
                         vv_strikepricediv,
                         vv_activitydate,
                         vv_currencycode,
                         vv_bidprice,
                         vv_bidhighprice,
                         vv_bidlowprice,
                         vv_askprice,
                         vv_tradedate,
                         vv_expirdate,
                         vv_pretradedate,
                         vv_tradeexchangename);
        END;
    END IF;

    COMMIT;
END;
/
/
