
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_INS_UPD_MKT_DEPTH_MBO (
    v_exchangecode    IN esp_marketdepth.exchangecode%TYPE,
    v_symbol          IN esp_marketdepth.symbol%TYPE,
    v_mbo_bid1        IN esp_marketdepth.mbo_bid1%TYPE,
    v_mbo_bid_qty1    IN esp_marketdepth.mbo_bid_qty1%TYPE,
    v_mbo_bid2        IN esp_marketdepth.mbo_bid2%TYPE,
    v_mbo_bid_qty2    IN esp_marketdepth.mbo_bid_qty2%TYPE,
    v_mbo_bid3        IN esp_marketdepth.mbo_bid3%TYPE,
    v_mbo_bid_qty3    IN esp_marketdepth.mbo_bid_qty3%TYPE,
    v_mbo_bid4        IN esp_marketdepth.mbo_bid4%TYPE,
    v_mbo_bid_qty4    IN esp_marketdepth.mbo_bid_qty4%TYPE,
    v_mbo_bid5        IN esp_marketdepth.mbo_bid5%TYPE,
    v_mbo_bid_qty5    IN esp_marketdepth.mbo_bid_qty5%TYPE,
    v_mbo_bid6        IN esp_marketdepth.mbo_bid6%TYPE,
    v_mbo_bid_qty6    IN esp_marketdepth.mbo_bid_qty6%TYPE,
    v_mbo_bid7        IN esp_marketdepth.mbo_bid7%TYPE,
    v_mbo_bid_qty7    IN esp_marketdepth.mbo_bid_qty7%TYPE,
    v_mbo_bid8        IN esp_marketdepth.mbo_bid8%TYPE,
    v_mbo_bid_qty8    IN esp_marketdepth.mbo_bid_qty8%TYPE,
    v_mbo_bid9        IN esp_marketdepth.mbo_bid9%TYPE,
    v_mbo_bid_qty9    IN esp_marketdepth.mbo_bid_qty9%TYPE,
    v_mbo_bid10       IN esp_marketdepth.mbo_bid10%TYPE,
    v_mbo_bid_qty10   IN esp_marketdepth.mbo_bid_qty10%TYPE,
	v_mbo_bid11        IN esp_marketdepth.mbo_bid11%TYPE,
    v_mbo_bid_qty11    IN esp_marketdepth.mbo_bid_qty11%TYPE,
    v_mbo_bid12        IN esp_marketdepth.mbo_bid12%TYPE,
    v_mbo_bid_qty12    IN esp_marketdepth.mbo_bid_qty12%TYPE,
    v_mbo_bid13        IN esp_marketdepth.mbo_bid13%TYPE,
    v_mbo_bid_qty13    IN esp_marketdepth.mbo_bid_qty13%TYPE,
    v_mbo_bid14        IN esp_marketdepth.mbo_bid14%TYPE,
    v_mbo_bid_qty14    IN esp_marketdepth.mbo_bid_qty14%TYPE,
    v_mbo_bid15        IN esp_marketdepth.mbo_bid15%TYPE,
    v_mbo_bid_qty15    IN esp_marketdepth.mbo_bid_qty15%TYPE,
    v_mbo_bid16        IN esp_marketdepth.mbo_bid16%TYPE,
    v_mbo_bid_qty16    IN esp_marketdepth.mbo_bid_qty16%TYPE,
    v_mbo_bid17        IN esp_marketdepth.mbo_bid17%TYPE,
    v_mbo_bid_qty17    IN esp_marketdepth.mbo_bid_qty17%TYPE,
    v_mbo_bid18        IN esp_marketdepth.mbo_bid18%TYPE,
    v_mbo_bid_qty18    IN esp_marketdepth.mbo_bid_qty18%TYPE,
    v_mbo_bid19        IN esp_marketdepth.mbo_bid19%TYPE,
    v_mbo_bid_qty19    IN esp_marketdepth.mbo_bid_qty19%TYPE,
    v_mbo_bid20       IN esp_marketdepth.mbo_bid20%TYPE,
    v_mbo_bid_qty20   IN esp_marketdepth.mbo_bid_qty20%TYPE,
    v_mbo_ask1        IN esp_marketdepth.mbo_ask1%TYPE,
    v_mbo_ask_qty1    IN esp_marketdepth.mbo_ask_qty1%TYPE,
    v_mbo_ask2        IN esp_marketdepth.mbo_ask2%TYPE,
    v_mbo_ask_qty2    IN esp_marketdepth.mbo_ask_qty2%TYPE,
    v_mbo_ask3        IN esp_marketdepth.mbo_ask3%TYPE,
    v_mbo_ask_qty3    IN esp_marketdepth.mbo_ask_qty3%TYPE,
    v_mbo_ask4        IN esp_marketdepth.mbo_ask4%TYPE,
    v_mbo_ask_qty4    IN esp_marketdepth.mbo_ask_qty4%TYPE,
    v_mbo_ask5        IN esp_marketdepth.mbo_ask5%TYPE,
    v_mbo_ask_qty5    IN esp_marketdepth.mbo_ask_qty5%TYPE,
    v_mbo_ask6        IN esp_marketdepth.mbo_ask6%TYPE,
    v_mbo_ask_qty6    IN esp_marketdepth.mbo_ask_qty6%TYPE,
    v_mbo_ask7        IN esp_marketdepth.mbo_ask7%TYPE,
    v_mbo_ask_qty7    IN esp_marketdepth.mbo_ask_qty7%TYPE,
    v_mbo_ask8        IN esp_marketdepth.mbo_ask8%TYPE,
    v_mbo_ask_qty8    IN esp_marketdepth.mbo_ask_qty8%TYPE,
    v_mbo_ask9        IN esp_marketdepth.mbo_ask9%TYPE,
    v_mbo_ask_qty9    IN esp_marketdepth.mbo_ask_qty9%TYPE,
    v_mbo_ask10       IN esp_marketdepth.mbo_ask10%TYPE,
    v_mbo_ask_qty10   IN esp_marketdepth.mbo_ask_qty10%TYPE,
    v_mbo_ask11        IN esp_marketdepth.mbo_ask11%TYPE,
    v_mbo_ask_qty11    IN esp_marketdepth.mbo_ask_qty11%TYPE,
    v_mbo_ask12        IN esp_marketdepth.mbo_ask12%TYPE,
    v_mbo_ask_qty12    IN esp_marketdepth.mbo_ask_qty12%TYPE,
    v_mbo_ask13        IN esp_marketdepth.mbo_ask13%TYPE,
    v_mbo_ask_qty13    IN esp_marketdepth.mbo_ask_qty13%TYPE,
    v_mbo_ask14        IN esp_marketdepth.mbo_ask14%TYPE,
    v_mbo_ask_qty14    IN esp_marketdepth.mbo_ask_qty14%TYPE,
    v_mbo_ask15        IN esp_marketdepth.mbo_ask15%TYPE,
    v_mbo_ask_qty15    IN esp_marketdepth.mbo_ask_qty15%TYPE,
    v_mbo_ask16        IN esp_marketdepth.mbo_ask16%TYPE,
    v_mbo_ask_qty16    IN esp_marketdepth.mbo_ask_qty16%TYPE,
    v_mbo_ask17        IN esp_marketdepth.mbo_ask17%TYPE,
    v_mbo_ask_qty17    IN esp_marketdepth.mbo_ask_qty17%TYPE,
    v_mbo_ask18        IN esp_marketdepth.mbo_ask18%TYPE,
    v_mbo_ask_qty18    IN esp_marketdepth.mbo_ask_qty18%TYPE,
    v_mbo_ask19        IN esp_marketdepth.mbo_ask19%TYPE,
    v_mbo_ask_qty19    IN esp_marketdepth.mbo_ask_qty19%TYPE,
    v_mbo_ask20       IN esp_marketdepth.mbo_ask20%TYPE,
    v_mbo_ask_qty20   IN esp_marketdepth.mbo_ask_qty20%TYPE)
	
AS
BEGIN
    UPDATE esp_marketdepth
       SET mbo_bid1 = v_mbo_bid1,
           mbo_bid_qty1 = v_mbo_bid_qty1,
           mbo_bid2 = v_mbo_bid2,
           mbo_bid_qty2 = v_mbo_bid_qty2,
           mbo_bid3 = v_mbo_bid3,
           mbo_bid_qty3 = v_mbo_bid_qty3,
           mbo_bid4 = v_mbo_bid4,
           mbo_bid_qty4 = v_mbo_bid_qty4,
           mbo_bid5 = v_mbo_bid5,
           mbo_bid_qty5 = v_mbo_bid_qty5,
           mbo_bid6 = v_mbo_bid6,
           mbo_bid_qty6 = v_mbo_bid_qty6,
           mbo_bid7 = v_mbo_bid7,
           mbo_bid_qty7 = v_mbo_bid_qty7,
           mbo_bid8 = v_mbo_bid8,
           mbo_bid_qty8 = v_mbo_bid_qty8,
           mbo_bid9 = v_mbo_bid9,
           mbo_bid_qty9 = v_mbo_bid_qty9,
           mbo_bid10 = v_mbo_bid10,
           mbo_bid_qty10 = v_mbo_bid_qty10,
		   mbo_bid11 = v_mbo_bid11,
           mbo_bid_qty11 = v_mbo_bid_qty11,
           mbo_bid12 = v_mbo_bid12,
           mbo_bid_qty12 = v_mbo_bid_qty12,
           mbo_bid13 = v_mbo_bid13,
           mbo_bid_qty13 = v_mbo_bid_qty13,
           mbo_bid14 = v_mbo_bid14,
           mbo_bid_qty14 = v_mbo_bid_qty14,
           mbo_bid15 = v_mbo_bid15,
           mbo_bid_qty15 = v_mbo_bid_qty15,
           mbo_bid16 = v_mbo_bid16,
           mbo_bid_qty16 = v_mbo_bid_qty16,
           mbo_bid17 = v_mbo_bid17,
           mbo_bid_qty17 = v_mbo_bid_qty17,
           mbo_bid18 = v_mbo_bid18,
           mbo_bid_qty18 = v_mbo_bid_qty18,
           mbo_bid19 = v_mbo_bid19,
           mbo_bid_qty19 = v_mbo_bid_qty19,
           mbo_bid20 = v_mbo_bid20,
           mbo_bid_qty20 = v_mbo_bid_qty20,
           mbo_ask1 = v_mbo_ask1,
           mbo_ask_qty1 = v_mbo_ask_qty1,
           mbo_ask2 = v_mbo_ask2,
           mbo_ask_qty2 = v_mbo_ask_qty2,
           mbo_ask3 = v_mbo_ask3,
           mbo_ask_qty3 = v_mbo_ask_qty3,
           mbo_ask4 = v_mbo_ask4,
           mbo_ask_qty4 = v_mbo_ask_qty4,
           mbo_ask5 = v_mbo_ask5,
           mbo_ask_qty5 = v_mbo_ask_qty5,
           mbo_ask6 = v_mbo_ask6,
           mbo_ask_qty6 = v_mbo_ask_qty6,
           mbo_ask7 = v_mbo_ask7,
           mbo_ask_qty7 = v_mbo_ask_qty7,
           mbo_ask8 = v_mbo_ask8,
           mbo_ask_qty8 = v_mbo_ask_qty8,
           mbo_ask9 = v_mbo_ask9,
           mbo_ask_qty9 = v_mbo_ask_qty9,
           mbo_ask10 = v_mbo_ask10,
           mbo_ask_qty10 = v_mbo_ask_qty10,
           mbo_ask11 = v_mbo_ask11,
           mbo_ask_qty11 = v_mbo_ask_qty11,
           mbo_ask12 = v_mbo_ask12,
           mbo_ask_qty12 = v_mbo_ask_qty12,
           mbo_ask13 = v_mbo_ask13,
           mbo_ask_qty13 = v_mbo_ask_qty13,
           mbo_ask14 = v_mbo_ask14,
           mbo_ask_qty14 = v_mbo_ask_qty14,
           mbo_ask15 = v_mbo_ask15,
           mbo_ask_qty15 = v_mbo_ask_qty15,
           mbo_ask16 = v_mbo_ask16,
           mbo_ask_qty16 = v_mbo_ask_qty16,
           mbo_ask17 = v_mbo_ask17,
           mbo_ask_qty17 = v_mbo_ask_qty17,
           mbo_ask18 = v_mbo_ask18,
           mbo_ask_qty18 = v_mbo_ask_qty18,
           mbo_ask19 = v_mbo_ask19,
           mbo_ask_qty19 = v_mbo_ask_qty19,
           mbo_ask20 = v_mbo_ask20,
           mbo_ask_qty20 = v_mbo_ask_qty20,
           last_updated =
               CASE
                   WHEN mbo_bid_qty1 = v_mbo_bid_qty1 THEN last_updated
                   ELSE SYSDATE
               END
     WHERE exchangecode = v_exchangecode AND symbol = v_symbol;

    IF (SQL%ROWCOUNT = 0)
    THEN
        INSERT INTO esp_marketdepth (exchangecode,
                                     symbol,
                                     mbo_bid1,
                                     mbo_bid_qty1,
                                     mbo_bid2,
                                     mbo_bid_qty2,
                                     mbo_bid3,
                                     mbo_bid_qty3,
                                     mbo_bid4,
                                     mbo_bid_qty4,
                                     mbo_bid5,
                                     mbo_bid_qty5,
                                     mbo_bid6,
                                     mbo_bid_qty6,
                                     mbo_bid7,
                                     mbo_bid_qty7,
                                     mbo_bid8,
                                     mbo_bid_qty8,
                                     mbo_bid9,
                                     mbo_bid_qty9,
                                     mbo_bid10,
                                     mbo_bid_qty10,
									 mbo_bid11,
                                     mbo_bid_qty11,
                                     mbo_bid12,
                                     mbo_bid_qty12,
                                     mbo_bid13,
                                     mbo_bid_qty13,
                                     mbo_bid14,
                                     mbo_bid_qty14,
                                     mbo_bid15,
                                     mbo_bid_qty15,
                                     mbo_bid16,
                                     mbo_bid_qty16,
                                     mbo_bid17,
                                     mbo_bid_qty17,
                                     mbo_bid18,
                                     mbo_bid_qty18,
                                     mbo_bid19,
                                     mbo_bid_qty19,
                                     mbo_bid20,
                                     mbo_bid_qty20,
                                     mbo_ask1,
                                     mbo_ask_qty1,
                                     mbo_ask2,
                                     mbo_ask_qty2,
                                     mbo_ask3,
                                     mbo_ask_qty3,
                                     mbo_ask4,
                                     mbo_ask_qty4,
                                     mbo_ask5,
                                     mbo_ask_qty5,
                                     mbo_ask6,
                                     mbo_ask_qty6,
                                     mbo_ask7,
                                     mbo_ask_qty7,
                                     mbo_ask8,
                                     mbo_ask_qty8,
                                     mbo_ask9,
                                     mbo_ask_qty9,
                                     mbo_ask10,
                                     mbo_ask_qty10,									 
                                     mbo_ask11,
                                     mbo_ask_qty11,
                                     mbo_ask12,
                                     mbo_ask_qty12,
                                     mbo_ask13,
                                     mbo_ask_qty13,
                                     mbo_ask14,
                                     mbo_ask_qty14,
                                     mbo_ask15,
                                     mbo_ask_qty15,
                                     mbo_ask16,
                                     mbo_ask_qty16,
                                     mbo_ask17,
                                     mbo_ask_qty17,
                                     mbo_ask18,
                                     mbo_ask_qty18,
                                     mbo_ask19,
                                     mbo_ask_qty19,
                                     mbo_ask20,
                                     mbo_ask_qty20,
                                     last_updated)
             VALUES (v_exchangecode,
                     v_symbol,
                     v_mbo_bid1,
                     v_mbo_bid_qty1,
                     v_mbo_bid2,
                     v_mbo_bid_qty2,
                     v_mbo_bid3,
                     v_mbo_bid_qty3,
                     v_mbo_bid4,
                     v_mbo_bid_qty4,
                     v_mbo_bid5,
                     v_mbo_bid_qty5,
                     v_mbo_bid6,
                     v_mbo_bid_qty6,
                     v_mbo_bid7,
                     v_mbo_bid_qty7,
                     v_mbo_bid8,
                     v_mbo_bid_qty8,
                     v_mbo_bid9,
                     v_mbo_bid_qty9,
                     v_mbo_bid10,
                     v_mbo_bid_qty10,
					 v_mbo_bid11,
                     v_mbo_bid_qty11,
                     v_mbo_bid12,
                     v_mbo_bid_qty12,
                     v_mbo_bid13,
                     v_mbo_bid_qty13,
                     v_mbo_bid14,
                     v_mbo_bid_qty14,
                     v_mbo_bid15,
                     v_mbo_bid_qty15,
                     v_mbo_bid16,
                     v_mbo_bid_qty16,
                     v_mbo_bid17,
                     v_mbo_bid_qty17,
                     v_mbo_bid18,
                     v_mbo_bid_qty18,
                     v_mbo_bid19,
                     v_mbo_bid_qty19,
                     v_mbo_bid20,
                     v_mbo_bid_qty20,
                     v_mbo_ask1,
                     v_mbo_ask_qty1,
                     v_mbo_ask2,
                     v_mbo_ask_qty2,
                     v_mbo_ask3,
                     v_mbo_ask_qty3,
                     v_mbo_ask4,
                     v_mbo_ask_qty4,
                     v_mbo_ask5,
                     v_mbo_ask_qty5,
                     v_mbo_ask6,
                     v_mbo_ask_qty6,
                     v_mbo_ask7,
                     v_mbo_ask_qty7,
                     v_mbo_ask8,
                     v_mbo_ask_qty8,
                     v_mbo_ask9,
                     v_mbo_ask_qty9,
                     v_mbo_ask10,
                     v_mbo_ask_qty10,
                     v_mbo_ask11,
                     v_mbo_ask_qty11,
                     v_mbo_ask12,
                     v_mbo_ask_qty12,
                     v_mbo_ask13,
                     v_mbo_ask_qty13,
                     v_mbo_ask14,
                     v_mbo_ask_qty14,
                     v_mbo_ask15,
                     v_mbo_ask_qty15,
                     v_mbo_ask16,
                     v_mbo_ask_qty16,
                     v_mbo_ask17,
                     v_mbo_ask_qty17,
                     v_mbo_ask18,
                     v_mbo_ask_qty18,
                     v_mbo_ask19,
                     v_mbo_ask_qty19,
                     v_mbo_ask20,
                     v_mbo_ask_qty20,
                     SYSDATE);
    END IF;
END;
/
/
