
CREATE OR REPLACE PROCEDURE DFN_PRICE.SP_INS_UPD_MKT_DEPTH_MBP (
    v_exchangecode       IN esp_marketdepth.exchangecode%TYPE,
    v_symbol             IN esp_marketdepth.symbol%TYPE,
    v_mbp_bid1           IN esp_marketdepth.mbp_bid1%TYPE,
    v_mbp_bid_qty1       IN esp_marketdepth.mbp_bid_qty1%TYPE,
    v_mbp_bid_splits1    IN esp_marketdepth.mbp_bid_splits1%TYPE,
    v_mbp_bid2           IN esp_marketdepth.mbp_bid2%TYPE,
    v_mbp_bid_qty2       IN esp_marketdepth.mbp_bid_qty2%TYPE,
    v_mbp_bid_splits2    IN esp_marketdepth.mbp_bid_splits2%TYPE,
    v_mbp_bid3           IN esp_marketdepth.mbp_bid3%TYPE,
    v_mbp_bid_qty3       IN esp_marketdepth.mbp_bid_qty3%TYPE,
    v_mbp_bid_splits3    IN esp_marketdepth.mbp_bid_splits3%TYPE,
    v_mbp_bid4           IN esp_marketdepth.mbp_bid4%TYPE,
    v_mbp_bid_qty4       IN esp_marketdepth.mbp_bid_qty4%TYPE,
    v_mbp_bid_splits4    IN esp_marketdepth.mbp_bid_splits4%TYPE,
    v_mbp_bid5           IN esp_marketdepth.mbp_bid5%TYPE,
    v_mbp_bid_qty5       IN esp_marketdepth.mbp_bid_qty5%TYPE,
    v_mbp_bid_splits5    IN esp_marketdepth.mbp_bid_splits5%TYPE,
    v_mbp_bid6           IN esp_marketdepth.mbp_bid6%TYPE,
    v_mbp_bid_qty6       IN esp_marketdepth.mbp_bid_qty6%TYPE,
    v_mbp_bid_splits6    IN esp_marketdepth.mbp_bid_splits6%TYPE,
    v_mbp_bid7           IN esp_marketdepth.mbp_bid7%TYPE,
    v_mbp_bid_qty7       IN esp_marketdepth.mbp_bid_qty7%TYPE,
    v_mbp_bid_splits7    IN esp_marketdepth.mbp_bid_splits7%TYPE,
    v_mbp_bid8           IN esp_marketdepth.mbp_bid8%TYPE,
    v_mbp_bid_qty8       IN esp_marketdepth.mbp_bid_qty8%TYPE,
    v_mbp_bid_splits8    IN esp_marketdepth.mbp_bid_splits8%TYPE,
    v_mbp_bid9           IN esp_marketdepth.mbp_bid9%TYPE,
    v_mbp_bid_qty9       IN esp_marketdepth.mbp_bid_qty9%TYPE,
    v_mbp_bid_splits9    IN esp_marketdepth.mbp_bid_splits9%TYPE,
    v_mbp_bid10          IN esp_marketdepth.mbp_bid10%TYPE,
    v_mbp_bid_qty10      IN esp_marketdepth.mbp_bid_qty10%TYPE,
    v_mbp_bid_splits10   IN esp_marketdepth.mbp_bid_splits10%TYPE,
    v_mbp_bid11           IN esp_marketdepth.mbp_bid11%TYPE,
    v_mbp_bid_qty11       IN esp_marketdepth.mbp_bid_qty11%TYPE,
    v_mbp_bid_splits11    IN esp_marketdepth.mbp_bid_splits11%TYPE,
    v_mbp_bid12           IN esp_marketdepth.mbp_bid12%TYPE,
    v_mbp_bid_qty12       IN esp_marketdepth.mbp_bid_qty12%TYPE,
    v_mbp_bid_splits12    IN esp_marketdepth.mbp_bid_splits12%TYPE,
    v_mbp_bid13           IN esp_marketdepth.mbp_bid13%TYPE,
    v_mbp_bid_qty13       IN esp_marketdepth.mbp_bid_qty13%TYPE,
    v_mbp_bid_splits13    IN esp_marketdepth.mbp_bid_splits13%TYPE,
    v_mbp_bid14           IN esp_marketdepth.mbp_bid14%TYPE,
    v_mbp_bid_qty14       IN esp_marketdepth.mbp_bid_qty14%TYPE,
    v_mbp_bid_splits14    IN esp_marketdepth.mbp_bid_splits14%TYPE,
    v_mbp_bid15           IN esp_marketdepth.mbp_bid15%TYPE,
    v_mbp_bid_qty15       IN esp_marketdepth.mbp_bid_qty15%TYPE,
    v_mbp_bid_splits15    IN esp_marketdepth.mbp_bid_splits15%TYPE,
    v_mbp_bid16           IN esp_marketdepth.mbp_bid16%TYPE,
    v_mbp_bid_qty16       IN esp_marketdepth.mbp_bid_qty16%TYPE,
    v_mbp_bid_splits16    IN esp_marketdepth.mbp_bid_splits16%TYPE,
    v_mbp_bid17           IN esp_marketdepth.mbp_bid17%TYPE,
    v_mbp_bid_qty17       IN esp_marketdepth.mbp_bid_qty17%TYPE,
    v_mbp_bid_splits17    IN esp_marketdepth.mbp_bid_splits17%TYPE,
    v_mbp_bid18           IN esp_marketdepth.mbp_bid18%TYPE,
    v_mbp_bid_qty18       IN esp_marketdepth.mbp_bid_qty18%TYPE,
    v_mbp_bid_splits18    IN esp_marketdepth.mbp_bid_splits18%TYPE,
    v_mbp_bid19           IN esp_marketdepth.mbp_bid19%TYPE,
    v_mbp_bid_qty19       IN esp_marketdepth.mbp_bid_qty19%TYPE,
    v_mbp_bid_splits19    IN esp_marketdepth.mbp_bid_splits19%TYPE,
    v_mbp_bid20          IN esp_marketdepth.mbp_bid20%TYPE,
    v_mbp_bid_qty20      IN esp_marketdepth.mbp_bid_qty20%TYPE,
    v_mbp_bid_splits20   IN esp_marketdepth.mbp_bid_splits20%TYPE,
    v_mbp_ask1           IN esp_marketdepth.mbp_ask1%TYPE,
    v_mbp_ask_qty1       IN esp_marketdepth.mbp_ask_qty1%TYPE,
    v_mbp_ask_splits1    IN esp_marketdepth.mbp_ask_splits1%TYPE,
    v_mbp_ask2           IN esp_marketdepth.mbp_ask2%TYPE,
    v_mbp_ask_qty2       IN esp_marketdepth.mbp_ask_qty2%TYPE,
    v_mbp_ask_splits2    IN esp_marketdepth.mbp_ask_splits2%TYPE,
    v_mbp_ask3           IN esp_marketdepth.mbp_ask3%TYPE,
    v_mbp_ask_qty3       IN esp_marketdepth.mbp_ask_qty3%TYPE,
    v_mbp_ask_splits3    IN esp_marketdepth.mbp_ask_splits3%TYPE,
    v_mbp_ask4           IN esp_marketdepth.mbp_ask4%TYPE,
    v_mbp_ask_qty4       IN esp_marketdepth.mbp_ask_qty4%TYPE,
    v_mbp_ask_splits4    IN esp_marketdepth.mbp_ask_splits4%TYPE,
    v_mbp_ask5           IN esp_marketdepth.mbp_ask5%TYPE,
    v_mbp_ask_qty5       IN esp_marketdepth.mbp_ask_qty5%TYPE,
    v_mbp_ask_splits5    IN esp_marketdepth.mbp_ask_splits5%TYPE,
    v_mbp_ask6           IN esp_marketdepth.mbp_ask6%TYPE,
    v_mbp_ask_qty6       IN esp_marketdepth.mbp_ask_qty6%TYPE,
    v_mbp_ask_splits6    IN esp_marketdepth.mbp_ask_splits6%TYPE,
    v_mbp_ask7           IN esp_marketdepth.mbp_ask7%TYPE,
    v_mbp_ask_qty7       IN esp_marketdepth.mbp_ask_qty7%TYPE,
    v_mbp_ask_splits7    IN esp_marketdepth.mbp_ask_splits7%TYPE,
    v_mbp_ask8           IN esp_marketdepth.mbp_ask8%TYPE,
    v_mbp_ask_qty8       IN esp_marketdepth.mbp_ask_qty8%TYPE,
    v_mbp_ask_splits8    IN esp_marketdepth.mbp_ask_splits8%TYPE,
    v_mbp_ask9           IN esp_marketdepth.mbp_ask9%TYPE,
    v_mbp_ask_qty9       IN esp_marketdepth.mbp_ask_qty9%TYPE,
    v_mbp_ask_splits9    IN esp_marketdepth.mbp_ask_splits9%TYPE,
    v_mbp_ask10          IN esp_marketdepth.mbp_ask10%TYPE,
    v_mbp_ask_qty10      IN esp_marketdepth.mbp_ask_qty10%TYPE,
    v_mbp_ask_splits10   IN esp_marketdepth.mbp_ask_splits10%TYPE,
    v_mbp_ask11           IN esp_marketdepth.mbp_ask11%TYPE,
    v_mbp_ask_qty11       IN esp_marketdepth.mbp_ask_qty11%TYPE,
    v_mbp_ask_splits11    IN esp_marketdepth.mbp_ask_splits11%TYPE,
    v_mbp_ask12           IN esp_marketdepth.mbp_ask12%TYPE,
    v_mbp_ask_qty12       IN esp_marketdepth.mbp_ask_qty12%TYPE,
    v_mbp_ask_splits12    IN esp_marketdepth.mbp_ask_splits12%TYPE,
    v_mbp_ask13           IN esp_marketdepth.mbp_ask13%TYPE,
    v_mbp_ask_qty13       IN esp_marketdepth.mbp_ask_qty13%TYPE,
    v_mbp_ask_splits13    IN esp_marketdepth.mbp_ask_splits13%TYPE,
    v_mbp_ask14           IN esp_marketdepth.mbp_ask14%TYPE,
    v_mbp_ask_qty14       IN esp_marketdepth.mbp_ask_qty14%TYPE,
    v_mbp_ask_splits14    IN esp_marketdepth.mbp_ask_splits14%TYPE,
    v_mbp_ask15           IN esp_marketdepth.mbp_ask15%TYPE,
    v_mbp_ask_qty15       IN esp_marketdepth.mbp_ask_qty15%TYPE,
    v_mbp_ask_splits15    IN esp_marketdepth.mbp_ask_splits15%TYPE,
    v_mbp_ask16           IN esp_marketdepth.mbp_ask16%TYPE,
    v_mbp_ask_qty16       IN esp_marketdepth.mbp_ask_qty16%TYPE,
    v_mbp_ask_splits16    IN esp_marketdepth.mbp_ask_splits16%TYPE,
    v_mbp_ask17           IN esp_marketdepth.mbp_ask17%TYPE,
    v_mbp_ask_qty17       IN esp_marketdepth.mbp_ask_qty17%TYPE,
    v_mbp_ask_splits17    IN esp_marketdepth.mbp_ask_splits17%TYPE,
    v_mbp_ask18           IN esp_marketdepth.mbp_ask18%TYPE,
    v_mbp_ask_qty18       IN esp_marketdepth.mbp_ask_qty18%TYPE,
    v_mbp_ask_splits18    IN esp_marketdepth.mbp_ask_splits18%TYPE,
    v_mbp_ask19           IN esp_marketdepth.mbp_ask19%TYPE,
    v_mbp_ask_qty19       IN esp_marketdepth.mbp_ask_qty19%TYPE,
    v_mbp_ask_splits19    IN esp_marketdepth.mbp_ask_splits19%TYPE,
    v_mbp_ask20          IN esp_marketdepth.mbp_ask20%TYPE,
    v_mbp_ask_qty20      IN esp_marketdepth.mbp_ask_qty20%TYPE,
    v_mbp_ask_splits20   IN esp_marketdepth.mbp_ask_splits20%TYPE,
    v_last_updated IN DATE)
AS
BEGIN
    UPDATE esp_marketdepth
       SET mbp_bid1 = v_mbp_bid1,
           mbp_bid_qty1 = v_mbp_bid_qty1,
           mbp_bid_splits1 = v_mbp_bid_splits1,
           mbp_bid2 = v_mbp_bid2,
           mbp_bid_qty2 = v_mbp_bid_qty2,
           mbp_bid_splits2 = v_mbp_bid_splits2,
           mbp_bid3 = v_mbp_bid3,
           mbp_bid_qty3 = v_mbp_bid_qty3,
           mbp_bid_splits3 = v_mbp_bid_splits3,
           mbp_bid4 = v_mbp_bid4,
           mbp_bid_qty4 = v_mbp_bid_qty4,
           mbp_bid_splits4 = v_mbp_bid_splits4,
           mbp_bid5 = v_mbp_bid5,
           mbp_bid_qty5 = v_mbp_bid_qty5,
           mbp_bid_splits5 = v_mbp_bid_splits5,
           mbp_bid6 = v_mbp_bid6,
           mbp_bid_qty6 = v_mbp_bid_qty6,
           mbp_bid_splits6 = v_mbp_bid_splits6,
           mbp_bid7 = v_mbp_bid7,
           mbp_bid_qty7 = v_mbp_bid_qty7,
           mbp_bid_splits7 = v_mbp_bid_splits7,
           mbp_bid8 = v_mbp_bid8,
           mbp_bid_qty8 = v_mbp_bid_qty8,
           mbp_bid_splits8 = v_mbp_bid_splits8,
           mbp_bid9 = v_mbp_bid9,
           mbp_bid_qty9 = v_mbp_bid_qty9,
           mbp_bid_splits9 = v_mbp_bid_splits9,
           mbp_bid10 = v_mbp_bid10,
           mbp_bid_qty10 = v_mbp_bid_qty10,
           mbp_bid_splits10 = v_mbp_bid_splits10,
           mbp_bid11 = v_mbp_bid11,
           mbp_bid_qty11 = v_mbp_bid_qty11,
           mbp_bid_splits11 = v_mbp_bid_splits11,
           mbp_bid12 = v_mbp_bid12,
           mbp_bid_qty12 = v_mbp_bid_qty12,
           mbp_bid_splits12 = v_mbp_bid_splits12,
           mbp_bid13 = v_mbp_bid13,
           mbp_bid_qty13 = v_mbp_bid_qty13,
           mbp_bid_splits13 = v_mbp_bid_splits13,
           mbp_bid14 = v_mbp_bid14,
           mbp_bid_qty14 = v_mbp_bid_qty14,
           mbp_bid_splits14 = v_mbp_bid_splits14,
           mbp_bid15 = v_mbp_bid15,
           mbp_bid_qty15 = v_mbp_bid_qty15,
           mbp_bid_splits15 = v_mbp_bid_splits15,
           mbp_bid16 = v_mbp_bid16,
           mbp_bid_qty16 = v_mbp_bid_qty16,
           mbp_bid_splits16 = v_mbp_bid_splits16,
           mbp_bid17 = v_mbp_bid17,
           mbp_bid_qty17 = v_mbp_bid_qty17,
           mbp_bid_splits17 = v_mbp_bid_splits17,
           mbp_bid18 = v_mbp_bid18,
           mbp_bid_qty18 = v_mbp_bid_qty18,
           mbp_bid_splits18 = v_mbp_bid_splits18,
           mbp_bid19 = v_mbp_bid19,
           mbp_bid_qty19 = v_mbp_bid_qty19,
           mbp_bid_splits19 = v_mbp_bid_splits19,
           mbp_bid20 = v_mbp_bid20,
           mbp_bid_qty20 = v_mbp_bid_qty20,
           mbp_bid_splits20 = v_mbp_bid_splits20,
           mbp_ask1 = v_mbp_ask1,
           mbp_ask_qty1 = v_mbp_ask_qty1,
           mbp_ask_splits1 = v_mbp_ask_splits1,
           mbp_ask2 = v_mbp_ask2,
           mbp_ask_qty2 = v_mbp_ask_qty2,
           mbp_ask_splits2 = v_mbp_ask_splits2,
           mbp_ask3 = v_mbp_ask3,
           mbp_ask_qty3 = v_mbp_ask_qty3,
           mbp_ask_splits3 = v_mbp_ask_splits3,
           mbp_ask4 = v_mbp_ask4,
           mbp_ask_qty4 = v_mbp_ask_qty4,
           mbp_ask_splits4 = v_mbp_ask_splits4,
           mbp_ask5 = v_mbp_ask5,
           mbp_ask_qty5 = v_mbp_ask_qty5,
           mbp_ask_splits5 = v_mbp_ask_splits5,
           mbp_ask6 = v_mbp_ask6,
           mbp_ask_qty6 = v_mbp_ask_qty6,
           mbp_ask_splits6 = v_mbp_ask_splits6,
           mbp_ask7 = v_mbp_ask7,
           mbp_ask_qty7 = v_mbp_ask_qty7,
           mbp_ask_splits7 = v_mbp_ask_splits7,
           mbp_ask8 = v_mbp_ask8,
           mbp_ask_qty8 = v_mbp_ask_qty8,
           mbp_ask_splits8 = v_mbp_ask_splits8,
           mbp_ask9 = v_mbp_ask9,
           mbp_ask_qty9 = v_mbp_ask_qty9,
           mbp_ask_splits9 = v_mbp_ask_splits9,
           mbp_ask10 = v_mbp_ask10,
           mbp_ask_qty10 = v_mbp_ask_qty10,
           mbp_ask_splits10 = v_mbp_ask_splits10,
           mbp_ask11 = v_mbp_ask11,
           mbp_ask_qty11 = v_mbp_ask_qty11,
           mbp_ask_splits11 = v_mbp_ask_splits11,
           mbp_ask12 = v_mbp_ask12,
           mbp_ask_qty12 = v_mbp_ask_qty12,
           mbp_ask_splits12 = v_mbp_ask_splits12,
           mbp_ask13 = v_mbp_ask13,
           mbp_ask_qty13 = v_mbp_ask_qty13,
           mbp_ask_splits13 = v_mbp_ask_splits13,
           mbp_ask14 = v_mbp_ask14,
           mbp_ask_qty14 = v_mbp_ask_qty14,
           mbp_ask_splits14 = v_mbp_ask_splits14,
           mbp_ask15 = v_mbp_ask15,
           mbp_ask_qty15 = v_mbp_ask_qty15,
           mbp_ask_splits15 = v_mbp_ask_splits15,
           mbp_ask16 = v_mbp_ask16,
           mbp_ask_qty16 = v_mbp_ask_qty16,
           mbp_ask_splits16 = v_mbp_ask_splits16,
           mbp_ask17 = v_mbp_ask17,
           mbp_ask_qty17 = v_mbp_ask_qty17,
           mbp_ask_splits17 = v_mbp_ask_splits17,
           mbp_ask18 = v_mbp_ask18,
           mbp_ask_qty18 = v_mbp_ask_qty18,
           mbp_ask_splits18 = v_mbp_ask_splits18,
           mbp_ask19 = v_mbp_ask19,
           mbp_ask_qty19 = v_mbp_ask_qty19,
           mbp_ask_splits19 = v_mbp_ask_splits19,
           mbp_ask20 = v_mbp_ask20,
           mbp_ask_qty20 = v_mbp_ask_qty20,
           mbp_ask_splits20 = v_mbp_ask_splits20,
           last_updated =
               CASE
                   WHEN mbp_bid_qty1 = v_mbp_bid_qty1 THEN last_updated
                   ELSE SYSDATE
               END
     WHERE exchangecode = v_exchangecode AND symbol = v_symbol;

    IF (SQL%ROWCOUNT = 0)
    THEN
        INSERT INTO esp_marketdepth (exchangecode,
                                     symbol,
                                     mbp_bid1,
                                     mbp_bid_qty1,
                                     mbp_bid_splits1,
                                     mbp_bid2,
                                     mbp_bid_qty2,
                                     mbp_bid_splits2,
                                     mbp_bid3,
                                     mbp_bid_qty3,
                                     mbp_bid_splits3,
                                     mbp_bid4,
                                     mbp_bid_qty4,
                                     mbp_bid_splits4,
                                     mbp_bid5,
                                     mbp_bid_qty5,
                                     mbp_bid_splits5,
                                     mbp_bid6,
                                     mbp_bid_qty6,
                                     mbp_bid_splits6,
                                     mbp_bid7,
                                     mbp_bid_qty7,
                                     mbp_bid_splits7,
                                     mbp_bid8,
                                     mbp_bid_qty8,
                                     mbp_bid_splits8,
                                     mbp_bid9,
                                     mbp_bid_qty9,
                                     mbp_bid_splits9,
                                     mbp_bid10,
                                     mbp_bid_qty10,
                                     mbp_bid_splits10,
                                     mbp_bid11,
                                     mbp_bid_qty11,
                                     mbp_bid_splits11,
                                     mbp_bid12,
                                     mbp_bid_qty12,
                                     mbp_bid_splits12,
                                     mbp_bid13,
                                     mbp_bid_qty13,
                                     mbp_bid_splits13,
                                     mbp_bid14,
                                     mbp_bid_qty14,
                                     mbp_bid_splits14,
                                     mbp_bid15,
                                     mbp_bid_qty15,
                                     mbp_bid_splits15,
                                     mbp_bid16,
                                     mbp_bid_qty16,
                                     mbp_bid_splits16,
                                     mbp_bid17,
                                     mbp_bid_qty17,
                                     mbp_bid_splits17,
                                     mbp_bid18,
                                     mbp_bid_qty18,
                                     mbp_bid_splits18,
                                     mbp_bid19,
                                     mbp_bid_qty19,
                                     mbp_bid_splits19,
                                     mbp_bid20,
                                     mbp_bid_qty20,
                                     mbp_bid_splits20,
                                     mbp_ask1,
                                     mbp_ask_qty1,
                                     mbp_ask_splits1,
                                     mbp_ask2,
                                     mbp_ask_qty2,
                                     mbp_ask_splits2,
                                     mbp_ask3,
                                     mbp_ask_qty3,
                                     mbp_ask_splits3,
                                     mbp_ask4,
                                     mbp_ask_qty4,
                                     mbp_ask_splits4,
                                     mbp_ask5,
                                     mbp_ask_qty5,
                                     mbp_ask_splits5,
                                     mbp_ask6,
                                     mbp_ask_qty6,
                                     mbp_ask_splits6,
                                     mbp_ask7,
                                     mbp_ask_qty7,
                                     mbp_ask_splits7,
                                     mbp_ask8,
                                     mbp_ask_qty8,
                                     mbp_ask_splits8,
                                     mbp_ask9,
                                     mbp_ask_qty9,
                                     mbp_ask_splits9,
                                     mbp_ask10,
                                     mbp_ask_qty10,
                                     mbp_ask_splits10,
                                     mbp_ask11,
                                     mbp_ask_qty11,
                                     mbp_ask_splits11,
                                     mbp_ask12,
                                     mbp_ask_qty12,
                                     mbp_ask_splits12,
                                     mbp_ask13,
                                     mbp_ask_qty13,
                                     mbp_ask_splits13,
                                     mbp_ask14,
                                     mbp_ask_qty14,
                                     mbp_ask_splits14,
                                     mbp_ask15,
                                     mbp_ask_qty15,
                                     mbp_ask_splits15,
                                     mbp_ask16,
                                     mbp_ask_qty16,
                                     mbp_ask_splits16,
                                     mbp_ask17,
                                     mbp_ask_qty17,
                                     mbp_ask_splits17,
                                     mbp_ask18,
                                     mbp_ask_qty18,
                                     mbp_ask_splits18,
                                     mbp_ask19,
                                     mbp_ask_qty19,
                                     mbp_ask_splits19,
                                     mbp_ask20,
                                     mbp_ask_qty20,
                                     mbp_ask_splits20,
                                     last_updated)
             VALUES (v_exchangecode,
                     v_symbol,
                     v_mbp_bid1,
                     v_mbp_bid_qty1,
                     v_mbp_bid_splits1,
                     v_mbp_bid2,
                     v_mbp_bid_qty2,
                     v_mbp_bid_splits2,
                     v_mbp_bid3,
                     v_mbp_bid_qty3,
                     v_mbp_bid_splits3,
                     v_mbp_bid4,
                     v_mbp_bid_qty4,
                     v_mbp_bid_splits4,
                     v_mbp_bid5,
                     v_mbp_bid_qty5,
                     v_mbp_bid_splits5,
                     v_mbp_bid6,
                     v_mbp_bid_qty6,
                     v_mbp_bid_splits6,
                     v_mbp_bid7,
                     v_mbp_bid_qty7,
                     v_mbp_bid_splits7,
                     v_mbp_bid8,
                     v_mbp_bid_qty8,
                     v_mbp_bid_splits8,
                     v_mbp_bid9,
                     v_mbp_bid_qty9,
                     v_mbp_bid_splits9,
                     v_mbp_bid10,
                     v_mbp_bid_qty10,
                     v_mbp_bid_splits10,
                      v_mbp_bid11,
                     v_mbp_bid_qty11,
                     v_mbp_bid_splits11,
                     v_mbp_bid12,
                     v_mbp_bid_qty12,
                     v_mbp_bid_splits12,
                     v_mbp_bid13,
                     v_mbp_bid_qty13,
                     v_mbp_bid_splits13,
                     v_mbp_bid14,
                     v_mbp_bid_qty14,
                     v_mbp_bid_splits14,
                     v_mbp_bid15,
                     v_mbp_bid_qty15,
                     v_mbp_bid_splits15,
                     v_mbp_bid16,
                     v_mbp_bid_qty16,
                     v_mbp_bid_splits16,
                     v_mbp_bid17,
                     v_mbp_bid_qty17,
                     v_mbp_bid_splits17,
                     v_mbp_bid18,
                     v_mbp_bid_qty18,
                     v_mbp_bid_splits18,
                     v_mbp_bid19,
                     v_mbp_bid_qty19,
                     v_mbp_bid_splits19,
                     v_mbp_bid20,
                     v_mbp_bid_qty20,
                     v_mbp_bid_splits20,
                     v_mbp_ask1,
                     v_mbp_ask_qty1,
                     v_mbp_ask_splits1,
                     v_mbp_ask2,
                     v_mbp_ask_qty2,
                     v_mbp_ask_splits2,
                     v_mbp_ask3,
                     v_mbp_ask_qty3,
                     v_mbp_ask_splits3,
                     v_mbp_ask4,
                     v_mbp_ask_qty4,
                     v_mbp_ask_splits4,
                     v_mbp_ask5,
                     v_mbp_ask_qty5,
                     v_mbp_ask_splits5,
                     v_mbp_ask6,
                     v_mbp_ask_qty6,
                     v_mbp_ask_splits6,
                     v_mbp_ask7,
                     v_mbp_ask_qty7,
                     v_mbp_ask_splits7,
                     v_mbp_ask8,
                     v_mbp_ask_qty8,
                     v_mbp_ask_splits8,
                     v_mbp_ask9,
                     v_mbp_ask_qty9,
                     v_mbp_ask_splits9,
                     v_mbp_ask10,
                     v_mbp_ask_qty10,
                     v_mbp_ask_splits10,
                     v_mbp_ask11,
                     v_mbp_ask_qty11,
                     v_mbp_ask_splits11,
                     v_mbp_ask12,
                     v_mbp_ask_qty12,
                     v_mbp_ask_splits12,
                     v_mbp_ask13,
                     v_mbp_ask_qty13,
                     v_mbp_ask_splits13,
                     v_mbp_ask14,
                     v_mbp_ask_qty14,
                     v_mbp_ask_splits14,
                     v_mbp_ask15,
                     v_mbp_ask_qty15,
                     v_mbp_ask_splits15,
                     v_mbp_ask16,
                     v_mbp_ask_qty16,
                     v_mbp_ask_splits16,
                     v_mbp_ask17,
                     v_mbp_ask_qty17,
                     v_mbp_ask_splits17,
                     v_mbp_ask18,
                     v_mbp_ask_qty18,
                     v_mbp_ask_splits18,
                     v_mbp_ask19,
                     v_mbp_ask_qty19,
                     v_mbp_ask_splits19,
                     v_mbp_ask20,
                     v_mbp_ask_qty20,
                     v_mbp_ask_splits20,
                     SYSDATE);
    END IF;
END;
/
/
