CREATE OR REPLACE VIEW dfn_price.symbol_data
(
    symbol,
    exchangecode,
    instrumenttype,
    currency,
    previousclosed,
    minprice,
    maxprice,
    lasttradeprice,
    accesslevel,
    nationality,
    sector,
    assetclass,
    bestbidprice,
    longdesc_1,
    longdesc_2,
    shortdesc_1,
    shortdesc_2,
    volume,
    high,
    low,
    bestaskprice,
    change,
    bestbidquantity,
    bestaskquantity,
    todaysopen,
    todaysclosed,
    lastaskprice,
    lastbidprice,
    security_type,
    highpriceof52weeks,
    lowpriceof52weeks,
    static_min,
    static_max
)
AS
    SELECT s.symbol,
           s.exchangecode,
           m.instrumenttype,
           s.currency,
           s.previousclosed,
           s.minprice,
           s.maxprice,
           s.lasttradeprice,
           m.accesslevel,
           m.nationality,
           m.sector,
           s.assetclass,
           s.bestbidprice,
           m.symboldescription_1 AS longdesc_1,
           m.symboldescription_2 AS longdesc_2,
           m.symbolshortdescription_1 shortdesc_1,
           m.symbolshortdescription_2 shortdesc_2,
           s.volume,
           s.high,
           s.low,
           s.bestaskprice,
           s.change,
           s.bestbidquantity,
           s.bestaskquantity,
           s.todaysopen,
           s.todaysclosed,
           lastaskprice,
           lastbidprice,
           security_type,
           s.highpriceof52weeks,
           s.lowpriceof52weeks,
           static_min,
           static_max
      FROM esp_todays_snapshots s, esp_symbolmap m
     WHERE     s.symbol = m.symbol
           AND s.exchangecode = m.exchange
           AND m.exchange IN ('DFM',
                              'ADSM',
                              'DGCX',
                              'TDWL')
           AND m.is_active = 1
/