CREATE OR REPLACE PROCEDURE dfn_ntp.sp_redist_order_generate (
    t09c              t09_txn_single_entry_v3%ROWTYPE,
    p_tr_status   OUT NUMBER)
IS
BEGIN
    BEGIN
        UPDATE dfn_ntp.t01_order t
           SET t.t01_cum_netstl = t09c.t09_cumord_netsettle,
               t.t01_status_id_v30 = t09c.t09_ord_status_v30,
               t.t01_orig_commission = t09c.t09_commission_orig,
               t.t01_exec_brk_commission = t09c.t09_exec_brk_commission,
               t.t01_avg_price = t09c.t09_avg_price,          --TODO dushantha
               t.t01_block_amount = t09c.t09_ord_blk,
               t.t01_settle_currency_rate = t09c.t09_fxrate,
               t.t01_cum_quantity = t09c.t09_cum_qty,
               t.t01_cum_ord_value = t09c.t09_cumord_value,
               t.t01_cum_commission = t09c.t09_cum_commission,
               t.t01_cum_exec_brk_commission = t09c.t09_cum_exec_brk_commisn,
               t.t01_cum_accrued_interest = t09c.t09_cum_accrd_intrst,
               t.t01_ord_exec_seq = t09c.t09_lockseq,
               t.t01_last_updated_by = t09c.t09_last_updated_by,
               t.t01_db_last_updated_date = SYSDATE,
               t.t01_last_db_seq_id = t09c.t09_db_seq_id,
               t.t01_position_effect = t09c.t09_position_effect,
               t.t01_remarks = t09c.t09_remarks,
               t.t01_exchange_ord_id = t09c.t09_ordid,
               --t.t01_order_mode = t09c.t09_ord_mode, --do not change order mode of the original order
               t.t01_fix_msg_type = t09c.t09_fix_msg_type,
               t.t01_price_inst_type = t09c.t09_price_inst_type,
               t.t01_last_updated_date_time =
                   NVL (
                       TO_TIMESTAMP (t09c.t09_last_updated_time,
                                     'YYYYMMDDHH24MISS'),
                       SYSDATE),
               t.t01_brker_fix_id = t09c.t09_brker_fix_id,
               t.t01_ord_value = t09c.t09_ord_value,
               t.t01_ord_net_value = t09c.t09_ord_netvalue,
               t.t01_is_active_order = t09c.t09_is_active_order,
               t.t01_ord_net_settle = t09c.t09_ord_netsettle,
               t.t01_fail_mngmnt_status = t09c.t09_fail_mngmnt_status,
               t.t01_fail_mngmnt_clord_id = t09c.t09_fail_mngmnt_clord_id,
               t.t01_fail_mngmnt_exec_id = t09c.t09_fail_mngmnt_exec_id,
               t.t01_profit_loss = t09c.t09_profit_loss,
               t.t01_profit_loss_for_this_exec =
                   t09c.t09_profit_loss_this_exec,
               t.t01_leaves_qty = t09c.t09_leaves_qty,
               t.t01_last_shares = t09c.t09_last_shares,
               t.t01_last_price = t09c.t09_last_price,
               t.t01_broker_tax = t09c.t09_broker_tax,
               t.t01_exchange_tax = t09c.t09_exchange_tax,
               t.t01_cum_broker_tax = t09c.t09_cum_broker_tax,
               t.t01_cum_exchange_tax = t09c.t09_cum_exchange_tax,
               t.t01_act_broker_tax = t09c.t09_act_broker_tax,
               t.t01_act_exchange_tax = t09c.t09_act_exchange_tax,
               t.t01_cum_act_broker_tax = t09c.t09_cum_act_broker_tax,
               t.t01_cum_act_exchange_tax = t09c.t09_cum_act_exchange_tax,
               t.t01_wfa_level = t09c.t09_wfa_current_level,
               t.t01_cum_net_value = t09c.t09_cumord_netvalue,
               t.t01_institution_id_m02 = t09c.t09_institution_id_m02,
               t.t01_ib_commission = t09c.t09_ib_commission,
               t.t01_cum_ib_commission = t09c.t09_cum_ib_commission,
               t.t01_exec_instruction = t09c.t09_exec_instruction,
               t.t01_reject_reason = t09c.t09_reject_reason,
               t.t01_approved_by_id_u17 = t09c.t09_approved_by_id_u17,
               t.t01_cash_settle_date =
                   TO_DATE (t09c.t09_cash_settle_date, 'YYYYMMDD'),
               t.t01_holding_settle_date =
                   TO_DATE (t09c.t09_holding_settle_date, 'YYYYMMDD'),
               t.t01_trade_process_stat_id_v01 =
                   t09c.t09_trade_processing_status_id,
               t.t01_wfa_current_value = t09c.t09_wfa_current_value,
               t.t01_wfa_expected_value = t09c.t09_wfa_expected_value,
               t.t01_remote_sec_source_id = t09c.t09_remote_sec_source_id,
               t.t01_tag50 = t09c.t09_tag50,
               t.t01_cum_discount = t09c.t09_cum_discount,
               t.t01_original_exchange_ord_id = t09c.t09_original_ordid,
               t.t01_quantity = t09c.t09_quantity,
               t.t01_wfa_reason = t09c.t09_wfa_reason,
               t.t01_con_ord_ref_t38 = t09c.t09_cond_order_id_t38,
               t.t01_parent_ord_category_t38 = t09c.t09_parent_ord_category,
               t.t01_orig_exg_tax = t09c.t09_orig_exg_tax,
               t.t01_orig_brk_tax = t09c.t09_orig_brk_tax,
               t.t01_cma_tax = t09c.t09_cma_tax,
               t.t01_cpp_tax = t09c.t09_cpp_tax,
               t.t01_dcm_tax = t09c.t09_dcm_tax,
               t.t01_cum_cma_tax = t09c.t09_cum_cma_tax,
               t.t01_cum_dcm_tax = t09c.t09_cum_dcm_tax,
               t.t01_cum_cpp_tax = t09c.t09_cum_cpp_tax,
               t.t01_act_dcm_tax = t09c.t09_act_dcm_tax,
               t.t01_act_cma_tax = t09c.t09_act_cma_tax,
               t.t01_act_cpp_tax = t09c.t09_act_cpp_tax,
               t.t01_cum_act_cma_tax = t09c.t09_cum_act_cma_tax,
               t.t01_cum_act_cpp_tax = t09c.t09_cum_act_cpp_tax,
               t.t01_cum_act_dcm_tax = t09c.t09_cum_act_dcm_tax,
               t.t01_cma_commission = t09c.t09_cma_commission,
               t.t01_cpp_commission = t09c.t09_cpp_commission,
               t.t01_dcm_commission = t09c.t09_dcm_commission,
               t.t01_cpp_cum_commission = t09c.t09_cpp_cum_commission,
               t.t01_dcm_cum_commission = t09c.t09_dcm_cum_commission,
               t.t01_cma_cum_commission = t09c.t09_cma_cum_commission,
               t.t01_initial_margin_amount = t09c.t09_initial_margin_charge,
               t.t01_maintain_margin_amount = t09c.t09_maintain_margin_charge,
               t.t01_maintain_margin_block = t09c.t09_maintain_margin_block,
               t.t01_cum_maintain_margin_block =
                   t09c.t09_cum_maintain_margin_block,
               t.t01_cum_initial_margin_amount =
                   t09c.t09_cum_initial_margin_charge,
               t.t01_cum_maintain_margin_amount =
                   t09c.t09_cum_maintain_margin_charge,
               t.t01_holding_avg_price = t09c.t09_holding_avg_price,
               t.t01_holding_avg_cost = t09c.t09_holding_avg_cost,
               t.t01_avg_cost = t09c.t09_avg_cost,
               t.t01_negotiated_request_id_t85 = t09c.t09_negotiated_request_id_t85,
               t.t01_board_code_m54 = t09c.t09_board_code_m54,
               t.t01_short_sell_enable = t09c.t09_short_sell_enable,
               t.t01_integration_ext_ref_no = t09c.t09_integration_ext_ref_no,
			   t.t01_other_cum_commission = t09c.t09_other_cum_commission,
               t.t01_other_cum_tax = t09c.t09_other_cum_tax
         WHERE     t.t01_cl_ord_id = t09c.t09_clordid
               AND (t.t01_ord_exec_seq < t09c.t09_lockseq);      --TODO verify

        p_tr_status := 1;

        IF (SQL%ROWCOUNT = 0)
        THEN
            INSERT INTO dfn_ntp.t01_order (t01_cum_netstl,
                                           t01_ord_no,
                                           t01_date_time,
                                           t01_date,
                                           t01_cl_ord_id,
                                           t01_orig_cl_ord_id,
                                           t01_remote_cl_ord_id,
                                           t01_remote_orig_cl_ord_id,
                                           t01_trading_acc_id_u07,
                                           t01_symbol_id_m20,
                                           t01_ord_type_id_v06,
                                           t01_quantity,
                                           t01_price,
                                           t01_min_quantity,
                                           t01_disclose_qty,
                                           t01_tif_id_v10,
                                           t01_status_id_v30,
                                           t01_instruction_type,
                                           t01_commission,
                                           t01_orig_commission,
                                           t01_discount,
                                           t01_exec_brk_commission,
                                           t01_avg_price,
                                           t01_block_amount,
                                           t01_settle_currency_rate,
                                           t01_expiry_date,
                                           t01_cum_quantity,
                                           t01_cum_ord_value,
                                           t01_cum_commission,
                                           t01_cum_exec_brk_commission,
                                           t01_cum_accrued_interest,
                                           t01_accrued_interest,
                                           t01_exec_broker_id_m26,
                                           t01_custodian_id_m26,
                                           t01_emp_trading_id_u19,
                                           t01_ord_exec_seq,
                                           t01_db_created_date,
                                           t01_last_updated_by,
                                           t01_db_last_updated_date,
                                           t01_side,
                                           t01_ord_channel_id_v29,
                                           t01_symbol_code_m20,
                                           t01_customer_login_id_u09,
                                           t01_dealer_id_u17,
                                           t01_last_db_seq_id,
                                           t01_exchange_code_m01,
                                           t01_market_code_m29,
                                           t01_customer_id_u01,
                                           t01_position_effect,
                                           t01_remarks,
                                           t01_tag_remote_sub_comp_id,
                                           t01_remote_tag_22,
                                           t01_remote_tag_100,
                                           t01_remote_sid,
                                           t01_tenant_code,
                                           t01_cash_acc_id_u06,
                                           t01_instrument_type_code,
                                           t01_exchange_ord_id,
                                           t01_order_mode,
                                           t01_fix_msg_type,
                                           t01_price_inst_type,
                                           t01_last_updated_date_time,
                                           t01_brker_fix_id,
                                           t01_trading_acntno_u07,
                                           t01_ord_value,
                                           t01_ord_net_value,
                                           t01_settle_currency,
                                           t01_gainloss,
                                           t01_is_active_order,
                                           t01_fail_mngmnt_status,
                                           t01_fail_mngmnt_clord_id,
                                           t01_fail_mngmnt_exec_id,
                                           t01_symbol_currency_code_m03,
                                           t01_profit_loss,
                                           t01_profit_loss_for_this_exec,
                                           t01_leaves_qty,
                                           t01_last_shares,
                                           t01_last_price,
                                           t01_server_id,
                                           t01_broker_tax,
                                           t01_exchange_tax,
                                           t01_cum_broker_tax,
                                           t01_cum_exchange_tax,
                                           t01_act_broker_tax,
                                           t01_act_exchange_tax,
                                           t01_cum_act_broker_tax,
                                           t01_cum_act_exchange_tax,
                                           t01_ord_net_settle,
                                           t01_wfa_level,
                                           t01_cum_net_value,
                                           t01_institution_id_m02,
                                           t01_ib_commission,
                                           t01_cum_ib_commission,
                                           t01_custodian_type_v01,
                                           t01_exec_instruction,
                                           t01_desk_order_ref_t52,
                                           t01_desk_order_no_t52,
                                           t01_cash_settle_date,
                                           t01_holding_settle_date,
                                           t01_trade_process_stat_id_v01,
                                           t01_algo_ord_ref_t54,
                                           t01_wfa_current_value,
                                           t01_wfa_expected_value,
                                           t01_remote_sec_source_id,
                                           t01_tag50,
                                           t01_orig_exg_commission,
                                           t01_cum_discount,
                                           t01_original_exchange_ord_id,
                                           t01_poa_id_u47,
                                           t01_wfa_reason,
                                           t01_con_ord_ref_t38,
                                           t01_parent_ord_category_t38,
                                           t01_orig_exg_tax,
                                           t01_orig_brk_tax,
                                           t01_cma_tax,
                                           t01_cpp_tax,
                                           t01_dcm_tax,
                                           t01_cum_cma_tax,
                                           t01_cum_dcm_tax,
                                           t01_cum_cpp_tax,
                                           t01_act_dcm_tax,
                                           t01_act_cma_tax,
                                           t01_act_cpp_tax,
                                           t01_cum_act_cma_tax,
                                           t01_cum_act_cpp_tax,
                                           t01_cum_act_dcm_tax,
                                           t01_cma_commission,
                                           t01_cpp_commission,
                                           t01_dcm_commission,
                                           t01_cpp_cum_commission,
                                           t01_dcm_cum_commission,
                                           t01_cma_cum_commission,
                                           t01_initial_margin_amount,
                                           t01_maintain_margin_amount,
                                           t01_cum_initial_margin_amount,
                                           t01_cum_maintain_margin_amount,
                                           t01_maintain_margin_block,
                                           t01_cum_maintain_margin_block,
                                           t01_holding_avg_price,
                                           t01_contract_id_t75,
                                           t01_holding_avg_cost,
                                           t01_avg_cost,
                                           t01_exchange_id_m01,
                                           t01_negotiated_request_id_t85,
                                           t01_board_code_m54,
                                           t01_short_sell_enable,
                                           t01_integration_ext_ref_no,
										   t01_other_commission,
                                           t01_other_tax,
                                           t01_other_cum_commission,
                                           t01_other_cum_tax)
                SELECT t09c.t09_cumord_netsettle,
                       t09c.t09_ord_no,
                       NVL (
                           TO_TIMESTAMP (t09c.t09_created_time,
                                         'YYYYMMDDHH24MISS'),
                           SYSDATE),
                       /*      TRUNC(NVL (
                                 TO_DATE (t09c.t09_created_time,
                                          'YYYYMMDD24MISS'),
                                 SYSDATE)),*/
                       --Changed by MJ due to t01_date_time issue
                       SYSDATE,
                       t09c.t09_clordid,
                       t09c.t09_clordid_orig,
                       t09c.t09_remote_clordid,
                       t09c.t09_remote_orig_clordid,
                       t09c.t09_trading_acc_id_u07,
                       TO_NUMBER (t09c.t09_symbol_id_m20),
                       t09c.t09_ord_type_v06,
                       t09c.t09_quantity,
                       t09c.t09_price,
                       t09c.t09_minfil_qty,
                       t09c.t09_disclosed_qty,
                       t09c.t09_tif_m58,
                       t09c.t09_ord_status_v30,
                       TO_NUMBER (t09c.t09_instruction_type),
                       NVL (t09c.t09_commission, -1),
                       t09c.t09_commission_orig,
                       t09c.t09_commisn_discount,
                       t09c.t09_exec_brk_commission,
                       t09c.t09_avg_price,                   -- TODO dushantha
                       t09c.t09_ord_blk,
                       t09c.t09_fxrate,
                       TO_DATE (t09c.t09_exp_date, 'YYYYMMDD'),
                       t09c.t09_cum_qty,
                       t09c.t09_cumord_value,
                       t09c.t09_cum_commission,
                       t09c.t09_cum_exec_brk_commisn,
                       t09c.t09_cum_accrd_intrst,
                       t09c.t09_accurd_intrst,
                       t09c.t09_exec_brkr_id_m26,
                       t09c.t09_custodian_id_m26,
                       t09c.t09_poa_id_u47,
                       t09c.t09_lockseq,
                       SYSDATE,
                       t09c.t09_last_updated_by,
                       SYSDATE,
                       TO_NUMBER (t09c.t09_side),
                       t09c.t09_channel_id_v29,
                       t09c.t09_symbol_code_m20,
                       t09c.t09_online_login_id_u09,
                       t09c.t09_dealer_id_u18,
                       t09c.t09_db_seq_id,
                       t09c.t09_exchange_m01,
                       t09c.t09_market_code_m29,
                       t09c.t09_customer_id_u01,
                       t09c.t09_position_effect,
                       t09c.t09_remarks,
                       t09c.t09_remote_sub_comp_id,
                       t09c.t09_remote_tag_22,
                       t09c.t09_remote_tag_100,
                       t09c.t09_remote_sid,
                       t09c.t09_tenant_code,
                       t09c.t09_cashacnt_id_u06,
                       t09c.t09_instrument_type,
                       t09c.t09_ordid,
                       t09c.t09_ord_mode,
                       t09c.t09_fix_msg_type,
                       t09c.t09_price_inst_type,
                       NVL (
                           TO_TIMESTAMP (t09c.t09_last_updated_time,
                                         'YYYYMMDDHH24MISS'),
                           SYSDATE),
                       t09c.t09_brker_fix_id,
                       t09c.t09_trading_acntno_u07,
                       t09c.t09_ord_value,
                       t09c.t09_ord_netvalue,
                       t09c.t09_settle_currency_m03,
                       t09c.t09_gain_loss,
                       t09c.t09_is_active_order,
                       t09c.t09_fail_mngmnt_status,
                       t09c.t09_fail_mngmnt_clord_id,
                       t09c.t09_fail_mngmnt_exec_id,
                       t09c.t09_txn_currency_m03,
                       t09c.t09_profit_loss,
                       t09c.t09_profit_loss_this_exec,
                       t09c.t09_leaves_qty,
                       t09c.t09_last_shares,
                       t09c.t09_last_price,
                       t09c.t09_app_server_id,
                       t09c.t09_broker_tax,
                       t09c.t09_exchange_tax,
                       t09c.t09_cum_broker_tax,
                       t09c.t09_cum_exchange_tax,
                       t09c.t09_act_broker_tax,
                       t09c.t09_act_exchange_tax,
                       t09c.t09_cum_act_broker_tax,
                       t09c.t09_cum_act_exchange_tax,
                       t09c.t09_ord_netsettle,
                       t09c.t09_wfa_current_level,
                       t09c.t09_cumord_netvalue,
                       t09c.t09_institution_id_m02,
                       t09c.t09_ib_commission,
                       t09c.t09_cum_ib_commission,
                       t09c.t09_custodian_type_v01,
                       t09c.t09_exec_instruction,
                       t09c.t09_desk_order_ref_t52,
                       t09c.t09_desk_order_no_t52,
                       TO_DATE (t09c.t09_cash_settle_date, 'YYYYMMDD'),
                       TO_DATE (t09c.t09_holding_settle_date, 'YYYYMMDD'),
                       t09c.t09_trade_processing_status_id,
                       t09c.t09_algo_order_ref_t54,
                       t09c.t09_wfa_current_value,
                       t09c.t09_wfa_expected_value,
                       t09c.t09_remote_sec_source_id,
                       t09c.t09_tag50,
                       t09c.t09_exg_commission_orig,
                       t09c.t09_cum_discount,
                       t09c.t09_original_ordid,
                       t09c.t09_poa_id_u47,
                       t09c.t09_wfa_reason,
                       t09c.t09_cond_order_id_t38,
                       t09c.t09_parent_ord_category,
                       t09c.t09_orig_exg_tax,
                       t09c.t09_orig_brk_tax,
                       t09c.t09_cma_tax,
                       t09c.t09_cpp_tax,
                       t09c.t09_dcm_tax,
                       t09c.t09_cum_cma_tax,
                       t09c.t09_cum_dcm_tax,
                       t09c.t09_cum_cpp_tax,
                       t09c.t09_act_dcm_tax,
                       t09c.t09_act_cma_tax,
                       t09c.t09_act_cpp_tax,
                       t09c.t09_cum_act_cma_tax,
                       t09c.t09_cum_act_cpp_tax,
                       t09c.t09_cum_act_dcm_tax,
                       t09c.t09_cma_commission,
                       t09c.t09_cpp_commission,
                       t09c.t09_dcm_commission,
                       t09c.t09_cpp_cum_commission,
                       t09c.t09_dcm_cum_commission,
                       t09c.t09_cma_cum_commission,
                       t09c.t09_initial_margin_charge,
                       t09c.t09_maintain_margin_charge,
                       t09c.t09_cum_initial_margin_charge,
                       t09c.t09_cum_maintain_margin_charge,
                       t09c.t09_maintain_margin_block,
                       t09c.t09_cum_maintain_margin_block,
                       t09c.t09_holding_avg_price,
                       t09c.t09_contract_id_t75,
                       t09c.t09_holding_avg_cost,
                       t09c.t09_avg_cost,
                       t09c.t09_exchange_id_m01,
                       t09c.t09_negotiated_request_id_t85,
                       t09c.t09_board_code_m54,
                       t09c.t09_short_sell_enable,
                       t09c.t09_integration_ext_ref_no,
					   t09c.t09_other_commission,
                       t09c.t09_other_tax,
                       t09c.t09_other_cum_commission,
                       t09c.t09_other_cum_tax
                  FROM DUAL;

            p_tr_status := 2;
        END IF;

        IF (    t09c.t09_clordid_orig IS NOT NULL
            AND t09c.t09_orig_ord_status_v30 IS NOT NULL)
        THEN
            UPDATE t01_order t1
               SET t1.t01_status_id_v30 = t09c.t09_orig_ord_status_v30
             WHERE t1.t01_cl_ord_id = t09c.t09_clordid_orig;

            p_tr_status := -1;
        END IF;

        IF (    t09c.t09_is_active_order_orig > -1
            AND t09c.t09_clordid_orig IS NOT NULL)
        THEN
            UPDATE t01_order t1
               SET t1.t01_is_active_order = t09c.t09_is_active_order_orig
             WHERE t1.t01_cl_ord_id = t09c.t09_clordid_orig;

            p_tr_status := -2;
        END IF;

        IF (    t09c.t09_fail_mngmnt_clord_id IS NOT NULL
            AND t09c.t09_fail_mngmnt_exec_id IS NOT NULL)
        THEN
            UPDATE t01_order t1
               SET t1.t01_fail_mngmnt_status = 5       -- RECAPTURE_ICM_REJECT
             WHERE t1.t01_cl_ord_id = t09c.t09_fail_mngmnt_clord_id;

            p_tr_status := -3;
        END IF;
    END;
END;
/
