-- Foreign Key for  DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS


  ALTER TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS ADD CONSTRAINT FK_ESP_EXCHANGE_DESCRIPTIONS_E FOREIGN KEY (LANGUAGE)
	  REFERENCES DFN_PRICE.ESP_LANGUAGE_MASTER (LANGUAGE_CODE) ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS ADD CONSTRAINT FK_ESP_EXCHANGE_DESCRIPTIONS_1 FOREIGN KEY (EXCHANGE)
	  REFERENCES DFN_PRICE.ESP_EXCHANGEMASTER (EXCHANGE) ENABLE
/
-- End of REF DDL Script for Table DFN_PRICE.ESP_EXCHANGE_DESCRIPTIONS
