-- Foreign Key for  DFN_PRICE.ESP_TRANSACTIONS_COMPLETE


  ALTER TABLE DFN_PRICE.ESP_TRANSACTIONS_COMPLETE ADD CONSTRAINT FK_TRANSCOM_EXCHANGE FOREIGN KEY (EXCHANGECODE)
	  REFERENCES DFN_PRICE.ESP_EXCHANGEMASTER (EXCHANGE) ENABLE
/
-- End of REF DDL Script for Table DFN_PRICE.ESP_TRANSACTIONS_COMPLETE
