-- Foreign Key for  DFN_PRICE.ESP_MARKETS_DESCRIPTIONS


  ALTER TABLE DFN_PRICE.ESP_MARKETS_DESCRIPTIONS ADD CONSTRAINT ESP_MARKETS_DESC_MASTER FOREIGN KEY (EXCHANGECODE, MARKET_CODE)
	  REFERENCES DFN_PRICE.ESP_MARKETS (EXCHANGE, MARKET_CODE) ENABLE
/

  ALTER TABLE DFN_PRICE.ESP_MARKETS_DESCRIPTIONS ADD CONSTRAINT ESP_MARKETS_DESC_EXCG FOREIGN KEY (EXCHANGECODE)
	  REFERENCES DFN_PRICE.ESP_EXCHANGEMASTER (EXCHANGE) ENABLE
/
-- End of REF DDL Script for Table DFN_PRICE.ESP_MARKETS_DESCRIPTIONS
