-- Foreign Key for  DFN_PRICE.ESP_SECTORS


  ALTER TABLE DFN_PRICE.ESP_SECTORS ADD CONSTRAINT FK_SECTOR_EXCHANGE FOREIGN KEY (EXCHANGECODE)
	  REFERENCES DFN_PRICE.ESP_EXCHANGEMASTER (EXCHANGE) ENABLE
/
-- End of REF DDL Script for Table DFN_PRICE.ESP_SECTORS
