DECLARE
    l_count   NUMBER := 0;
    l_table   VARCHAR2 (50) := 'table_map';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM user_tables
     WHERE table_name = UPPER (l_table);

    IF (l_count = 1)
    THEN
        EXECUTE IMMEDIATE 'DROP TABLE ' || l_table || '';
    END IF;

    EXECUTE IMMEDIATE
           'CREATE TABLE '
        || l_table
        || ' (
    seq_id          NUMBER (4, 0),
    at_name         VARCHAR2 (50 BYTE),
    ntp_name        VARCHAR2 (50 BYTE),
    expected_diff   NUMBER (10, 0),
    comments        VARCHAR2 (500 BYTE)
    )';
END;
/

INSERT INTO table_map 
VALUES(0,'M05_BRANCHES','M02_INSTITUTE',0,NULL);
INSERT INTO table_map 
VALUES(1,'M28_DEPARTMENTS','M12_EMPLOYEE_DEPARTMENT',1,'SYSTEM User Department for NTP (+1)');
INSERT INTO table_map 
VALUES(2,'M06_EMPLOYEES','U17_EMPLOYEE',-2,'DFNADMIN for NTP (+1) | INTEGRATION USER for DFN (+1) | Users (Except ADMIN) in Admin Institution for Old (-4)');
INSERT INTO table_map 
VALUES(3,'M03_EXCHANGE_RATES','M04_CURRENCY_RATE',0,NULL);
INSERT INTO table_map 
VALUES(4,'M53_LOCATIONS','M07_LOCATION',0,NULL);
INSERT INTO table_map 
VALUES(5,'M11_EXCHANGES','M01_EXCHANGES',0,NULL);
INSERT INTO table_map 
VALUES(7,'M157_COMPANIES','M09_COMPANIES',0,NULL);
INSERT INTO table_map 
VALUES(8,'M254_RELATIONSHIP_MANAGERS','M10_RELATIONSHIP_MANAGER',0,NULL);
INSERT INTO table_map 
VALUES(10,'M146_ISSUE_LOCATION','M14_ISSUE_LOCATION',18,'Looped for Extra Institution for NTP (+18)');
INSERT INTO table_map 
VALUES(21,'M36_BANKS','M16_BANK',0,NULL);
INSERT INTO table_map 
VALUES(22,'M168_BANK_BRANCHES','M17_BANK_BRANCHES',0,NULL);
INSERT INTO table_map 
VALUES(23,'M115_SUB_MARKETS','M29_MARKETS',0,NULL);
INSERT INTO table_map 
VALUES(24,'M99_SECTORS','M63_SECTORS',0,NULL);
INSERT INTO table_map 
VALUES(25,'M77_SYMBOLS','M20_SYMBOL',0,NULL);
INSERT INTO table_map 
VALUES(27,'M199_INTRODUCING_BROKER','M21_INTRODUCING_BROKER',0,NULL);
INSERT INTO table_map 
VALUES(29,'M52_COMMISSION_STRUCTURES','M23_COMMISSION_SLABS',0,NULL);
INSERT INTO table_map 
VALUES(30,'M278_COMMISION_DISCOUNT_GROUP','M24_COMMISSION_DISCOUNT_GROUP',0,NULL);
INSERT INTO table_map 
VALUES(41,'M279_COMMISION_DISCOUNT_RATE','M25_COMMISSION_DISCOUNT_SLABS',0,NULL);
INSERT INTO table_map 
VALUES(43,'M10_EXCHANGE_COMMISSION_EXEC','M34_EXEC_BROKER_COMMISSION',0,NULL);
INSERT INTO table_map 
VALUES(44,'M127_CUSTOMER_GRADE_DATA','M28_CUSTOMER_GRADE_DATA',0,NULL);
INSERT INTO table_map 
VALUES(45,'M119_EXCHANGE_ORDER_TYPES','M57_EXCHANGE_ORDER_TYPES',0,NULL);
INSERT INTO table_map 
VALUES(46,'M118_EXCHANGE_TIF','M58_EXCHANGE_TIF',0,NULL);
INSERT INTO table_map 
VALUES(47,'M166_EXCHANGE_MARKET_STATUS','M59_EXCHANGE_MARKET_STATUS',0,NULL);
INSERT INTO table_map 
VALUES(64,'M108_EMPLOYEE_TRD_LIMITS','M50_EMPLOYEE_TRD_LIMITS',0,NULL);
INSERT INTO table_map 
VALUES(65,'M278_DEALER_CUSTOMER_GROUP','M51_EMPLOYEE_TRADING_GROUPS',42,'Local & International Trading Groups for DFNADMIN User for NTP (+21 * 2)');
INSERT INTO table_map 
VALUES(66,'M173_BRANCH_BANKS','M60_INSTITUTE_BANKS',-2,'Banks in Admin Institution for Old (-2)');
INSERT INTO table_map 
VALUES(67,'G05_BRANCH_DOCUMENTS','M62_INSTITUTE_DOCUMENTS',0,NULL);
INSERT INTO table_map 
VALUES(68,'M151_NOTIFICATION_GROUPS','M52_NOTIFICATION_GROUP',1,'Notification Group for ADMIN User for NTP (+1)');
INSERT INTO table_map 
VALUES(69,'M253_SAIBOR_BASIS_RATES','M65_SAIBOR_BASIS_RATES',+2,'Default Saibor Basis Rates for Default Margin Interest Groups for NTP (+2)');
INSERT INTO table_map 
VALUES(70,'M184_FIX_LOGINS','M67_FIX_LOGINS',0,NULL);
INSERT INTO table_map 
VALUES(82,'M109_INSTITUTION_TRD_LIMITS','M69_INSTITUTE_TRADING_LIMITS',0,NULL);
INSERT INTO table_map 
VALUES(84,'EX03_EXE_INST_CASH_ACCOUNT','M72_EXEC_BROKER_CASH_ACCOUNT',0,NULL);
INSERT INTO table_map 
VALUES(87,'M291_SYMBOL_MARGINABILITY_GRPS','M77_SYMBOL_MARGINABILITY_GRPS',0,NULL);
INSERT INTO table_map 
VALUES(88,'M90_SYMBOL_MARGINABILITY','M78_SYMBOL_MARGINABILITY',0,NULL);
INSERT INTO table_map 
VALUES(89,'M196_PENDNG_SYMBL_MRG_REQUESTS','M79_PENDING_SYMBL_MRG_REQUEST',0,NULL);
INSERT INTO table_map 
VALUES(95,'M51_COMMISSION_TYPE','M89_CUSTOMER_CATEGORY',23,'Looped for Extra Institution for NTP (+23)');
INSERT INTO table_map 
VALUES(101,'M116_EXCHANGE_BROKERS','M105_OTHER_BROKERAGES', 9, 'Looped for Extra Institution for NTP (+9)');
INSERT INTO table_map 
VALUES(102,'M156_COMPANY_POSITIONS','M114_COMPANY_POSITIONS',0,NULL);
INSERT INTO table_map 
VALUES(103,'M252_WITHDRAW_BLOCK_REASON','M110_REASONS', 9, 'Looped for Extra Institution for NTP (+9)');
INSERT INTO table_map 
VALUES(104,'M268_HIJRI_ADJUSTMENTS','M116_HIJRI_ADJUSTMENTS',0,NULL);
INSERT INTO table_map 
VALUES(105,'M280_CHARGES_GROUPS','M117_CHARGE_GROUPS', 23, 'Looped for Extra Institution for NTP (+23)');
INSERT INTO table_map 
VALUES(108,'U16_INST_SHARIA_SYMBOLS','M119_SHARIA_SYMBOL',0,NULL);
INSERT INTO table_map 
VALUES(109,'M155_EXCHANGE_TICK_SIZES','M122_EXCHANGE_TICK_SIZES',0,NULL);
INSERT INTO table_map 
VALUES(110,'M291_EXCHANGE_INSTRUMENT_TYPE','M125_EXCHANGE_INSTRUMENT_TYPE',0,NULL);
INSERT INTO table_map 
VALUES(124,'T14_BANK_ACCOUNTS','M93_BANK_ACCOUNTS', -7,'Bank Account in Admin Institution for Old (-7)');
INSERT INTO table_map 
VALUES(125,'M01_CUSTOMER','U01_CUSTOMER', -5, 'Customers in Admin Institution for Old (-5)');
INSERT INTO table_map 
VALUES(126,'M131_CUSTOMER_FAMILY_MEMBERS','M109_CUSTOMER_FAMILY_MEMBERS',0,NULL);
INSERT INTO table_map 
VALUES(128,'M160_CUSTOMER_CONTACTS','U48_CORP_CUSTOMER_CONTACT', 0, NULL);
INSERT INTO table_map 
VALUES(129,'M243_CUSTOMER_IDENTIFICATIONS','U05_CUSTOMER_IDENTIFICATION',-5,'Customers in Admin Institution for Old (-5)');
INSERT INTO table_map 
VALUES(130,'M01_CMA_COMPLIENT_DETAILS','U03_CUSTOMER_KYC',0,NULL);
INSERT INTO table_map 
VALUES(141,'T03_CASH_ACCOUNT','U06_CASH_ACCOUNT', -16,'Cash Accounts in Admin Institution for Old (-16)');
INSERT INTO table_map 
VALUES(142,'M348_MARKET_MAKERS','M131_MARKET_MAKER_GRPS', 3, 'Looped for Extra Institution for NTP (+3)');
INSERT INTO table_map 
VALUES(143,'U06_ROUTING_ACCOUNTS','U07_TRADING_ACCOUNT',-11,'Security Accounts in Admin Institution for Old (-11)');
INSERT INTO table_map 
VALUES(149,'M141_CUST_NOTIFICATION_SCHEDUL','M104_CUST_NOTIFICATION_SCHEDUL',0,NULL);
INSERT INTO table_map 
VALUES(163,'U10_RESTRICTED_INSTRMNT_TYPES','U16_TRADING_INSTRUMENT_RESTRIC',13,'Looped for Buy & Sell for NTP (+13)');
INSERT INTO table_map 
VALUES(164,'U20_RESTRICTED_CHANNELS','U18_TRADING_CHANNEL_RESTRICT',32,'Looped for Buy & Sell for NTP (+32)');
INSERT INTO table_map 
VALUES(165,'U22_CUSTOMER_MARGIN_PRODUCTS','U23_CUSTOMER_MARGIN_PRODUCT',0,NULL);
INSERT INTO table_map 
VALUES(169,'M148_EMPLOYEE_EXCHANGES','U28_EMPLOYEE_EXCHANGES',1,'Dealer Exchange for INTEGRATION USER for NTP (+1)');
INSERT INTO table_map 
VALUES(170,'M152_EMP_NOTIFICATION_GROUPS','U29_EMP_NOTIFICATION_GROUPS',0,NULL);
INSERT INTO table_map 
VALUES(181,'M280_MASTER_NOTIFICATIONS','U41_NOTIFICATION_CONFIGURATION',0,NULL);
INSERT INTO table_map 
VALUES(182,'G06_UPLOADED_DOCUMENTS','U44_UPLOADED_DOCUMENTS',0,NULL);
INSERT INTO table_map 
VALUES(183,'G07_UPLOADED_DOC_PAGES','U45_UPLOADED_DOC_PAGES',0,NULL);
INSERT INTO table_map 
VALUES(186,'M175_CUTOMER_POA_SYMBOLS','U55_POA_SYMBOL_RESTRICTIONS',0,NULL);
INSERT INTO table_map 
VALUES(201,'T43_EXE_INST_CASH_ACC_LOG','T05_INSTITUTE_CASH_ACC_LOG',-36,'Logs in Admin Institution for Old (-36)');
INSERT INTO table_map 
VALUES(203,'T16_PENDING_OD','T08_OD_WITHDRAW_LIMIT',0,NULL);
INSERT INTO table_map 
VALUES(204,'T77_FUND_TRANSFER_BLOCK','T10_CASH_BLOCK_REQUEST',0,NULL);
INSERT INTO table_map 
VALUES(221,'T18_DAILY_STATUS','H26_DAILY_STATUS',0,NULL);
INSERT INTO table_map 
VALUES(222,'T52_DESK_ORDERS','T52_DESK_ORDERS',0,NULL);
INSERT INTO table_map 
VALUES(226,'M03_EXCHANGE_RATES_HISTORY','H03_CURRENCY_RATE', 1024709, 'Looped for Extra Institution for NTP (+1024709)');
INSERT INTO table_map 
VALUES(227,'M109_INSTITUTION_TRD_LIMITS','H05_INSTITUTE_TRADING_LIMITS',0,NULL);
INSERT INTO table_map 
VALUES(230,'S11_BANK_ACCOUNTS_SUMMARY','H10_BANK_ACCOUNTS_SUMMARY',-217,'Bank Accounts in Admin INstitution for Old (-217)');
INSERT INTO table_map 
VALUES(243,'M286_SUKUK_COUPON_PAYMENT','M1001_SUKUK_COUPON_PAYMENT',0,NULL);
INSERT INTO table_map 
VALUES(246,'M80_AGENT_COMMISSION_GROUPS','M162_INCENTIVE_GROUP',1,'Default Incentive Group for RM Type for NTP (+1)');
INSERT INTO table_map 
VALUES(247,'M81_AGENT_COMMISSION_STRUCTS','M163_INCENTIVE_SLABS',0,NULL);
INSERT INTO table_map 
VALUES(249,'TMP10_CUST_NOTIFICATIONS','T14_NOTIFICATION_DATA',0,NULL);
INSERT INTO table_map 
VALUES(250,'T83_U_MESSAGE','T18_C_UMESSAGE',0,NULL);
INSERT INTO table_map 
VALUES(262,'M147_PRICE_USER_POOL','M161_PRICE_USER_POOL',0,NULL);
INSERT INTO table_map 
VALUES(263,'M201_PRICEUSER_AGREEMENT','M158_PRICEUSER_AGREEMENT',0,NULL);
INSERT INTO table_map 
VALUES(264,'M120_ASSET_MANAGEMENT_COMPANIE','M178_ASSET_MANAGEMENT_COMPANY',0,NULL);
INSERT INTO table_map 
VALUES(265,'M349_MARKET_MAKER_DETAILS','M132_MARKET_MAKER_GRP_DETAILS',12,'Looped for Extra Institution for NTP (+12)');
INSERT INTO table_map 
VALUES(266,'T36_SLICE_ORDERS','T54_SLICE_ORDERS',0,NULL);
/* Janaka: Will be Handled from ETI Migration
INSERT INTO table_map 
VALUES(268,'M236_PRICE_SUBSCRIPTION_FEES','M153_EXCHANGE_SUBSCRIPTION_PRD',0,NULL);
INSERT INTO table_map 
VALUES(270,'M237_CUST_SUBSCRIPTION_WAVEOFF','M155_PRODUCT_WAIVEOFF_DETAILS',0,NULL);
INSERT INTO table_map 
VALUES(281,'M237_CUST_SUBSCRIPTION_WAVEOFF','M156_EXCHANGE_WAIVEOFF_DETAILS',0,NULL);
INSERT INTO table_map 
VALUES(282,'T73_CUST_SUBSCRIBE_PRD','T56_PRODUCT_SUBSCRIPTION_DATA',0,NULL);
INSERT INTO table_map 
VALUES(283,'T73_CUST_SUBSCRIBE_PRD','T57_EXCHANGE_SUBSCRIPTION_DATA',0,NULL);
*/
INSERT INTO table_map 
VALUES(284,'M77_OFLINE_SYMBOLS_UPDATE_LOG','M160_OFFLINE_SYMBOL_UPDATE_LOG',0,NULL);
INSERT INTO table_map 
VALUES(285,'M258_PRICE_TYPES','M39_PRICE_QTY_FACTORS',2,'Default Price Quantity Factor for ADMIN Institute for Old (+1) | Default Price Quantity Factor for NTP (+1)');
INSERT INTO table_map 
VALUES(288,'M272_CORPORATE_ACTIONS','M141_CUST_CORPORATE_ACTION',0,NULL);
INSERT INTO table_map 
VALUES(289,'M336_CUSTODIAN_FEE_GROUPS','M166_CUSTODY_CHARGES_GROUP', 5,'Looped for Extra Institution for NTP (+5)');
INSERT INTO table_map 
VALUES(290,'M337_CUSTODIAN_FEE_STRUCTURES','M167_CUSTODY_CHARGES_SLAB', 77,'Looped for Extra Institution for NTP (+77)');
INSERT INTO table_map 
VALUES(301,'M379_PAYING_AGENTS','M170_INSTITUTE_CASH_ACC_CONFIG',0,NULL);
INSERT INTO table_map 
VALUES(302,'T122_PAYMENT_SESSIONS','T500_PAYMENT_SESSIONS_C',35,'Looped for Extra Institution for NTP (+35)');
INSERT INTO table_map 
VALUES(303,'T123_PAYMENT_LOG','T501_PAYMENT_DETAIL_C',0,NULL);
INSERT INTO table_map 
VALUES(304,'T110_STOCK_BULK_TRANS_DETAILS','T61_BULK_SHARE_TRANSACTIONS',0,NULL);
INSERT INTO table_map 
VALUES(306,'T32_CONDITIONAL_ORDERS','T38_CONDITIONAL_ORDER',0,NULL);
INSERT INTO table_map 
VALUES(309,'T10_GL_LOCAL_INTEGRATION_SFC','T29_GL_COLUMN_WISE_ENTRIES',0,NULL);
INSERT INTO table_map 
VALUES(310,'M273_CORPORATE_ACTION_CUSTOMER','T41_CUST_CORP_ACT_DISTRIBUTION',-8,'Security Account in Admin Institution for Old (-8)');
INSERT INTO table_map 
VALUES(321,'M273_CORPORATE_ACTION_CUSTOMER','T42_CUST_CORP_ACT_HOLD_ADJUST',-8,'Security Account in Admin Institution for Old (-8)');
INSERT INTO table_map 
VALUES(322,'M273_CORPORATE_ACTION_CUSTOMER','T43_CUST_CORP_ACT_CASH_ADJUST',-8,'Security Account in Admin Institution for Old (-8)');
INSERT INTO table_map 
VALUES(323,'M391_FUTURES_SPREAD_MATRIX','M18_DERIVATIVE_SPREAD_MATRIX',0,NULL);
INSERT INTO table_map 
VALUES(324,'T87_AUTHORIZATION_REQUEST','T15_AUTHORIZATION_REQUEST',0,NULL);
INSERT INTO table_map 
VALUES(325,'T81_CHANGE_ACCOUNT_REQUESTS','T502_CHANGE_ACCOUNT_REQUESTS_C',0,NULL);
INSERT INTO table_map 
VALUES(326,'T102_TAX_INVOICES','T48_TAX_INVOICES',0,NULL);
INSERT INTO table_map 
VALUES(328,'M284_MURABAHA_BASKETS','M181_MURABAHA_BASKETS',24,'Looped for Extra Institution for NTP (+24)');
INSERT INTO table_map 
VALUES(329,'M285_MURABAHA_BSKT_COMPOSITION','M182_MURABAHA_BSKT_COMPOSITION',55,'Looped for Extra Institution for NTP (+55)');
INSERT INTO table_map 
VALUES(330,'T119_MARK_TO_MARKET','T70_MARK_TO_MARKET',0,NULL);
INSERT INTO table_map 
VALUES(341,'T85_MURABAHA_CONTRACTS','T75_MURABAHA_CONTRACTS',0,NULL);
INSERT INTO table_map 
VALUES(343,'T78_HOLDINGS_BLOCK','T67_STOCK_BLOCK_REQUEST',0,NULL);
INSERT INTO table_map 
VALUES(344,'T87_MURABAHA_AMORTIZE','T90_MURABAHA_AMORTIZE',0,NULL);

COMMIT;

DECLARE
    l_count   NUMBER := 0;
    l_table   VARCHAR2 (50) := 'row_count_ntp';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM user_tables
     WHERE table_name = UPPER (l_table);

    IF (l_count = 1)
    THEN
        EXECUTE IMMEDIATE 'DROP TABLE ' || l_table || '';
    END IF;

    EXECUTE IMMEDIATE
           'CREATE TABLE '
        || l_table
        || ' AS
    SELECT table_name, num_rows, owner
      FROM all_tables
     WHERE owner IN (''DFN_NTP'')';
END;
/

DECLARE
    l_count   NUMBER := 0;
    l_table   VARCHAR2 (50) := 'row_count_gbl';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM user_tables
     WHERE table_name = UPPER (l_table);

    IF (l_count = 1)
    THEN
        EXECUTE IMMEDIATE 'DROP TABLE ' || l_table || '';
    END IF;

    EXECUTE IMMEDIATE
           'CREATE TABLE '
        || l_table
        || ' AS
    SELECT table_name, num_rows, owner
      FROM all_tables@mubasher_db_link
     WHERE owner IN (''MUBASHER_OMS'')';
END;
/

DECLARE
    l_count   NUMBER := 0;
    l_table   VARCHAR2 (50) := 'row_count_differences';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM user_tables
     WHERE table_name = UPPER (l_table);

    IF (l_count = 1)
    THEN
        EXECUTE IMMEDIATE 'DROP TABLE ' || l_table || '';
    END IF;
END;
/

CREATE TABLE row_count_differences
AS
      SELECT *
        FROM (SELECT mapping.seq_id,
                     ntp.table_name,
                     gbl.table_name AS old_name,
                     ntp.num_rows AS new,
                     gbl.num_rows AS old,
                     mapping.expected_diff,
                     ntp.num_rows - gbl.num_rows AS actual_diff,
                     mapping.comments,
                     CASE
                         WHEN gbl.num_rows + mapping.expected_diff =
                                  ntp.num_rows
                         THEN
                             'YES'
                         ELSE
                             'NO'
                     END
                         AS equal
                FROM row_count_ntp ntp
                     JOIN table_map mapping
                         ON table_name = mapping.ntp_name
                     JOIN row_count_gbl gbl
                         ON gbl.table_name = mapping.at_name)
    ORDER BY equal, ABS (actual_diff);

COMMIT;
