DECLARE
    l_sqlerrm   VARCHAR2 (4000);

    l_rec_cnt   NUMBER := 0;
BEGIN
    DELETE FROM error_log
          WHERE mig_table = 'ESP_TODAYS_SNAPSHOTS';

    FOR i
        IN (SELECT mub.companycode,
                   NVL (map16.map16_ntp_code, mub.exchangecode)
                       AS exchangecode,
                   mub.symbol,
                   mub.sector,
                   mub.symboldescription_1,
                   mub.symboldescription_2,
                   mub.symbolshortdescription_1,
                   mub.symbolshortdescription_2,
                   mub.symbolstatus,
                   mub.assetclass,
                   mub.currency,
                   mub.lastupdatedtime,
                   mub.lasttradetime,
                   mub.tradetick,
                   mub.asktick,
                   mub.bidtick,
                   mub.bestaskprice,
                   mub.bestaskquantity,
                   mub.bestbidprice,
                   mub.bestbidquantity,
                   mub.lasttradeprice,
                   mub.lasttradequantity,
                   mub.high,
                   mub.low,
                   mub.change,
                   mub.volume,
                   mub.turnover,
                   mub.percentchanged,
                   mub.previousclosed,
                   mub.todaysopen,
                   mub.updated,
                   mub.nooftrades,
                   mub.noofbids,
                   mub.noofasks,
                   mub.vwap,
                   mub.minprice,
                   mub.maxprice,
                   mub.highpriceof52weeks,
                   mub.highpriceof52weeksdate,
                   mub.lowpriceof52weeks,
                   mub.lowpriceof52weeksdate,
                   mub.is52weeksconsistsoflasttrade,
                   mub.beginingofyear,
                   mub.lastsequenceno,
                   mub.per,
                   mub.pbr,
                   mub.marketcap,
                   mub.yield,
                   mub.totalbidqty,
                   mub.totalaskqty,
                   mub.highask,
                   mub.lowbid,
                   mub.lastaskprice,
                   mub.lastbidprice,
                   mub.bidaskratio,
                   mub.simpleavgask,
                   mub.weightedavgask,
                   mub.simpleavgbid,
                   mub.weightedavgbid,
                   mub.avgvolume,
                   mub.acronym_1,
                   mub.acronym_2,
                   mub.paid_shares,
                   mub.face_value,
                   mub.coupon_value,
                   mub.coupon_date,
                   mub.net_profit,
                   mub.net_profit_date,
                   mub.eps,
                   mub.lasttradeddate,
                   mub.is_active,
                   mub.todaysclosed,
                   mub.lasttradedprice,
                   mub.created_date,
                   mub.ref_price,
                   mub.strikeprice,
                   mub.openinterest,
                   mub.expirydate,
                   mub.optiontype,
                   mub.instrumenttype,
                   mub.equitysymbol,
                   mub.benchmark,
                   mub.performance_ytd,
                   mub.performance_12m,
                   mub.performance_3y,
                   mub.performance_5y,
                   mub.management_fee,
                   mub.dealing_deadline,
                   mub.no_of_shares_for_foreigners,
                   mub.cashinnooforders,
                   mub.cashinturnover,
                   mub.cashinvolume,
                   mub.cashoutnooforders,
                   mub.cashoutturnover,
                   mub.cashoutvolume,
                   mub.change_in_openinterest,
                   mub.settlment_price,
                   mub.issue_capital,
                   mub.tick_size,
                   mub.intrinsic_value,
                   mub.float_shares,
                   mub.settle_type,
                   mub.twap,
                   mub.closing_vwap,
                   mub.loosing_category,
                   mub.nominal_value,
                   mub.shariah_status,
                   mub.toprice,
                   mub.tovolume,
                   mub.tcprice,
                   mub.tcvolume,
                   mub.twap_prm,
                   mub.avg_trd_prc_prm,
                   mub.market_capital,
                   mub.share_capital,
                   mub.day_count_method,
                   mub.calculated_vwap,
                   mub.monthly_high,
                   mub.monthly_low,
                   mub.yearly_high,
                   mub.yearly_low,
                   mub.static_min,
                   mub.static_max,
                   mub.settlement_price,
                   ntp.exchangecode AS ntp_exchangecode,
                   ntp.symbol AS ntp_symbol
              FROM mubasher_price.esp_todays_snapshots@mubasher_price_link mub,
                   map16_optional_exchanges_m01 map16,
                   dfn_price.esp_todays_snapshots ntp
             WHERE     mub.exchangecode = map16.map16_oms_code(+)
                   AND NVL (map16.map16_ntp_code, mub.exchangecode) =
                           ntp.exchangecode(+)
                   AND mub.symbol = ntp.symbol(+))
    LOOP
        BEGIN
            IF (i.ntp_exchangecode IS NULL AND i.ntp_symbol IS NULL)
            THEN
                INSERT
                  INTO dfn_price.esp_todays_snapshots (
                           companycode,
                           exchangecode,
                           symbol,
                           sector,
                           symboldescription_1,
                           symboldescription_2,
                           symbolshortdescription_1,
                           symbolshortdescription_2,
                           symbolstatus,
                           assetclass,
                           currency,
                           lastupdatedtime,
                           lasttradetime,
                           tradetick,
                           asktick,
                           bidtick,
                           bestaskprice,
                           bestaskquantity,
                           bestbidprice,
                           bestbidquantity,
                           lasttradeprice,
                           lasttradequantity,
                           high,
                           low,
                           change,
                           volume,
                           turnover,
                           percentchanged,
                           previousclosed,
                           todaysopen,
                           updated,
                           nooftrades,
                           noofbids,
                           noofasks,
                           vwap,
                           minprice,
                           maxprice,
                           highpriceof52weeks,
                           highpriceof52weeksdate,
                           lowpriceof52weeks,
                           lowpriceof52weeksdate,
                           is52weeksconsistsoflasttrade,
                           beginingofyear,
                           lastsequenceno,
                           per,
                           pbr,
                           marketcap,
                           yield,
                           totalbidqty,
                           totalaskqty,
                           highask,
                           lowbid,
                           lastaskprice,
                           lastbidprice,
                           bidaskratio,
                           simpleavgask,
                           weightedavgask,
                           simpleavgbid,
                           weightedavgbid,
                           avgvolume,
                           acronym_1,
                           acronym_2,
                           paid_shares,
                           face_value,
                           coupon_value,
                           coupon_date,
                           net_profit,
                           net_profit_date,
                           eps,
                           lasttradeddate,
                           is_active,
                           todaysclosed,
                           lasttradedprice,
                           created_date,
                           ref_price,
                           strikeprice,
                           openinterest,
                           expirydate,
                           optiontype,
                           instrumenttype,
                           equitysymbol,
                           benchmark,
                           performance_ytd,
                           performance_12m,
                           performance_3y,
                           performance_5y,
                           management_fee,
                           dealing_deadline,
                           no_of_shares_for_foreigners,
                           cashinnooforders,
                           cashinturnover,
                           cashinvolume,
                           cashoutnooforders,
                           cashoutturnover,
                           cashoutvolume,
                           change_in_openinterest,
                           settlment_price,
                           issue_capital,
                           tick_size,
                           intrinsic_value,
                           float_shares,
                           settle_type,
                           twap,
                           closing_vwap,
                           loosing_category,
                           nominal_value,
                           shariah_status,
                           toprice,
                           tovolume,
                           tcprice,
                           tcvolume,
                           twap_prm,
                           avg_trd_prc_prm,
                           market_capital,
                           share_capital,
                           day_count_method,
                           calculated_vwap,
                           monthly_high,
                           monthly_low,
                           yearly_high,
                           yearly_low,
                           static_min,
                           static_max,
                           settlement_price)
                VALUES (i.companycode,
                        i.exchangecode,
                        i.symbol,
                        i.sector,
                        i.symboldescription_1,
                        i.symboldescription_2,
                        i.symbolshortdescription_1,
                        i.symbolshortdescription_2,
                        i.symbolstatus,
                        i.assetclass,
                        i.currency,
                        i.lastupdatedtime,
                        i.lasttradetime,
                        i.tradetick,
                        i.asktick,
                        i.bidtick,
                        i.bestaskprice,
                        i.bestaskquantity,
                        i.bestbidprice,
                        i.bestbidquantity,
                        i.lasttradeprice,
                        i.lasttradequantity,
                        i.high,
                        i.low,
                        i.change,
                        i.volume,
                        i.turnover,
                        i.percentchanged,
                        i.previousclosed,
                        i.todaysopen,
                        i.updated,
                        i.nooftrades,
                        i.noofbids,
                        i.noofasks,
                        i.vwap,
                        i.minprice,
                        i.maxprice,
                        i.highpriceof52weeks,
                        i.highpriceof52weeksdate,
                        i.lowpriceof52weeks,
                        i.lowpriceof52weeksdate,
                        i.is52weeksconsistsoflasttrade,
                        i.beginingofyear,
                        i.lastsequenceno,
                        i.per,
                        i.pbr,
                        i.marketcap,
                        i.yield,
                        i.totalbidqty,
                        i.totalaskqty,
                        i.highask,
                        i.lowbid,
                        i.lastaskprice,
                        i.lastbidprice,
                        i.bidaskratio,
                        i.simpleavgask,
                        i.weightedavgask,
                        i.simpleavgbid,
                        i.weightedavgbid,
                        i.avgvolume,
                        i.acronym_1,
                        i.acronym_2,
                        i.paid_shares,
                        i.face_value,
                        i.coupon_value,
                        i.coupon_date,
                        i.net_profit,
                        i.net_profit_date,
                        i.eps,
                        i.lasttradeddate,
                        i.is_active,
                        i.todaysclosed,
                        i.lasttradedprice,
                        i.created_date,
                        i.ref_price,
                        i.strikeprice,
                        i.openinterest,
                        i.expirydate,
                        i.optiontype,
                        i.instrumenttype,
                        i.equitysymbol,
                        i.benchmark,
                        i.performance_ytd,
                        i.performance_12m,
                        i.performance_3y,
                        i.performance_5y,
                        i.management_fee,
                        i.dealing_deadline,
                        i.no_of_shares_for_foreigners,
                        i.cashinnooforders,
                        i.cashinturnover,
                        i.cashinvolume,
                        i.cashoutnooforders,
                        i.cashoutturnover,
                        i.cashoutvolume,
                        i.change_in_openinterest,
                        i.settlment_price,
                        i.issue_capital,
                        i.tick_size,
                        i.intrinsic_value,
                        i.float_shares,
                        i.settle_type,
                        i.twap,
                        i.closing_vwap,
                        i.loosing_category,
                        i.nominal_value,
                        i.shariah_status,
                        i.toprice,
                        i.tovolume,
                        i.tcprice,
                        i.tcvolume,
                        i.twap_prm,
                        i.avg_trd_prc_prm,
                        i.market_capital,
                        i.share_capital,
                        i.day_count_method,
                        i.calculated_vwap,
                        i.monthly_high,
                        i.monthly_low,
                        i.yearly_high,
                        i.yearly_low,
                        i.static_min,
                        i.static_max,
                        i.settlement_price);
            ELSE
                UPDATE dfn_price.esp_todays_snapshots
                   SET todaysclosed = i.todaysclosed,
                       previousclosed = i.previousclosed,
                       minprice = i.minprice,
                       maxprice = i.maxprice,
                       vwap = i.vwap,
                       lasttradeprice = i.lasttradeprice,
                       bestbidprice = i.bestbidprice,
                       bestaskprice = i.bestaskprice,
                       strikeprice = i.strikeprice,
                       static_min = i.static_min,
                       static_max = i.static_max,
                       settlement_price = i.settlement_price
                 WHERE     exchangecode = i.ntp_exchangecode
                       AND symbol = i.ntp_symbol;
            END IF;

            l_rec_cnt := l_rec_cnt + 1;

            IF MOD (l_rec_cnt, 25000) = 0
            THEN
                COMMIT;
            END IF;
        EXCEPTION
            WHEN OTHERS
            THEN
                l_sqlerrm := SUBSTR (SQLERRM, 1, 512);

                INSERT INTO error_log
                     VALUES (
                                'ESP_TODAYS_SNAPSHOTS',
                                   ' Exg: '
                                || i.exchangecode
                                || ' - '
                                || ' Symbol: '
                                || i.symbol,
                                   ' Exg: '
                                || i.exchangecode
                                || ' - '
                                || ' Symbol: '
                                || i.symbol,
                                l_sqlerrm,
                                CASE
                                    WHEN (    i.ntp_exchangecode IS NULL
                                          AND i.ntp_symbol IS NULL)
                                    THEN
                                        'INSERT'
                                    ELSE
                                        'UPDATE'
                                END,
                                SYSDATE);
        END;
    END LOOP;
END;
/