/* Formatted on 1/11/2021 11:22:49 PM (QP5 v5.206) */
DECLARE
    l_m01_id   NUMBER := 0;
BEGIN
    DELETE dfn_ntp.m54_boards;

    COMMIT;

    UPDATE dfn_ntp.app_seq_store
       SET app_seq_value = 0
     WHERE app_seq_name = 'M54_BOARDS';

    COMMIT;

    FOR i IN (SELECT m01_exchange_code, m01_id
                FROM dfn_ntp.m01_exchanges
               WHERE m01_exchange_code <> 'TDWL')
    LOOP
        INSERT INTO dfn_ntp.m54_boards (m54_id,
                                        m54_exchange_code_m01,
                                        m54_exchange_id_m01,
                                        m54_code,
                                        m54_exg_brd_status_id_v19,
                                        m54_exg_brd_sts_updated_date,
                                        m54_is_default,
                                        m54_is_active,
                                        m54_preopen_allowed,
                                        m54_last_preopened_date,
                                        m54_last_eod_date,
                                        m54_status_id_v01,
                                        m54_status_changed_by_id_u17,
                                        m54_status_changed_date,
                                        m54_created_by_id_u17,
                                        m54_created_date,
                                        m54_modified_by_id_u17,
                                        m54_modified_date,
                                        m54_custom_type,
                                        m54_primary_institution_id_m02,
                                        m54_price_brd_code,
                                        m54_trade_type_v01,
                                        m54_is_active_process,
                                        m54_manual_suspend,
                                        m54_price_fluctuation,
                                        m54_last_symbol_status_req_dat,
                                        m54_last_market_status_req_dat)
             VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                     i.m01_exchange_code,
                     i.m01_id,
                     'ALL',                                         --m54_code
                     3,
                     SYSDATE,
                     1,                                       --m54_is_default
                     1,
                     0,                                  --m54_preopen_allowed
                     SYSDATE - 1,
                     SYSDATE - 1,
                     2,
                     NULL,
                     NULL,
                     1,
                     SYSDATE,
                     NULL,
                     NULL,
                     '1',
                     1,
                     NULL,
                     1,
                     'NONE',
                     NULL,
                     NULL,
                     NULL,
                     NULL);
    END LOOP;


    SELECT m01_id
      INTO l_m01_id
      FROM dfn_ntp.m01_exchanges
     WHERE m01_exchange_code = 'TDWL';

    INSERT INTO dfn_ntp.m54_boards (m54_id,
                                    m54_exchange_code_m01,
                                    m54_exchange_id_m01,
                                    m54_code,
                                    m54_exg_brd_status_id_v19,
                                    m54_exg_brd_sts_updated_date,
                                    m54_is_default,
                                    m54_is_active,
                                    m54_preopen_allowed,
                                    m54_last_preopened_date,
                                    m54_last_eod_date,
                                    m54_status_id_v01,
                                    m54_status_changed_by_id_u17,
                                    m54_status_changed_date,
                                    m54_created_by_id_u17,
                                    m54_created_date,
                                    m54_modified_by_id_u17,
                                    m54_modified_date,
                                    m54_custom_type,
                                    m54_primary_institution_id_m02,
                                    m54_price_brd_code,
                                    m54_trade_type_v01,
                                    m54_is_active_process,
                                    m54_manual_suspend,
                                    m54_price_fluctuation,
                                    m54_last_symbol_status_req_dat,
                                    m54_last_market_status_req_dat)
         VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                 'TDWL',
                 l_m01_id,
                 'SAEQ',                                            --m54_code
                 3,
                 SYSDATE,
                 1,                                           --m54_is_default
                 1,
                 1,                                      --m54_preopen_allowed
                 SYSDATE - 1,
                 SYSDATE - 1,
                 2,
                 NULL,
                 NULL,
                 1,
                 SYSDATE,
                 NULL,
                 NULL,
                 '1',
                 1,
                 NULL,
                 1,
                 'NONE',
                 NULL,
                 NULL,
                 NULL,
                 NULL);

    INSERT INTO dfn_ntp.m54_boards (m54_id,
                                    m54_exchange_code_m01,
                                    m54_exchange_id_m01,
                                    m54_code,
                                    m54_exg_brd_status_id_v19,
                                    m54_exg_brd_sts_updated_date,
                                    m54_is_default,
                                    m54_is_active,
                                    m54_preopen_allowed,
                                    m54_last_preopened_date,
                                    m54_last_eod_date,
                                    m54_status_id_v01,
                                    m54_status_changed_by_id_u17,
                                    m54_status_changed_date,
                                    m54_created_by_id_u17,
                                    m54_created_date,
                                    m54_modified_by_id_u17,
                                    m54_modified_date,
                                    m54_custom_type,
                                    m54_primary_institution_id_m02,
                                    m54_price_brd_code,
                                    m54_trade_type_v01,
                                    m54_is_active_process,
                                    m54_manual_suspend,
                                    m54_price_fluctuation,
                                    m54_last_symbol_status_req_dat,
                                    m54_last_market_status_req_dat)
         VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                 'TDWL',
                 l_m01_id,
                 'SADF',                                            --m54_code
                 3,
                 SYSDATE,
                 1,                                           --m54_is_default
                 1,
                 1,                                      --m54_preopen_allowed
                 SYSDATE - 1,
                 SYSDATE - 1,
                 2,
                 NULL,
                 NULL,
                 1,
                 SYSDATE,
                 NULL,
                 NULL,
                 '1',
                 1,
                 NULL,
                 1,
                 'NONE',
                 NULL,
                 NULL,
                 NULL,
                 NULL);

    INSERT INTO dfn_ntp.m54_boards (m54_id,
                                    m54_exchange_code_m01,
                                    m54_exchange_id_m01,
                                    m54_code,
                                    m54_exg_brd_status_id_v19,
                                    m54_exg_brd_sts_updated_date,
                                    m54_is_default,
                                    m54_is_active,
                                    m54_preopen_allowed,
                                    m54_last_preopened_date,
                                    m54_last_eod_date,
                                    m54_status_id_v01,
                                    m54_status_changed_by_id_u17,
                                    m54_status_changed_date,
                                    m54_created_by_id_u17,
                                    m54_created_date,
                                    m54_modified_by_id_u17,
                                    m54_modified_date,
                                    m54_custom_type,
                                    m54_primary_institution_id_m02,
                                    m54_price_brd_code,
                                    m54_trade_type_v01,
                                    m54_is_active_process,
                                    m54_manual_suspend,
                                    m54_price_fluctuation,
                                    m54_last_symbol_status_req_dat,
                                    m54_last_market_status_req_dat)
         VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                 'TDWL',
                 l_m01_id,
                 'SAEQ_U',                                          --m54_code
                 3,
                 SYSDATE,
                 1,                                           --m54_is_default
                 1,
                 1,                                      --m54_preopen_allowed
                 SYSDATE - 1,
                 SYSDATE - 1,
                 2,
                 NULL,
                 NULL,
                 1,
                 SYSDATE,
                 NULL,
                 NULL,
                 '1',
                 1,
                 NULL,
                 1,
                 'NONE',
                 NULL,
                 NULL,
                 NULL,
                 NULL);


    INSERT INTO dfn_ntp.m54_boards (m54_id,
                                    m54_exchange_code_m01,
                                    m54_exchange_id_m01,
                                    m54_code,
                                    m54_exg_brd_status_id_v19,
                                    m54_exg_brd_sts_updated_date,
                                    m54_is_default,
                                    m54_is_active,
                                    m54_preopen_allowed,
                                    m54_last_preopened_date,
                                    m54_last_eod_date,
                                    m54_status_id_v01,
                                    m54_status_changed_by_id_u17,
                                    m54_status_changed_date,
                                    m54_created_by_id_u17,
                                    m54_created_date,
                                    m54_modified_by_id_u17,
                                    m54_modified_date,
                                    m54_custom_type,
                                    m54_primary_institution_id_m02,
                                    m54_price_brd_code,
                                    m54_trade_type_v01,
                                    m54_is_active_process,
                                    m54_manual_suspend,
                                    m54_price_fluctuation,
                                    m54_last_symbol_status_req_dat,
                                    m54_last_market_status_req_dat)
         VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                 'TDWL',
                 l_m01_id,
                 'SAFI',                                            --m54_code
                 3,
                 SYSDATE,
                 1,                                           --m54_is_default
                 1,
                 1,                                      --m54_preopen_allowed
                 SYSDATE - 1,
                 SYSDATE - 1,
                 2,
                 NULL,
                 NULL,
                 1,
                 SYSDATE,
                 NULL,
                 NULL,
                 '1',
                 1,
                 NULL,
                 1,
                 'NONE',
                 NULL,
                 NULL,
                 NULL,
                 NULL);

    INSERT INTO dfn_ntp.m54_boards (m54_id,
                                    m54_exchange_code_m01,
                                    m54_exchange_id_m01,
                                    m54_code,
                                    m54_exg_brd_status_id_v19,
                                    m54_exg_brd_sts_updated_date,
                                    m54_is_default,
                                    m54_is_active,
                                    m54_preopen_allowed,
                                    m54_last_preopened_date,
                                    m54_last_eod_date,
                                    m54_status_id_v01,
                                    m54_status_changed_by_id_u17,
                                    m54_status_changed_date,
                                    m54_created_by_id_u17,
                                    m54_created_date,
                                    m54_modified_by_id_u17,
                                    m54_modified_date,
                                    m54_custom_type,
                                    m54_primary_institution_id_m02,
                                    m54_price_brd_code,
                                    m54_trade_type_v01,
                                    m54_is_active_process,
                                    m54_manual_suspend,
                                    m54_price_fluctuation,
                                    m54_last_symbol_status_req_dat,
                                    m54_last_market_status_req_dat)
         VALUES (dfn_ntp.fn_get_next_sequnce ('M54_BOARDS'),
                 'TDWL',
                 l_m01_id,
                 'ALL',                                             --m54_code
                 3,
                 SYSDATE,
                 1,                                           --m54_is_default
                 1,
                 1,                                      --m54_preopen_allowed
                 SYSDATE - 1,
                 SYSDATE - 1,
                 2,
                 NULL,
                 NULL,
                 1,
                 SYSDATE,
                 NULL,
                 NULL,
                 '1',
                 1,
                 NULL,
                 1,
                 'NONE',
                 NULL,
                 NULL,
                 NULL,
                 NULL);
END;
/
commit;
