-- Foreign Key for  DFN_NTP.F02_FALCON_PROCESSES

ALTER TABLE DFN_NTP.F02_FALCON_PROCESSES ADD CONSTRAINT FK_F02_F03_RUN_CONTROLLER_ID
  FOREIGN KEY (
F02_RUN_CONTROLLER_ID_F03
)
 REFERENCES DFN_NTP.F03_FALCON_CONTROLLERS
 ENABLE
 VALIDATE
/

ALTER TABLE DFN_NTP.F02_FALCON_PROCESSES ADD CONSTRAINT FK_F02_F03_KILL_CONTROLLER_ID
  FOREIGN KEY (
F02_KILL_CONTROLLER_ID_F03
)
 REFERENCES DFN_NTP.F03_FALCON_CONTROLLERS
 ENABLE
 VALIDATE
/

-- End of REF DDL Script for Table DFN_NTP.F02_FALCON_PROCESSES
